Repository widelands/widelands, pull requests merged in 2020-12, with the labels that each got.

#4539 Inform about required restart after installing world add-ons
  README.md
  doc/sphinx/source/add-ons.rst
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
Labels: addon

#4547 Improve profile handling of translatable strings
  doc/sphinx/source/add-ons.rst
  src/io/profile.cc
  src/io/profile.h
  src/logic/addons.cc
  src/logic/map.cc
  src/logic/map.h
  src/map_io/map_elemental_packet.cc
Labels: enhancement, internationalization

#4541 Some more add-on features
  .github/workflows/build.yaml
  .travis.yml
  debian/control
  src/editor/editorinteractive.cc
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/game_io/game_loader.cc
  src/game_io/game_preload_packet.cc
  src/game_io/game_preload_packet.h
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game_settings.h
  src/logic/map.h
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/worker_descr.cc
  src/logic/map_objects/tribes/worker_descr.h
  src/map_io/map_elemental_packet.cc
  src/map_io/map_loader.h
  src/map_io/s2map.cc
  src/map_io/s2map.h
  src/map_io/widelands_map_loader.cc
  src/map_io/widelands_map_loader.h
  src/network/net_addons.cc
  src/network/net_addons.h
  src/scripting/lua_globals.cc
  src/scripting/lua_root.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/ui_fsmenu/campaigns.cc
  src/ui_fsmenu/mapselect.cc
  src/wlapplication.cc
  src/wui/gamedetails.cc
  src/wui/mapdata.h
  src/wui/mapdetails.cc
  src/wui/savegamedata.h
Labels: addon, enhancement, lua

#4526 Refactor toolbar and overlay strings to an info panel
  data/images/wui/toolbar/center_inv.png
  data/images/wui/toolbar/left_corner_inv.png
  data/images/wui/toolbar/left_inv.png
  data/images/wui/toolbar/right_corner_inv.png
  data/images/wui/toolbar/right_inv.png
  data/tribes/initialization/amazons/images/toolbar_center.png
  data/tribes/initialization/amazons/images/toolbar_left.png
  data/tribes/initialization/amazons/images/toolbar_left_corner.png
  data/tribes/initialization/amazons/images/toolbar_right.png
  data/tribes/initialization/amazons/images/toolbar_right_corner.png
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/frisians/units.lua
  src/editor/editorinteractive.cc
  src/graphic/toolbar_imageset.cc
  src/graphic/toolbar_imageset.h
  src/logic/game.cc
  src/ui_fsmenu/options.cc
  src/wlapplication.cc
  src/wui/CMakeLists.txt
  src/wui/game_message_menu.cc
  src/wui/game_message_menu.h
  src/wui/info_panel.cc
  src/wui/info_panel.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_player.cc
  src/wui/toolbar.cc
  src/wui/toolbar.h
Labels: enhancement, graphics, ui

#4530 Accessibility Options
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/mapview.cc
  src/wui/mapview.h
Labels: accessibility, enhancement

#4520 Allow hiding players from the general statistics menu via Lua
  data/campaigns/emp02.wmf/scripting/mission_thread.lua
  data/campaigns/emp02.wmf/scripting/starting_conditions.lua
  data/campaigns/fri01.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/mission_thread.lua
  src/game_io/game_player_info_packet.cc
  src/logic/player.cc
  src/logic/player.h
  src/notifications/note_ids.h
  src/scripting/lua_game.cc
  src/scripting/lua_game.h
  src/wui/general_statistics_menu.cc
  src/wui/general_statistics_menu.h
Labels: campaigns & scenarios, enhancement, statistics

#4559 Fix two info panel crashes
  src/wui/info_panel.cc
Labels: bug, crashes or hangs

#4564 Fix travis
  .travis.yml
Labels: building & packaging, macos

#4515 Allow savegames anywhere
  src/io/filesystem/layered_filesystem.cc
  src/logic/replay.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/wlapplication.cc
  src/wlapplication_messages.cc
Labels: filesystem, saveloading & compatibility
