Repository widelands/widelands, pull requests merged in 2020-10, with the labels that each got.

#4290 Fix random map generator terrain selection
  data/world/map_generation.lua
  src/logic/map_objects/world/map_gen.cc
Labels: bug, crashes or hangs, editor, maps, world

#4301 Refactor string assembly in MapDetailsBox
  src/ui_basic/multilinetextarea.cc
  src/ui_fsmenu/mapdetailsbox.cc
Labels: cleanup & refactoring, internationalization

#4292 Draw checkbox borders on top of focus overlay
  src/ui_basic/checkbox.cc
  src/ui_basic/checkbox.h
Labels: bug, ui

#4330 Handle additional expedition items in fri01/fri02
  data/campaigns/fri01.wmf/scripting/mission_thread.lua
  data/campaigns/fri01.wmf/scripting/texts.lua
  data/campaigns/fri02.wmf/scripting/init.lua
  data/campaigns/fri02.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/starting_conditions.lua
  data/campaigns/fri02.wmf/scripting/texts.lua
  src/game_io/game_player_info_packet.cc
  src/logic/player.cc
  src/logic/player.h
  src/scripting/lua_game.cc
  src/scripting/lua_game.h
  src/scripting/lua_map.cc
  src/wui/portdockwaresdisplay.cc
  test/maps/ship_transportation.wmf/scripting/test_rip_second_port_with_worker_in_portdock.lua
Labels: bug, campaigns & scenarios, lua, seafaring

#4297 Delete the `is_a()` macro
  src/ai/ai_help_structs.cc
  src/ai/defaultai.cc
  src/base/macros.h
  src/economy/road.cc
  src/economy/transfer.cc
  src/economy/ware_instance.cc
  src/economy/waterway.cc
  src/editor/editorinteractive.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.h
  src/logic/map.cc
  src/logic/map_objects/bob.cc
  src/logic/map_objects/tribes/carrier.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/worker.cc
  src/logic/map_objects/world/critter.cc
  src/logic/player.cc
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_object_saver.cc
  src/map_io/map_saver.cc
  src/scripting/lua_map.cc
  src/wui/buildingwindow.cc
  src/wui/fieldaction.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_spectator.cc
Labels: cleanup & refactoring, memory & performance

#4342 Clear minimap icon on multiselect
  src/wui/gamedetails.cc
Labels: ui

#4302 Immovable targeting fixes
  src/logic/playercommand.cc
  src/wui/fieldaction.cc
Labels: bug, desync, replay, ui

#4326 Improve testsuite error handling
  regression_test.py
  src/base/exceptions.cc
  src/base/wexception.h
  src/logic/cmd_luacoroutine.cc
  src/wlapplication.cc
  src/wlapplication_messages.cc
Labels: crashes or hangs, enhancement, lua, testing

#4337 Fix statistics button translation
  data/scripting/win_conditions/artifacts.lua
  data/scripting/win_conditions/collectors.lua
  data/scripting/win_conditions/territorial_functions.lua
  data/scripting/win_conditions/wood_gnome.lua
Labels: internationalization, lua, saveloading & compatibility

#4313 Unload expeditions at once
  src/logic/map_objects/tribes/ship.cc
  src/wui/seafaring_statistics_menu.cc
  src/wui/seafaring_statistics_menu.h
Labels: seafaring

#4282 Generalize building- and ship windows to use InteractiveBase
  src/editor/editorinteractive.h
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
  src/wui/constructionsitewindow.cc
  src/wui/constructionsitewindow.h
  src/wui/dismantlesitewindow.cc
  src/wui/dismantlesitewindow.h
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/militarysitewindow.cc
  src/wui/militarysitewindow.h
  src/wui/productionsitewindow.cc
  src/wui/productionsitewindow.h
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
  src/wui/soldiercapacitycontrol.cc
  src/wui/soldiercapacitycontrol.h
  src/wui/soldierlist.cc
  src/wui/soldierlist.h
  src/wui/trainingsitewindow.cc
  src/wui/trainingsitewindow.h
  src/wui/warehousewindow.cc
  src/wui/warehousewindow.h
Labels: cleanup & refactoring

#4357 Box Layouting Fixes
  src/editor/ui_menus/main_menu_map_options.cc
  src/ui_basic/box.cc
  src/wui/CMakeLists.txt
  src/wui/economy_options_window.cc
  src/wui/game_chat_panel.cc
  src/wui/game_summary.cc
  src/wui/game_summary.h
Labels: bug, ui

#4377 Fix memset compiler warning
  src/logic/map.cc
Labels: cleanup & refactoring

#4387 Fix `stol` out-of-range error on saveloading
  src/map_io/map_players_view_packet.cc
Labels: bug, saveloading & compatibility

#4393 Fix WareStatisticsMenu main box assert
  src/wui/ware_statistics_menu.cc
Labels: bug, crashes or hangs, ui

#4289 Random matches & Editor launching convenience
  src/editor/CMakeLists.txt
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/editor/map_generator.cc
  src/editor/map_generator.h
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_random_map.h
  src/logic/game.cc
  src/logic/map.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/base.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/launch_spg.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/mapdetailsbox.h
  src/wlapplication.cc
  src/wlapplication.h
Labels: editor, enhancement, maps, ui

#4385 Table/Tabpanel Navigation
  src/ui_basic/table.cc
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
Labels: accessibility, enhancement

#4390 Overhaul building statistics menu
  src/ui_basic/spinbox.cc
  src/wui/building_statistics_menu.cc
  src/wui/building_statistics_menu.h
Labels: bug, cleanup & refactoring, enhancement, ui

#4376 Wares/Workers Cheats
  src/editor/editorinteractive.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/map_objects/tribes/worker.h
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/productionsitewindow.cc
  src/wui/productionsitewindow.h
  src/wui/warehousewindow.cc
Labels: enhancement, tribes, ui

#4381 Draw road length tooltip in road building mode
  src/wui/interactive_base.cc
Labels: enhancement, ui

#4391 Change geologist's mountain definition
  src/logic/map_objects/tribes/worker.cc
Labels: balancing & gameplay, tribes, world

#4397 Refactor PartiallyFinishedBuildingDetails
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/constructionsite.h
  src/logic/player.cc
  src/logic/player.h
  src/map_io/map_players_view_packet.cc
  src/wui/interactive_player.cc
Labels: cleanup & refactoring, memory & performance

#4366 Focus indicator tweaks
  data/templates/default/init.lua
  src/ui_basic/button.cc
  src/ui_basic/button.h
  src/ui_basic/checkbox.cc
  src/ui_basic/checkbox.h
  src/ui_basic/dropdown.cc
  src/ui_basic/dropdown.h
  src/ui_basic/multilinetextarea.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/scrollbar.cc
Labels: accessibility, graphics

#4403 Goodbye Travis
  .github/workflows/build.yaml
  .travis.sh
  .travis.yml
  README.md
Labels: building & packaging, testing

#4414 Try to fix transient SDL error handling
  .github/workflows/build.yaml
Labels: testing

#4449 Tweak some random map terrain definitions
  data/world/map_generation.lua
Labels: maps, world

#4430 Set OpenGL swap interval to 0
  src/graphic/gl/initialize.cc
Labels: memory & performance
