Repository widelands/widelands, pull requests merged in 2020-11, with the labels that each got.

#4435 Split minimap rendering into stages
  src/graphic/CMakeLists.txt
  src/graphic/minimap_renderer.cc
  src/graphic/minimap_renderer.h
  src/wui/minimap.cc
  src/wui/minimap.h
Labels: memory & performance

#4441 Ware Priority Improvements
  src/ai/defaultai_seafaring.cc
  src/economy/CMakeLists.txt
  src/economy/economy.cc
  src/economy/expedition_bootstrap.cc
  src/economy/expedition_bootstrap.h
  src/economy/flag.cc
  src/economy/flag.h
  src/economy/input_queue.cc
  src/economy/input_queue.h
  src/economy/portdock.cc
  src/economy/request.cc
  src/economy/request.h
  src/economy/ware_priority.cc
  src/economy/ware_priority.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/building_settings.cc
  src/logic/map_objects/tribes/building_settings.h
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/constructionsite.h
  src/logic/map_objects/tribes/market.cc
  src/logic/map_objects/tribes/market.h
  src/logic/map_objects/tribes/partially_finished_building.h
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/warehouse.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/map_io/map_building_packet.cc
  src/map_io/map_building_packet.h
  src/map_io/map_buildingdata_packet.cc
  src/scripting/lua_map.cc
  src/ui_basic/icon.cc
  src/ui_basic/icon.h
  src/ui_basic/listselect.h
  src/ui_basic/slider.cc
  src/ui_basic/slider.h
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
  src/wui/constructionsitewindow.cc
  src/wui/dismantlesitewindow.cc
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
  src/wui/portdockwaresdisplay.cc
  src/wui/productionsitewindow.cc
Labels: balancing & gameplay, cleanup & refactoring, enhancement, ui

#4433 Trigger build action after formatting
  .github/workflows/format.yaml
  README.md
Labels: building & packaging, codecheck, testing

#4473 Amazon fixes
  data/tribes/immovables/resi/amazons/init.lua
  data/tribes/immovables/resi/amazons/pics/water_0.5.png
  data/tribes/immovables/resi/amazons/pics/water_1.png
  data/tribes/immovables/resi/amazons/pics/water_2.png
  data/tribes/immovables/resi/amazons/pics/water_4.png
  data/tribes/immovables/resi/amazons/register.lua
  data/tribes/initialization/amazons/units.lua
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/player.cc
  src/logic/player.h
  src/wui/fieldaction.cc
  src/wui/interactive_player.cc
Labels: amazons, bug

#4436 Tweak low productivity threshold in building statistics
  src/ui_basic/box.cc
  src/ui_basic/spinbox.cc
  src/ui_fsmenu/options.cc
  src/wui/building_statistics_menu.cc
Labels: ui

#4469 Random map menu tweaks
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_random_map.h
  src/ui_basic/dropdown.cc
  src/ui_basic/dropdown.h
Labels: editor, enhancement, maps, ui

#4500 Fix formatting action for branches on origin
  .github/workflows/format.yaml
Labels: building & packaging

#4483 Fix savegame compatibility #4482
  src/map_io/map_buildingdata_packet.cc
Labels: bug, saveloading & compatibility

#4461 Saveload lua textdomain stack
  src/map_io/map_scripting_packet.cc
  src/scripting/CMakeLists.txt
  src/scripting/logic.cc
  src/scripting/logic.h
  src/scripting/lua_coroutine.cc
  src/scripting/lua_globals.cc
  src/scripting/lua_globals.h
Labels: bug, lua, saveloading & compatibility

#4477 Option to destroy attack target instead of conquering
  src/ai/defaultai_warfare.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/attack_target.h
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/militarysite.h
  src/logic/map_objects/tribes/warehouse.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/map_io/map_buildingdata_packet.cc
  src/wui/attack_box.cc
  src/wui/attack_box.h
  src/wui/fieldaction.cc
Labels: enhancement, military

#4525 Fix loading saves with see_all players
  src/logic/player.cc
Labels: saveloading & compatibility

#4524 Saveload TrainingSite::checked_soldier_training_ to fix a crash
  src/map_io/map_buildingdata_packet.cc
Labels: crashes or hangs, saveloading & compatibility

#4538 Fix curl on AppVeyor
  appveyor.yml
Labels: building & packaging, windows
