Repository widelands/widelands, pull requests merged in 2020-08, with the labels that each got.

#4042 Increase critter death chance in crowded regions
  src/logic/map.cc
  src/logic/map.h
  src/logic/map_objects/world/critter.cc
Labels: balancing & gameplay, world

#4039 Forbid destroying expedition port construction sites
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/partially_finished_building.cc
  src/logic/map_objects/tribes/ship.cc
Labels: bug, seafaring

#4037 Unblock soldiers
  src/logic/map_objects/tribes/soldier.cc
Labels: bug, military, pathfinding

#4048 Correct shipwright's work area
  src/logic/map_objects/tribes/production_program.cc
Labels: bug, tribes

#3756 Improve spritesheet exporting
  doc/sphinx/source/animations.rst
  src/graphic/animation/animation.cc
  src/graphic/animation/animation.h
  src/graphic/animation/nonpacked_animation.cc
  src/graphic/animation/nonpacked_animation.h
  src/graphic/animation/spritesheet_animation.cc
  src/graphic/animation/spritesheet_animation.h
  src/logic/map_objects/map_object.cc
  src/website/create_spritesheet.cc
Labels: bug, graphics

#4049 Fix z-layering glitches of roads
  src/graphic/render_queue.cc
Labels: bug, graphics

#4034 Add buttons to mute/unmute buildings
  data/images/wui/buildings/menu_mute_all.png
  data/images/wui/buildings/menu_mute_this.png
  data/images/wui/buildings/menu_unmute_all.png
  data/images/wui/buildings/menu_unmute_this.png
  src/game_io/game_player_info_packet.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/map_io/map_buildingdata_packet.cc
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
Labels: enhancement, tribes, ui

#4040 Ship Localization
  data/tribes/atlanteans.lua
  data/tribes/barbarians.lua
  data/tribes/empire.lua
  data/tribes/frisians.lua
  src/economy/shipping_schedule.cc
  src/economy/shipping_schedule.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/player.cc
  src/logic/player.h
  src/wui/seafaring_statistics_menu.cc
Labels: bug, internationalization, seafaring, tribes

#4036 Use player fields for terrain rendering
  src/editor/editorinteractive.cc
  src/graphic/game_renderer.cc
  src/graphic/game_renderer.h
  src/graphic/gl/dither_program.cc
  src/graphic/gl/dither_program.h
  src/graphic/gl/terrain_program.cc
  src/graphic/gl/terrain_program.h
  src/graphic/render_queue.cc
  src/graphic/render_queue.h
  src/wui/interactive_player.cc
  src/wui/interactive_spectator.cc
  src/wui/mapview.cc
  src/wui/mapview.h
Labels: bug, ui, world

#4018 Soldier statistics window
  data/tribes/scripting/help/controls.lua
  src/logic/map_objects/tribes/soldier.cc
  src/logic/player.cc
  src/logic/player.h
  src/ui_basic/icon.cc
  src/ui_basic/icon.h
  src/wui/CMakeLists.txt
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
  src/wui/soldier_statistics_menu.cc
  src/wui/soldier_statistics_menu.h
  src/wui/waresdisplay.cc
  src/wui/waresdisplay.h
Labels: enhancement, military, ui

#4023 Editor Suggested Teams Box
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_map_options.h
  src/logic/map.h
  src/ui_basic/box.cc
  src/ui_basic/box.h
  src/wui/dismantlesitewindow.cc
Labels: editor, enhancement, ui

#4075 Fix disappearing language stats
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
Labels: bug, internationalization, ui

#4046 Refactor playerfields visibility
  src/ai/defaultai.cc
  src/ai/defaultai_seafaring.cc
  src/ai/defaultai_warfare.cc
  src/editor/editorinteractive.cc
  src/graphic/game_renderer.cc
  src/graphic/gl/fields_to_draw.cc
  src/graphic/gl/fields_to_draw.h
  src/graphic/minimap_renderer.cc
  src/logic/editor_game_base.cc
  src/logic/game.cc
  src/logic/map_objects/bob.cc
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/map_object.h
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/worker.cc
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/see_unsee_node.h
  src/map_io/CMakeLists.txt
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_exploration_packet.cc
  src/map_io/map_exploration_packet.h
  src/map_io/map_players_view_packet.cc
  src/map_io/map_players_view_packet.h
  src/map_io/map_saver.cc
  src/map_io/widelands_map_loader.cc
  src/scripting/lua_game.cc
  src/wui/attack_box.cc
  src/wui/fieldaction.cc
  src/wui/game_debug_ui.cc
  src/wui/interactive_base.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_player.cc
  src/wui/watchwindow.cc
Labels: bug, cleanup & refactoring, tribes

#4077 Draw window frames with a different colour when focused
  data/templates/default/init.lua
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/ui_basic/panel.h
  src/ui_basic/window.cc
Labels: accessibility, enhancement, ui

#4082 Fix incorrect allows_seafaring detection
  src/logic/map.cc
Labels: bug, seafaring

#4076 Fix carriers keeping wares
  src/logic/map_objects/tribes/worker.cc
  test/maps/ship_transportation.wmf/scripting/test_create_request_while_worker_with_ware_is_in_transit.lua
Labels: bug, tribes

#4083 Show buildhelp semi-transparent on PreviouslySeen nodes
  src/editor/editorinteractive.cc
  src/game_io/game_interactive_player_packet.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
Labels: cleanup & refactoring, tribes, ui

#4084 Fix terrain glitches in see_all mode
  src/graphic/gl/dither_program.cc
  src/graphic/gl/terrain_program.cc
Labels: bug, ui, world

#4065 Move MS-Windows packaging and integration to a GitHub action
  .github/workflows/windows.yaml
  CMakeLists.txt
  README.md
  appveyor.yml
  data/tribes/scripting/help/controls.lua
  src/graphic/render_queue.cc
  src/logic/field.h
  src/logic/map_objects/map_object.h
  src/logic/map_objects/world/critter.cc
  utils/win32/innosetup/Widelands.iss
Labels: building & packaging, windows

#4095 Fix game saving crash in spectator mode
  src/game_io/game_interactive_player_packet.cc
Labels: crashes or hangs

#4098 Move 32-bit MS-Windows integration for PRs to the action
  .github/workflows/windows.yaml
  README.md
  appveyor.yml
Labels: building & packaging, windows

#4104 Follow-up cornercase fix against carriers keeping wares
  src/economy/idleworkersupply.cc
  src/logic/map_objects/tribes/worker.cc
Labels: bug, crashes or hangs, tribes

#4101 Editor MainMenuLoadOrSaveMap Tweaks
  src/editor/ui_menus/main_menu_load_map.cc
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/editor/ui_menus/main_menu_load_or_save_map.h
  src/editor/ui_menus/main_menu_save_map.cc
Labels: editor, ui

#4114 Remember dismantlesite's state when unseeing a field
  src/logic/map_objects/tribes/partially_finished_building.h
  src/logic/player.cc
  src/logic/player.h
  src/map_io/map_players_view_packet.cc
  src/scripting/lua_game.cc
  src/wui/interactive_player.cc
Labels: bug, ui

#4033 Fix nodecaps calculation error
  data/maps/Crossing_the_Horizon_v2.wmf/elemental
  data/maps/Long, long way v2.wmf/binary/mapobjects
  data/maps/Long, long way v2.wmf/binary/terrain
  data/maps/Long, long way v2.wmf/elemental
  data/maps/Long, long way v2.wmf/minimap.png
  data/maps/Long, long way v2.wmf/objective
  data/maps/Long, long way v2.wmf/player_names
  data/maps/Long, long way v2.wmf/player_position
  data/maps/Long, long way v2.wmf/port_spaces
  data/maps/Long, long way v2.wmf/version
  data/maps/Sun_of_Fire.wmf/binary/mapobjects
  data/maps/Sun_of_Fire.wmf/binary/resource
  data/maps/Sun_of_Fire.wmf/binary/terrain
  data/maps/Sun_of_Fire.wmf/elemental
  data/maps/Sun_of_Fire.wmf/minimap.png
  data/maps/Sun_of_Fire.wmf/objective
  data/maps/Sun_of_Fire.wmf/player_names
  data/maps/Sun_of_Fire.wmf/player_position
  data/maps/Sun_of_Fire.wmf/port_spaces
  data/maps/Sun_of_Fire.wmf/version
  src/logic/map.cc
  src/logic/map.h
Labels: bug, maps, world

#4145 Extend keyboard support
  data/templates/default/init.lua
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/ui_basic/button.cc
  src/ui_basic/button.h
  src/ui_basic/checkbox.cc
  src/ui_basic/checkbox.h
  src/ui_basic/dropdown.cc
  src/ui_basic/listselect.cc
  src/ui_basic/multilinetextarea.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/slider.cc
  src/ui_basic/slider.h
  src/ui_basic/spinbox.cc
  src/ui_basic/spinbox.h
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
  src/ui_basic/window.h
  src/wui/interactive_base.cc
  src/wui/sound_options.cc
Labels: accessibility, enhancement, ui

#4158 Option to let players choose their own starting position
  src/ai/defaultai.cc
  src/editor/tools/set_starting_pos_tool.cc
  src/editor/tools/set_starting_pos_tool.h
  src/game_io/game_player_info_packet.cc
  src/logic/game.cc
  src/logic/game_settings.h
  src/logic/map.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/logic/single_player_game_settings_provider.cc
  src/logic/single_player_game_settings_provider.h
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/network_protocol.h
  src/scripting/lua_map.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/wui/interactive_player.cc
Labels: enhancement, tribes

#4155 Trigger economy rebalancing on warehouse policy change
  src/logic/map_objects/tribes/warehouse.cc
Labels: bug, economy, tribes

#4176 Disallow ferries to swim on lava
  data/maps/Long, long way v2.wmf/binary/resource
  data/maps/Long, long way v2.wmf/binary/terrain
  data/maps/Long, long way v2.wmf/elemental
  data/maps/Long, long way v2.wmf/minimap.png
  data/maps/Long, long way v2.wmf/objective
  data/maps/Long, long way v2.wmf/player_names
  data/maps/Long, long way v2.wmf/player_position
  data/maps/Long, long way v2.wmf/port_spaces
  data/maps/Long, long way v2.wmf/version
  src/logic/map_objects/checkstep.cc
Labels: bug, ferry&ww, maps, pathfinding
