Repository widelands/widelands, pull requests merged in 2020-06, with the labels that each got.

#3857 Refactor Ship Scheduling
  src/economy/CMakeLists.txt
  src/economy/portdock.cc
  src/economy/portdock.h
  src/economy/ship_fleet.cc
  src/economy/ship_fleet.h
  src/economy/shipping_schedule.cc
  src/economy/shipping_schedule.h
  src/economy/shippingitem.h
  src/economy/ware_instance.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/warehouse.cc
  src/scripting/lua_map.cc
  src/wui/seafaring_statistics_menu.cc
  src/wui/shipwindow.cc
  test/maps/expedition.wmf/scripting/test_cancel_started_expedition_on_ship_two_ships.lua
  test/maps/expedition.wmf/scripting/test_cancel_when_port_space_was_reached_two_ships.lua
  test/maps/expedition.wmf/scripting/test_ship_movement_controls.lua
  test/maps/ship_transportation.wmf/scripting/test_create_request_while_worker_with_ware_is_in_transit.lua
  test/maps/ship_transportation.wmf/scripting/test_rip_first_port_with_ware_in_portdock.lua
  test/maps/ship_transportation.wmf/scripting/test_rip_ship_before_picking_up_transporting_ware.lua
Labels: seafaring, urgent

#3936 Fix textdomain for »New Objective(s)« headers
  data/scripting/messages.lua
Labels: bug, campaigns & scenarios, internationalization

#3850 Fix editor resize tool
  src/editor/tools/action_args.h
  src/editor/tools/resize_tool.cc
  src/editor/tools/set_resources_tool.cc
  src/logic/editor_game_base.cc
  src/logic/map.cc
  src/logic/map.h
  src/logic/player.cc
  src/logic/player.h
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_players_view_packet.cc
Labels: editor, urgent

#3941 Fix ship destination mismatch after order cancelling
  src/economy/shipping_schedule.cc
Labels: bug, seafaring

#3944 use detect_revision.py on appveyor
  appveyor.yml
Labels: building & packaging, windows

#3948 Load replay savegames in multiplayer screens
  src/wui/savegameloader.cc
Labels: bug, replay, saveloading & compatibility, ui

#3951 Appveyor
  appveyor.yml
Labels: building & packaging

#3949 Fix a WException when shift-clicking constructionsite WareQueues
  src/wui/inputqueuedisplay.cc
Labels: bug, crashes or hangs, tribes
