Repository widelands/widelands, pull requests merged in 2020-09, with the labels that each got.

#4147 Fail gracefully on Lua PANIC
  src/map_io/map_scripting_packet.cc
Labels: crashes or hangs

#4197 Focus tweaks
  data/templates/default/init.lua
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/ui_basic/button.cc
  src/ui_basic/checkbox.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/table.cc
  src/ui_basic/table.h
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
  src/wui/game_message_menu.cc
  src/wui/game_summary.cc
Labels: accessibility, bug, ui

#4211 Rephrase some map hints
  data/maps/Dolomites_v3.wmf/elemental
  data/maps/Twinkling_Waves.wmf/elemental
Labels: maps

#4213 Fix BaseListselect key handling when no entry selected
  src/ui_basic/listselect.cc
Labels: accessibility, crashes or hangs

#4209 Target workers to immovables
  data/images/wui/fieldaction/menu_mark_removal.png
  data/images/wui/fieldaction/menu_tab_target.png
  data/images/wui/fieldaction/menu_unmark_removal.png
  data/images/wui/overlays/targeted.png
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable.h
  src/logic/map_objects/immovable_program.cc
  src/logic/map_objects/immovable_program.h
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/worker.cc
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/wui/fieldaction.cc
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
  src/wui/interactive_spectator.cc
Labels: balancing & gameplay, enhancement, tribes

#4242 Optimize ObjectManager::object_still_available()
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/map_object.h
Labels: memory & performance

#4231 Frisian toolbar icons
  data/tribes/initialization/atlanteans/images/toolbar_center.png
  data/tribes/initialization/atlanteans/images/toolbar_left.png
  data/tribes/initialization/atlanteans/images/toolbar_left_corner.png
  data/tribes/initialization/atlanteans/images/toolbar_right.png
  data/tribes/initialization/atlanteans/images/toolbar_right_corner.png
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/frisians/images/toolbar_center.png
  data/tribes/initialization/frisians/images/toolbar_left.png
  data/tribes/initialization/frisians/images/toolbar_main.png
  data/tribes/initialization/frisians/images/toolbar_right.png
  data/tribes/initialization/frisians/units.lua
Labels: enhancement, frisians, graphics

#4283 Fix vision glitches
  src/logic/player.cc
  src/logic/widelands_geometry.h
  src/map_io/map_players_view_packet.cc
  src/wui/game_message_menu.cc
Labels: bug, saveloading & compatibility, tribes

#4293 Fix poor hamlet warning message localization
  data/tribes/initialization/atlanteans/starting_conditions/poor_hamlet.lua
  data/tribes/initialization/barbarians/starting_conditions/poor_hamlet.lua
  data/tribes/initialization/empire/starting_conditions/poor_hamlet.lua
  data/tribes/initialization/frisians/starting_conditions/poor_hamlet.lua
Labels: bug, internationalization, lua, tribes

#3847 Overhaul of SP and MP launch game screen
  src/logic/single_player_game_settings_provider.cc
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/notifications/note_ids.h
  src/ui_basic/dropdown.cc
  src/ui_basic/panel.cc
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_mpg.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/launch_spg.h
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/mapdetailsbox.h
  src/ui_fsmenu/mapselect.h
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/multiplayersetupgroup.h
  src/ui_fsmenu/singleplayerdropdown.cc
  src/ui_fsmenu/singleplayerdropdown.h
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
  src/wui/CMakeLists.txt
  src/wui/game_chat_panel.cc
  src/wui/game_chat_panel.h
  src/wui/mapdetails.cc
  src/wui/suggested_teams_box.cc
Labels: cleanup & refactoring, ui
