Repository widelands/widelands, pull requests merged in 2020-07, with the labels that each got.

#3911 Fix 1% too-high soldier evade
  src/logic/map_objects/tribes/battle.cc
Labels: military

#3939 Set correct WorkerQueue Economy after economy split
  src/economy/workers_queue.cc
Labels: bug, economy

#3953 Ignore multiple enhance commands
  src/logic/playercommand.cc
  src/wui/actionconfirm.cc
  src/wui/buildingwindow.cc
Labels: bug, crashes or hangs, tribes

#3916 Fix snprintf error for Windows build
  appveyor.yml
  src/base/i18n.h
  utils/appveyor/libintl.patch
Labels: cleanup & refactoring, windows

#3976 Fixes two desyncs in New World & Discovery
  data/scripting/starting_conditions.lua
  src/scripting/lua_map.cc
Labels: desync

#3718 Clever Critters
  data/world/critters/badger/init.lua
  data/world/critters/brownbear/init.lua
  data/world/critters/bunny/init.lua
  data/world/critters/chamois/init.lua
  data/world/critters/deer/init.lua
  data/world/critters/duck/init.lua
  data/world/critters/fox/init.lua
  data/world/critters/lynx/init.lua
  data/world/critters/marten/init.lua
  data/world/critters/moose/init.lua
  data/world/critters/reindeer/init.lua
  data/world/critters/sheep/init.lua
  data/world/critters/stag/init.lua
  data/world/critters/wildboar/init.lua
  data/world/critters/wisent/init.lua
  data/world/critters/wolf/init.lua
  src/logic/map.cc
  src/logic/map.h
  src/logic/map_objects/bob.cc
  src/logic/map_objects/bob.h
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable.h
  src/logic/map_objects/immovable_program.cc
  src/logic/map_objects/world/critter.cc
  src/logic/map_objects/world/critter.h
  src/logic/map_objects/world/world.cc
  src/logic/map_objects/world/world.h
Labels: enhancement, world

#3977 Add optional braces to economy code
  src/economy/cmd_call_economy_balance.cc
  src/economy/economy.cc
  src/economy/expedition_bootstrap.cc
  src/economy/flag.cc
  src/economy/idleworkersupply.cc
  src/economy/input_queue.cc
  src/economy/portdock.cc
  src/economy/request.cc
  src/economy/road.cc
  src/economy/roadbase.cc
  src/economy/route.cc
  src/economy/routeastar.cc
  src/economy/router.cc
  src/economy/ship_fleet.cc
  src/economy/shippingitem.cc
  src/economy/supply_list.cc
  src/economy/test/test_routing.cc
  src/economy/transfer.cc
  src/economy/ware_instance.cc
  src/economy/wares_queue.cc
  src/economy/workers_queue.cc
Labels: cleanup & refactoring

#3988 Immediately-upgraded constructionsites should not burn
  src/logic/map_objects/tribes/constructionsite.cc
Labels: bug, tribes

#3987 Don't add a dismantle button when no wares will be returned
  data/campaigns/emp04.wmf/scripting/texts.lua
  src/wui/buildingwindow.cc
Labels: bug, tribes, ui

#4008 Update Crossing The Horizon hint
  data/maps/Crossing_the_Horizon_v2.wmf/elemental
Labels: maps

#4001 Switch to new version scheme
  NEXT_STABLE_VERSION
  utils/detect_revision.py
  utils/win32/widelands.rc.cmake
Labels: building & packaging

#4011 Additional Expedition Items dropdown sorting order
  src/wui/portdockwaresdisplay.cc
Labels: ui

#4010 Continue button in main menu
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/base.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/wlapplication.cc
  src/wlapplication.h
Labels: enhancement, saveloading & compatibility, ui

#3980 Rip out savegame compatibility code
  src/economy/cmd_call_economy_balance.cc
  src/economy/economy.h
  src/economy/economy_data_packet.cc
  src/economy/economy_data_packet.h
  src/economy/expedition_bootstrap.cc
  src/economy/input_queue.cc
  src/economy/portdock.cc
  src/economy/ship_fleet.cc
  src/economy/ship_fleet.h
  src/economy/shipping_schedule.cc
  src/economy/shipping_schedule.h
  src/economy/shippingitem.cc
  src/economy/ware_instance.cc
  src/game_io/game_class_packet.cc
  src/game_io/game_player_economies_packet.cc
  src/logic/map_objects/tribes/building_settings.cc
  src/logic/map_objects/tribes/carrier.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/worker.cc
  src/logic/player.cc
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_flag_packet.cc
  src/map_io/map_object_loader.cc
  src/map_io/map_object_loader.h
  src/map_io/map_object_packet.cc
  src/map_io/map_players_view_packet.cc
  src/map_io/map_roaddata_packet.cc
  src/map_io/tribes_legacy_lookup_table.cc
  test/maps/lua_testsuite.wmf/binary/mapobjects
Labels: cleanup & refactoring, saveloading & compatibility

#4017 Button to toggle buildings visibility
  data/tribes/scripting/help/controls.lua
  src/graphic/animation/animation.cc
  src/graphic/animation/animation.h
  src/graphic/animation/nonpacked_animation.cc
  src/graphic/animation/nonpacked_animation.h
  src/graphic/animation/spritesheet_animation.cc
  src/graphic/animation/spritesheet_animation.h
  src/graphic/rendertarget.cc
  src/graphic/rendertarget.h
  src/logic/map_objects/info_to_draw.h
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/constructionsite.h
  src/logic/map_objects/tribes/dismantlesite.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
Labels: enhancement, tribes, ui

#4027 Fix a crash after cancelling an expedition when no port is left
  src/logic/map_objects/tribes/ship.cc
Labels: bug, seafaring

#4029 Disallow enhancing conquered enemy militarysites
  src/wui/buildingwindow.cc
Labels: bug, tribes, ui

#4031 Fix editor player menu glitches
  src/editor/ui_menus/player_menu.cc
Labels: bug, editor, ui

#4032 Fix coordinate maths error in road graphics
  src/graphic/gl/road_program.cc
Labels: bug, graphics

#4035 Fix editor MapOptions tabbing order
  src/editor/ui_menus/main_menu_map_options.cc
  src/ui_basic/panel.cc
Labels: bug, editor, ui
