Repository widelands/widelands, pull requests merged in 2020-05, with the labels that each got.

#3891 Rework main_worker_ saveloading
  src/logic/map_objects/tribes/productionsite.cc
  src/map_io/map_buildingdata_packet.cc
Labels: saveloading & compatibility, tribes

#3892 Fix duplicate campaign description
  src/ui_fsmenu/campaigndetails.cc
Labels: campaigns & scenarios, ui

#3884 Expedition fixes
  src/economy/expedition_bootstrap.cc
  src/economy/input_queue.cc
  src/economy/portdock.cc
  src/economy/portdock.h
  src/logic/map_objects/tribes/warehouse.cc
Labels: bug, economy, seafaring, ui, urgent

#3901 Marked tut03 objective headings for translation
  data/campaigns/tutorial03_seafaring.wmf/scripting/texts.lua
Labels: internationalization, urgent

#3903 updated innosetup file to reflect new Icu filenames
  utils/win32/innosetup/Widelands.iss
Labels: urgent

#3906 new WAI files - result of about 120 rounds of training
  data/ai/ai_input_1.wai
  data/ai/ai_input_2.wai
  data/ai/ai_input_3.wai
  data/ai/ai_input_4.wai
Labels: ai

#3908 Fix gcc10 compiler errors
  src/economy/router.h
  src/logic/map_objects/map_object_program.cc
  src/logic/widelands_geometry.h
  src/ui_basic/box.cc
  src/wlapplication.h
  src/wui/debugconsole.h
  utils/win32/innosetup/Widelands.iss
Labels: building & packaging, ftbfs

#3910 preventing zero division in Check_building_necesity
  src/ai/defaultai.cc
Labels: ai

#3871 Fixes issue #3869 : No training in camp for Empire
  src/logic/map_objects/tribes/trainingsite.cc
  src/logic/map_objects/tribes/trainingsite.h
  src/map_io/map_buildingdata_packet.cc
Labels: balancing & gameplay, military

#3915 Fix table column index mismatch regression
  src/ui_basic/table.cc
Labels: crashes or hangs, ui

#3917 add missing dll to appveyor builds
  appveyor.yml
  utils/win32/innosetup/Widelands.iss
Labels: windows

#3918 Make emp03 title translatable
  data/campaigns/emp03.wmf/elemental
Labels: internationalization

#3922 Fix recycling center hotspot
  data/tribes/buildings/productionsites/frisians/recycling_center/init.lua
Labels: graphics

#3924 Add missing include in building_help.lua
  data/tribes/scripting/help/building_help.lua
Labels: bug, help, lua
