Repository widelands/widelands, pull requests merged in 2020-04, with the labels that each got.

#3804 Fix rookie creation for hero demands
  src/economy/economy.cc
  src/economy/economy.h
Labels: economy, military

#3825 Replace deprecated reveal_scenario with mark_scenario_as_solved in frisian campaign
  data/campaigns/fri01.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/mission_thread.lua
Labels: campaigns & scenarios

#3828 Scenarios should include all scripts from the init.lua
  data/campaigns/atl01.wmf/scripting/init.lua
  data/campaigns/atl01.wmf/scripting/texts.lua
  data/campaigns/atl01.wmf/scripting/water_rising.lua
  data/campaigns/bar01.wmf/scripting/init.lua
  data/campaigns/bar01.wmf/scripting/mission_thread.lua
  data/campaigns/bar01.wmf/scripting/texts.lua
  data/campaigns/bar02.wmf/scripting/init.lua
  data/campaigns/bar02.wmf/scripting/mission_thread.lua
  data/campaigns/bar02.wmf/scripting/texts.lua
  data/campaigns/emp01.wmf/scripting/init.lua
  data/campaigns/emp01.wmf/scripting/mission_thread.lua
  data/campaigns/emp01.wmf/scripting/texts.lua
  data/campaigns/emp02.wmf/scripting/init.lua
  data/campaigns/emp02.wmf/scripting/mission_thread.lua
  data/campaigns/emp02.wmf/scripting/texts.lua
  data/campaigns/emp03.wmf/scripting/init.lua
  data/campaigns/emp03.wmf/scripting/mission_thread.lua
  data/campaigns/emp03.wmf/scripting/texts.lua
  data/campaigns/emp04.wmf/scripting/init.lua
  data/campaigns/emp04.wmf/scripting/mission_thread.lua
  data/campaigns/emp04.wmf/scripting/texts.lua
  data/campaigns/fri01.wmf/scripting/init.lua
  data/campaigns/fri01.wmf/scripting/mission_thread.lua
  data/campaigns/fri01.wmf/scripting/texts.lua
  data/campaigns/fri02.wmf/scripting/init.lua
  data/campaigns/fri02.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/texts.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/init.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/campaigns/tutorial02_warfare.wmf/scripting/init.lua
  data/campaigns/tutorial02_warfare.wmf/scripting/texts.lua
  data/campaigns/tutorial03_seafaring.wmf/scripting/init.lua
  data/campaigns/tutorial03_seafaring.wmf/scripting/texts.lua
  data/campaigns/tutorial04_economy.wmf/scripting/init.lua
  data/campaigns/tutorial04_economy.wmf/scripting/texts.lua
Labels: bug, campaigns & scenarios, cleanup & refactoring

#3824 Fix a desync
  data/world/immovables/trees/alder/init.lua
  data/world/immovables/trees/aspen/init.lua
  data/world/immovables/trees/beech/init.lua
  data/world/immovables/trees/birch/init.lua
  data/world/immovables/trees/cirrus/init.lua
  data/world/immovables/trees/larch/init.lua
  data/world/immovables/trees/liana/init.lua
  data/world/immovables/trees/maple/init.lua
  data/world/immovables/trees/mushroom_dark/init.lua
  data/world/immovables/trees/mushroom_green/init.lua
  data/world/immovables/trees/mushroom_red/init.lua
  data/world/immovables/trees/oak/init.lua
  data/world/immovables/trees/palm_borassus/init.lua
  data/world/immovables/trees/palm_coconut/init.lua
  data/world/immovables/trees/palm_date/init.lua
  data/world/immovables/trees/palm_oil/init.lua
  data/world/immovables/trees/palm_roystonea/init.lua
  data/world/immovables/trees/rowan/init.lua
  data/world/immovables/trees/spruce/init.lua
  data/world/immovables/trees/twine/init.lua
  data/world/immovables/trees/umbrella_green/init.lua
  data/world/immovables/trees/umbrella_red/init.lua
  src/logic/map_objects/immovable_program.cc
Labels: desync, world

#3829 Immovable program documentation
  data/tribes/immovables/ashes/init.lua
  data/world/immovables/bush1/init.lua
  doc/sphinx/source/immovable_program.rst
  doc/sphinx/source/map_object_programs.rst
  src/logic/map_objects/tribes/worker_program.cc
  src/scripting/lua_ui.cc
Labels: documentation

#3848 Fix travis MacOS builds
  .travis.sh
  .travis.yml
Labels: building & packaging, macos, testing

#3818 Tutorial 01: Click-by-click demonstration of worker area
  data/campaigns/tutorial01_basic_control.wmf/scripting/mission_thread.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
Labels: tutorials, urgent

#3853 Fix wrong textdomain for a string
  src/ui_fsmenu/campaigns.cc
Labels: bug, internationalization, urgent

#3854 Fix text alignment problem
  src/graphic/text/sdl_ttf_font.cc
Labels: ui, urgent

#3757 Handle missing locale dir on Windows
  src/ui_fsmenu/options.cc
  src/wlapplication.cc
Labels: urgent, windows

#3845 Removing signal from warelist.
  regression_test.py
  src/logic/map_objects/tribes/warelist.cc
  src/logic/map_objects/tribes/warelist.h
  src/wlapplication.cc
Labels: cleanup & refactoring, testing, urgent

#3855 Hide economy setting when default target quantity is 0
  data/tribes/wares/armor/init.lua
  data/tribes/wares/blackroot_flour/init.lua
  src/logic/map_objects/tribes/ware_descr.cc
Labels: atlanteans, economy, enhancement

#3844 Allow preserving wares left in buildings when dismantling or enhancing
  src/ai/defaultai.cc
  src/ai/defaultai_warfare.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/constructionsite.h
  src/logic/map_objects/tribes/dismantlesite.cc
  src/logic/map_objects/tribes/dismantlesite.h
  src/logic/map_objects/tribes/partially_finished_building.cc
  src/logic/map_objects/tribes/partially_finished_building.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/map_io/map_buildingdata_packet.cc
  src/wui/actionconfirm.cc
  src/wui/buildingwindow.cc
  src/wui/constructionsitewindow.cc
  src/wui/dismantlesitewindow.cc
Labels: enhancement, tribes, ui, urgent

#3858 Faster game saving with endless_game_fogless win condition
  data/scripting/win_conditions/endless_game_fogless.lua
Labels: memory & performance, saveloading & compatibility, wincondition

#3837 Allow setting economy targets to ∞
  data/images/wui/menus/infinity.png
  src/economy/economy.h
  src/wui/economy_options_window.cc
  src/wui/economy_options_window.h
Labels: economy, enhancement, ui, urgent

#3842 Restrict waterway length limit
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_map_options.h
Labels: editor, ferry&ww, ui, urgent

#3859 Removing new networking accept code
  src/network/bufferedconnection.cc
  src/network/bufferedconnection.h
  src/network/nethost.cc
  src/network/nethost.h
Labels: multiplayer & networking, urgent, windows

#3861 Fix travis failure on gcc-9.1_debug
  src/logic/map_objects/map_object.cc
Labels: building & packaging, testing, urgent

#3872 Improve SDL2 detection on modern systems
  CMakeLists.txt
  cmake/WlFunctions.cmake
Labels: building & packaging

#3870 Fix economy mismatch in Request loading
  src/economy/request.cc
  src/map_io/map_buildingdata_packet.cc
Labels: economy, saveloading & compatibility, urgent
