Repository widelands/widelands, pull requests merged in 2021-03, with the labels that each got.

#4720 Fix hotkeys in tutorials
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/campaigns/tutorial02_warfare.wmf/scripting/texts.lua
  data/campaigns/tutorial04_economy.wmf/scripting/texts.lua
  data/txts/tips/general_game.lua
Labels: accessibility, bug, tutorials

#4716 MP Fixes
  src/logic/game_settings.cc
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
Labels: bug, multiplayer & networking

#4723 Fix Transifex String Issues
  data/campaigns/fri02.wmf/scripting/texts.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/empire/units.lua
  data/world/immovables/trees/fallentree/init.lua
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons_packager.cc
  src/wui/interactive_base.cc
  src/wui/savegameloader.cc
  utils/buildcat.py
Labels: bug, internationalization

#4719 Toggle preserve wares default behaviour with Shift
  src/wui/buildingwindow.cc
Labels: ui

#4728 More string/i18n fixes
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons_packager.cc
  utils/merge_and_push_translations.sh
Labels: internationalization

#4725 Catch exception on invalid locale
  src/ui_fsmenu/addons.cc
Labels: bug, crashes or hangs, urgent

#4738 Fri03 Fixes
  data/campaigns/fri03.wmf/scripting/mission_thread.lua
  data/campaigns/fri03.wmf/scripting/texts.lua
Labels: bug, campaigns & scenarios, frisians

#4724 Relayout stock menu on tab change
  src/wui/stock_menu.cc
  src/wui/stock_menu.h
Labels: bug, statistics, ui

#4737 Fix crash when using debug console in editor
  src/wui/interactive_base.cc
Labels: crashes or hangs, editor, lua

#4742 Fix scrolling in gamedetails and mapdetails
  src/wui/gamedetails.cc
  src/wui/gamedetails.h
  src/wui/mapdetails.cc
Labels: ui

#4743 Fix textdomains for add-on maps
  doc/sphinx/source/add-ons.rst
  src/base/i18n.h
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/scenario_select.cc
  src/wui/CMakeLists.txt
  src/wui/mapdata.cc
  src/wui/savegamedata.cc
Labels: addon, bug, internationalization

#4618 Ai production support
  data/tribes/buildings/productionsites/amazons/cocoa_farm/init.lua
  data/tribes/buildings/productionsites/amazons/hunter_gatherers_hut/init.lua
  data/tribes/buildings/productionsites/amazons/jungle_preservers_hut/init.lua
  data/tribes/buildings/productionsites/amazons/liana_cutters_hut/init.lua
  data/tribes/buildings/productionsites/amazons/rare_tree_cutters_hut/init.lua
  data/tribes/buildings/productionsites/amazons/rare_tree_plantation/init.lua
  data/tribes/buildings/productionsites/amazons/stonecutters_hut/init.lua
  data/tribes/buildings/productionsites/amazons/water_gatherers_hut/init.lua
  data/tribes/buildings/productionsites/amazons/wilderness_keepers_tent/init.lua
  data/tribes/buildings/productionsites/amazons/woodcutters_hut/init.lua
  data/tribes/buildings/productionsites/atlanteans/armorsmithy/init.lua
  data/tribes/buildings/productionsites/atlanteans/fishbreeders_house/init.lua
  data/tribes/buildings/productionsites/atlanteans/fishers_house/init.lua
  data/tribes/buildings/productionsites/atlanteans/foresters_house/init.lua
  data/tribes/buildings/productionsites/atlanteans/hunters_house/init.lua
  data/tribes/buildings/productionsites/atlanteans/quarry/init.lua
  data/tribes/buildings/productionsites/atlanteans/well/init.lua
  data/tribes/buildings/productionsites/atlanteans/woodcutters_house/init.lua
  data/tribes/buildings/productionsites/barbarians/fishers_hut/init.lua
  data/tribes/buildings/productionsites/barbarians/gamekeepers_hut/init.lua
  data/tribes/buildings/productionsites/barbarians/hunters_hut/init.lua
  data/tribes/buildings/productionsites/barbarians/lumberjacks_hut/init.lua
  data/tribes/buildings/productionsites/barbarians/quarry/init.lua
  data/tribes/buildings/productionsites/barbarians/rangers_hut/init.lua
  data/tribes/buildings/productionsites/barbarians/well/init.lua
  data/tribes/buildings/productionsites/empire/fishers_house/init.lua
  data/tribes/buildings/productionsites/empire/foresters_house/init.lua
  data/tribes/buildings/productionsites/empire/hunters_house/init.lua
  data/tribes/buildings/productionsites/empire/lumberjacks_house/init.lua
  data/tribes/buildings/productionsites/empire/quarry/init.lua
  data/tribes/buildings/productionsites/empire/well/init.lua
  data/tribes/buildings/productionsites/frisians/aqua_farm/init.lua
  data/tribes/buildings/productionsites/frisians/beekeepers_house/init.lua
  data/tribes/buildings/productionsites/frisians/berry_farm/init.lua
  data/tribes/buildings/productionsites/frisians/clay_pit/init.lua
  data/tribes/buildings/productionsites/frisians/collectors_house/init.lua
  data/tribes/buildings/productionsites/frisians/farm/init.lua
  data/tribes/buildings/productionsites/frisians/fishers_house/init.lua
  data/tribes/buildings/productionsites/frisians/foresters_house/init.lua
  data/tribes/buildings/productionsites/frisians/hunters_house/init.lua
  data/tribes/buildings/productionsites/frisians/quarry/init.lua
  data/tribes/buildings/productionsites/frisians/well/init.lua
  data/tribes/buildings/productionsites/frisians/woodcutters_house/init.lua
  data/tribes/buildings/trainingsites/amazons/training_glade/init.lua
  data/tribes/buildings/trainingsites/amazons/warriors_gathering/init.lua
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/ai_hints.cc
  src/ai/ai_hints.h
  src/ai/defaultai.cc
  src/ai/defaultai.h
  src/ai/defaultai_warfare.cc
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/worker_descr.h
  src/logic/map_objects/tribes/worker_program.cc
  src/logic/map_objects/tribes/worker_program.h
  src/scripting/lua_map.cc
Labels: ai, urgent

#4751 Fix save game menu buttons
  src/wui/gamedetails.cc
Labels: ui

#4753 fix AI handling of amazon_water_gatherer
  src/ai/defaultai.cc
Labels: ai, amazons

#4736 Disable Autofix Dependencies v1.0
  src/logic/mutable_addon.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/ui_fsmenu/addons_packager.cc
Labels: addon, urgent

#4722 Request no bug report for expected disconnects
  src/network/gameclient.cc
  src/wlapplication.cc
  src/wlapplication.h
Labels: bug, multiplayer & networking, urgent

#4762 Fix npgettext textdomains for add-ons
  src/logic/addons.cc
  src/scripting/lua_globals.cc
  src/ui_fsmenu/addons.cc
Labels: addon, bug, internationalization, urgent

#4764 Fix crash on invalid screenshot
  src/ui_fsmenu/addons.cc
Labels: addon, bug, crashes or hangs

#4767 Fix duplicate description registries by add-ons
  src/logic/map_objects/CMakeLists.txt
  src/logic/map_objects/description_manager.cc
Labels: addon, crashes or hangs, tribes, urgent, world

#4755 Clean up superfluous log output
  src/ai/ai_help_structs.cc
  src/ai/defaultai.cc
  src/ai/defaultai_seafaring.cc
  src/ai/defaultai_warfare.cc
  src/base/log.h
  src/base/scoped_timer.cc
  src/base/scoped_timer.h
  src/economy/economy.cc
  src/economy/shipping_schedule.cc
  src/economy/transfer.cc
  src/editor/editorinteractive.cc
  src/game_io/game_loader.cc
  src/game_io/game_saver.cc
  src/graphic/animation/nonpacked_animation.cc
  src/graphic/gl/initialize.cc
  src/graphic/graphic.cc
  src/graphic/style_manager.cc
  src/logic/ai_dna_handler.cc
  src/logic/cmd_luascript.cc
  src/logic/editor_game_base.cc
  src/logic/game.cc
  src/logic/map.cc
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/tribes/trainingsite.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/player.cc
  src/logic/playercommand.cc
  src/logic/replay.cc
  src/logic/save_handler.cc
  src/map_io/map_saver.cc
  src/map_io/s2map.cc
  src/map_io/widelands_map_loader.cc
  src/network/bufferedconnection.cc
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/internet_gaming.cc
  src/network/netclient.cc
  src/network/nethost.cc
  src/network/nethostproxy.cc
  src/network/network.cc
  src/network/network_lan_promotion.cc
  src/sound/sound_handler.cc
  src/wlapplication.cc
Labels: cleanup & refactoring

#4765 No custom starting positions for Discovery
  data/tribes/initialization/amazons/starting_conditions/discovery.lua
  data/tribes/initialization/amazons/starting_conditions/new_world.lua
  data/tribes/initialization/atlanteans/starting_conditions/discovery.lua
  data/tribes/initialization/atlanteans/starting_conditions/new_world.lua
  data/tribes/initialization/barbarians/starting_conditions/discovery.lua
  data/tribes/initialization/barbarians/starting_conditions/new_world.lua
  data/tribes/initialization/empire/starting_conditions/discovery.lua
  data/tribes/initialization/empire/starting_conditions/new_world.lua
  data/tribes/initialization/frisians/starting_conditions/discovery.lua
  data/tribes/initialization/frisians/starting_conditions/new_world.lua
  src/logic/game.cc
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_basic_info.h
  src/logic/player.h
  src/network/gameclient.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/singleplayerdropdown.cc
  src/ui_fsmenu/singleplayerdropdown.h
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
Labels: bug, tribes, ui

#4769 Make editor toolsize hotkeys configurable
  data/scripting/editor/editor_controls.lua
  data/txts/help/common_helptexts.lua
  data/txts/tips/editor.lua
  src/editor/editorinteractive.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
Labels: accessibility, editor

#4758 Add-Ons: More verbose doc & get rid of required restarts
  data/templates/new_game_template
  doc/sphinx/source/add-ons.rst
  src/graphic/graphic.cc
  src/graphic/graphic.h
  src/graphic/image_cache.cc
  src/graphic/image_cache.h
  src/logic/addons.cc
  src/logic/addons.h
  src/scripting/lua_map.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
Labels: addon, bug, documentation

#4766 Fix replays and savegames with add-on tribes
  src/editor/ui_menus/player_menu.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_basic_info.h
  src/logic/replay.cc
  src/logic/single_player_game_settings_provider.cc
  src/network/gameclient.cc
  src/scripting/lua_map.cc
  src/ui_fsmenu/addons_packager_box.cc
  src/ui_fsmenu/campaigns.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/singleplayerdropdown.cc
  src/website/map_object_info.cc
  src/wui/game_tips.cc
  src/wui/game_tips.h
Labels: addon, replay, saveloading & compatibility, tribes, urgent

#4780 Fix MP dropdown conditions
  src/logic/game_settings.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
Labels: multiplayer & networking, ui

#4770 Fix TX string issues
  data/campaigns/emp04.wmf/scripting/texts.lua
  data/campaigns/emp04.wmf/scripting/tribes/init.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/maps/Dolomites.wmf/elemental
  data/maps/No_metal_challenge.wmf/elemental
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  data/txts/developers.json
  data/txts/tips/amazons.lua
  data/txts/tips/multiplayer.lua
  src/logic/game_data_error.cc
  src/logic/map_objects/tribes/worker.cc
  src/network/gameclient.cc
  src/network/internet_gaming.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_mpg.cc
  src/wlapplication_messages.cc
  src/wlapplication_options.cc
  src/wui/fieldaction.cc
  src/wui/game_message_menu.cc
  src/wui/waresdisplay.cc
Labels: internationalization

#4782 Prevent large dropdowns dropping out of the screen
  src/ui_basic/dropdown.cc
Labels: bug, ui

#4777 Fix desyncs with tribe add-ons
  src/game_io/game_loader.cc
  src/game_io/game_loader.h
  src/logic/CMakeLists.txt
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/replay.cc
Labels: addon, bug, desync, tribes, urgent

#4789 Fix linking with opus
  cmake/WlFunctions.cmake
Labels: building & packaging, windows

#4793 Fix amazons fortified village
  data/tribes/initialization/amazons/starting_conditions/fortified_village.lua
Labels: amazons, bug
