Repository widelands/widelands, pull requests merged in 2021-01, with the labels that each got.

#4549 Allow configuring playercolor
  src/editor/editorinteractive.cc
  src/game_io/game_player_info_packet.cc
  src/logic/CMakeLists.txt
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game_settings.cc
  src/logic/game_settings.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playersmanager.cc
  src/logic/playersmanager.h
  src/logic/single_player_game_settings_provider.cc
  src/logic/single_player_game_settings_provider.h
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/network_player_settings_backend.cc
  src/network/network_player_settings_backend.h
  src/network/network_protocol.h
  src/ui_basic/CMakeLists.txt
  src/ui_basic/color_chooser.cc
  src/ui_basic/color_chooser.h
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
  src/wui/game_summary.cc
  src/wui/general_statistics_menu.cc
  src/wui/interactive_player.cc
Labels: enhancement, graphics, ui

#4567 Fix LAN mapname localization
  src/ui_fsmenu/netsetup_lan.cc
Labels: bug, internationalization

#4577 Fix double-deletion of message previews
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
Labels: bug, crashes or hangs

#4572 Main Menu Redesign, Part 5
  src/logic/editor_game_base.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/progresswindow.cc
  src/ui_basic/progresswindow.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_mpg.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/launch_spg.h
  src/ui_fsmenu/loadgame.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/mapselect.h
  src/ui_fsmenu/menu.cc
  src/ui_fsmenu/menu.h
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/random_game.h
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
  src/wlapplication.cc
Labels: bug, cleanup & refactoring, enhancement, ui

#4581 Increase player info packet version
  src/game_io/game_player_info_packet.cc
Labels: bug, saveloading & compatibility, urgent

#4568 Add missing postload call
  src/logic/game.cc
Labels: bug, tribes, urgent

#4587 Fix heap-use-after-free in LaunchMPG
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_fsmenu/launch_mpg.cc
Labels: bug, crashes or hangs, ui, urgent

#4582 Color chooser enhancements
  data/images/ui_basic/square.png
  data/images/ui_basic/square_pc.png
  src/ui_basic/color_chooser.cc
  src/ui_basic/color_chooser.h
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/singleplayersetupbox.cc
Labels: enhancement, ui, urgent

#4591 Color Chooser: Mouse drag support & Enter key
  src/ui_basic/color_chooser.cc
  src/ui_basic/color_chooser.h
Labels: ui

#4583 adding productivity threshhold to amazon stonecutter_hut
  data/tribes/buildings/militarysites/amazons/warriors_dwelling/init.lua
  data/tribes/buildings/productionsites/amazons/stonecutters_hut/init.lua
  data/tribes/initialization/amazons/units.lua
Labels: amazons, urgent

#4569 Switch UI themes
  doc/sphinx/source/add-ons.rst
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/editor/ui_menus/main_menu_load_map.cc
  src/editor/ui_menus/main_menu_new_map.cc
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_save_map.cc
  src/graphic/graphic.cc
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/logic/addons.h
  src/ui_basic/button.cc
  src/ui_basic/button.h
  src/ui_basic/editbox.cc
  src/ui_basic/editbox.h
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/multilinetextarea.cc
  src/ui_basic/multilinetextarea.h
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/progressbar.cc
  src/ui_basic/progressbar.h
  src/ui_basic/progresswindow.cc
  src/ui_basic/progresswindow.h
  src/ui_basic/scrollbar.cc
  src/ui_basic/scrollbar.h
  src/ui_basic/slider.cc
  src/ui_basic/slider.h
  src/ui_basic/table.cc
  src/ui_basic/table.h
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
  src/ui_basic/textarea.cc
  src/ui_basic/textarea.h
  src/ui_basic/window.cc
  src/ui_basic/window.h
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication.cc
  src/wui/building_statistics_menu.cc
  src/wui/game_tips.cc
  src/wui/info_panel.cc
Labels: enhancement, ui, urgent

#4593 Ensure at least one statistics data point
  src/wui/general_statistics_menu.cc
Labels: bug, crashes or hangs, statistics

#4578 move caret with mouse click in editbox
  src/ui_basic/editbox.cc
  src/ui_basic/editbox.h
Labels: enhancement, ui, urgent

#4592 Disallow random matches if starting positions are too close
  src/editor/ui_menus/main_menu_random_map.cc
Labels: maps, urgent

#4600 Fix statistics plots player colours
  src/wui/general_statistics_menu.cc
Labels: bug, statistics

#4597 Fix Enter/Esc consistency issues
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/ui_fsmenu/about.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/menu.cc
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/training_wheel_options.cc
  src/ui_fsmenu/training_wheel_options.h
Labels: accessibility, bug, crashes or hangs, ui, urgent

#4493 Targeted Scouting
  data/tribes/buildings/productionsites/amazons/scouts_hut/init.lua
  data/tribes/buildings/productionsites/atlanteans/scouts_house/init.lua
  data/tribes/buildings/productionsites/barbarians/scouts_hut/init.lua
  data/tribes/buildings/productionsites/empire/scouts_house/init.lua
  data/tribes/buildings/productionsites/frisians/scouts_house/init.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  data/tribes/workers/amazons/scout/init.lua
  data/tribes/workers/atlanteans/scout/init.lua
  data/tribes/workers/barbarians/scout/init.lua
  data/tribes/workers/empire/scout/init.lua
  data/tribes/workers/frisians/scout/init.lua
  src/economy/CMakeLists.txt
  src/economy/economy.cc
  src/economy/economy.h
  src/economy/flag.cc
  src/economy/flag.h
  src/economy/flag_job.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/map_io/map_flagdata_packet.cc
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
  src/wui/fieldaction.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/productionsitewindow.cc
  src/wui/productionsitewindow.h
  src/wui/seafaring_statistics_menu.cc
Labels: enhancement, tribes, urgent

#4601 Require clang-format version 10
  .github/workflows/format.yaml
Labels: building & packaging

#4594 Themes: Docs & Fail Safe
  doc/sphinx/source/add-ons.rst
  doc/sphinx/source/reference.rst
  doc/sphinx/source/themes.rst
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/ui_basic/progresswindow.cc
  src/ui_fsmenu/main.cc
  src/wui/game_tips.cc
  src/wui/info_panel.cc
Labels: documentation, graphics

#4609 Fix crash in seafaring stats menu
  src/wui/seafaring_statistics_menu.cc
Labels: bug, crashes or hangs, seafaring, statistics

#4599 Update for msvc
  .github/workflows/build.yaml
  CMakeLists.txt
  cmake/WlFunctions.cmake
Labels: building & packaging, windows

#4605 Warn about replay version mismatch
  src/ui_fsmenu/loadgame.cc
Labels: enhancement, replay, ui

#4552 Add-Ons: Screenshots and voting stats
  src/logic/addons.cc
  src/logic/addons.h
  src/network/net_addons.cc
  src/network/net_addons.h
  src/ui_basic/progressbar.cc
  src/ui_basic/progressbar.h
  src/ui_basic/window.h
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/wlapplication.cc
  src/wlapplication_messages.cc
Labels: addon, enhancement, urgent

#4571 Fix crash when worker's terraform program fails
  src/logic/map_objects/tribes/worker.cc
Labels: bug, crashes or hangs, tribes, urgent

#4613 Tweak ATL New World start
  data/tribes/initialization/atlanteans/starting_conditions/new_world.lua
Labels: atlanteans, balancing & gameplay

#4615 Fix crashes in seafaring tutorial
  data/campaigns/tutorial03_seafaring.wmf/scripting/mission_thread.lua
  src/scripting/lua_map.cc
Labels: crashes or hangs, ferry&ww, lua, tutorials

#4620 Fix forwarding of keypresses in main menu
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/menu.cc
Labels: bug, ui

#4616 Add missing postload call for replays
  src/logic/game.cc
Labels: bug, replay, urgent

#4614 Move autosave messages to info panel
  src/notifications/note_ids.h
  src/wui/CMakeLists.txt
  src/wui/chat_overlay.cc
  src/wui/info_panel.cc
  src/wui/info_panel.h
  src/wui/interactive_base.cc
  src/wui/logmessage.h
Labels: bug, saveloading & compatibility, ui

#4633 Show initial status message for win conditions
  data/scripting/win_conditions/win_condition_functions.lua
Labels: lua, wincondition

#4624 Fix game tips display
  src/logic/game.cc
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/ui_basic/progresswindow.cc
  src/ui_basic/progresswindow.h
  src/ui_fsmenu/launch_spg.cc
  src/wui/game_tips.cc
  src/wui/game_tips.h
Labels: bug, ui

#4476 Configurable keyboard shortcuts
  src/CMakeLists.txt
  src/editor/editorinteractive.cc
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/keyboard_options.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/interactive_base.cc
  src/wui/interactive_gamebase.cc
Labels: accessibility, enhancement, urgent

#4529 Indicate stock/target amount relations in stock menu
  data/templates/default/init.lua
  doc/sphinx/source/themes.rst
  src/game_io/game_player_info_packet.cc
  src/graphic/style_manager.cc
  src/graphic/styles/building_statistics_style.h
  src/logic/player.cc
  src/logic/player.h
  src/wui/stock_menu.cc
  src/wui/stock_menu.h
  src/wui/waresdisplay.cc
  src/wui/waresdisplay.h
Labels: enhancement, statistics, urgent

#4637 Configurable Keyboard Shortcuts, Part 2
  src/CMakeLists.txt
  src/editor/editorinteractive.cc
  src/ui_basic/messagebox.cc
  src/ui_basic/messagebox.h
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/keyboard_options.h
  src/wlapplication.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/CMakeLists.txt
  src/wui/interactive_base.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_player.cc
  src/wui/mapview.cc
  src/wui/quicknavigation.cc
Labels: accessibility

#4640 Configurable Keyboard Shortcuts, Part 3
  data/campaigns/tutorial04_economy.wmf/scripting/texts.lua
  data/scripting/editor/editor_controls.lua
  data/tribes/scripting/help/controls.lua
  data/txts/help/common_helptexts.lua
  data/txts/tips/general_game.lua
  src/editor/editorinteractive.cc
  src/scripting/CMakeLists.txt
  src/scripting/lua_interface.cc
  src/scripting/lua_ui.cc
  src/ui_basic/editbox.cc
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/panel.cc
  src/ui_basic/table.cc
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/loadgame.cc
  src/ui_fsmenu/main.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/game_main_menu_save_game.cc
  src/wui/game_message_menu.cc
  src/wui/info_panel.cc
  src/wui/info_panel.h
  src/wui/interactive_base.cc
  src/wui/interactive_gamebase.cc
  src/wui/quicknavigation.cc
  src/wui/seafaring_statistics_menu.cc
Labels: accessibility, help, lua

#4643 Add missing textdomain calls
  src/scripting/lua_globals.cc
Labels: internationalization

#4634 v1.0 Maps Review
  data/maps/Lesser_Ring.wmf/binary/heights
  data/maps/Lesser_Ring.wmf/binary/mapobjects
  data/maps/Lesser_Ring.wmf/binary/resource
  data/maps/Lesser_Ring.wmf/binary/terrain
  data/maps/Lesser_Ring.wmf/elemental
  data/maps/Lesser_Ring.wmf/minimap.png
  data/maps/Lesser_Ring.wmf/objective
  data/maps/Lesser_Ring.wmf/player_names
  data/maps/Lesser_Ring.wmf/player_position
  data/maps/Lesser_Ring.wmf/port_spaces
  data/maps/Lesser_Ring.wmf/version
  data/maps/Sandy_Passes.wmf/binary/heights
  data/maps/Sandy_Passes.wmf/binary/mapobjects
  data/maps/Sandy_Passes.wmf/binary/resource
  data/maps/Sandy_Passes.wmf/binary/terrain
  data/maps/Sandy_Passes.wmf/elemental
  data/maps/Sandy_Passes.wmf/minimap.png
  data/maps/Sandy_Passes.wmf/objective
  data/maps/Sandy_Passes.wmf/player_names
  data/maps/Sandy_Passes.wmf/player_position
  data/maps/Sandy_Passes.wmf/port_spaces
  data/maps/Sandy_Passes.wmf/version
  data/maps/Sun_of_Fire.wmf/binary/heights
  data/maps/Sun_of_Fire.wmf/binary/mapobjects
  data/maps/Sun_of_Fire.wmf/binary/resource
  data/maps/Sun_of_Fire.wmf/binary/terrain
  data/maps/Sun_of_Fire.wmf/elemental
  data/maps/Sun_of_Fire.wmf/minimap.png
  data/maps/Sun_of_Fire.wmf/objective
  data/maps/Sun_of_Fire.wmf/player_position
  data/maps/Sun_of_Fire.wmf/port_spaces
  data/maps/Sun_of_Fire.wmf/version
  data/maps/Wideworld.wmf/binary/mapobjects
  data/maps/Wideworld.wmf/binary/resource
  data/maps/Wideworld.wmf/binary/terrain
  data/maps/Wideworld.wmf/elemental
  data/maps/Wideworld.wmf/minimap.png
  data/maps/Wideworld.wmf/objective
  data/maps/Wideworld.wmf/player_names
  data/maps/Wideworld.wmf/player_position
  data/maps/Wideworld.wmf/port_spaces
  data/maps/Wideworld.wmf/version
  data/txts/developers.json
Labels: maps

#4584 New lua methods & properties
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/partially_finished_building.h
  src/logic/map_objects/tribes/soldier.h
  src/logic/map_objects/tribes/trainingsite.cc
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
Labels: enhancement, lua, urgent
