Repository widelands/widelands, pull requests merged in 2021-05, with the labels that each got.

#4825 Allow defining target quantity and preciousness for add-on wares and workers
  src/scripting/lua_root.cc
Labels: addon, economy, tribes

#4840 Skip preloading invalid add-ons
  src/graphic/CMakeLists.txt
  src/graphic/build_texture_atlas.cc
  src/wlapplication.cc
Labels: addon, bug

#4835 Fix add-on compatibility issues in random match setup
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/random_game.h
Labels: addon, crashes or hangs, ui

#4826 Don't let invisible panels handle keys
  src/ui_basic/panel.cc
Labels: accessibility, bug, ui

#4845 Skip ca-cert update
  .github/workflows/build.yaml
Labels: building & packaging, windows

#4827 Fix several add-on cornercase crashes
  src/logic/game.cc
  src/logic/map_objects/tribes/worker_descr.cc
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/network_protocol.h
  src/scripting/lua_root.cc
Labels: addon, bug, desync, multiplayer & networking

#4850 Rename Cassava Root Field/Plantation → Cassava Field/Plantation
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_0.5.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_0.5_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_1.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_1_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_2.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_2_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_4.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/idle_4_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/init.lua
  data/tribes/buildings/productionsites/amazons/cassava_plantation/menu.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/register.lua
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_0.5.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_0.5_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_1.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_1_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_2.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_2_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_4.png
  data/tribes/buildings/productionsites/amazons/cassava_plantation/unoccupied_4_pc.png
  data/tribes/buildings/productionsites/amazons/cassava_root_plantation/register.lua
  data/tribes/immovables/cassavafield/harvested/init.lua
  data/tribes/immovables/cassavafield/harvested/register.lua
  data/tribes/immovables/cassavafield/medium/init.lua
  data/tribes/immovables/cassavafield/medium/register.lua
  data/tribes/immovables/cassavafield/ripe/init.lua
  data/tribes/immovables/cassavafield/ripe/register.lua
  data/tribes/immovables/cassavafield/small/init.lua
  data/tribes/immovables/cassavafield/small/register.lua
  data/tribes/immovables/cassavafield/tiny/init.lua
  data/tribes/immovables/cassavafield/tiny/register.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/map_objects/descriptions_compatibility_table.cc
Labels: amazons, internationalization

#4855 Don't jump to undefined landmarks
  src/wui/quicknavigation.cc
Labels: bug, regression

#4870 Fix mingw rev detection
  cmake/BzrRevision.cmake
  cmake/WlFunctions.cmake
Labels: building & packaging

#4862 Fix missing compatibility lookups during gameloading
  ChangeLog
  src/logic/map_objects/immovable_program.cc
  src/logic/map_objects/immovable_program.h
  src/map_io/map_building_packet.cc
Labels: bug, saveloading & compatibility

#4891 Better fri03 placeholder portraits
  data/campaigns/fri03.wmf/pics/angadthur.png
  data/campaigns/fri03.wmf/pics/claus.png
  data/campaigns/fri03.wmf/pics/henneke.png
  data/campaigns/fri03.wmf/pics/iniucundus.png
Labels: campaigns & scenarios, frisians, graphics

#4895 Fix codecheck path magic
  .github/workflows/build.yaml
  CMakeLists.txt
  README.md
  cmake/WlFunctions.cmake
  cmake/codecheck/CodeCheck.cmake
  cmake/codecheck/rules/images_exist.py
Labels: codecheck

#4874 Make fri03 starting port indestructible
  data/campaigns/fri03.wmf/scripting/starting_conditions.lua
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
Labels: campaigns & scenarios, frisians, lua

#4900 Fix crash when loading map with not installed add-on in editor
  src/editor/ui_menus/main_menu_load_map.cc
  src/ui_fsmenu/main.cc
Labels: addon, bug, crashes or hangs, editor

#4785 New barbarians barracks graphics by DragonAtma
  data/tribes/buildings/productionsites/barbarians/barracks/build_0.5.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_0.5_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_00.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_01.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_02.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_03.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_1.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_1_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_2.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_2_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_4.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_4_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_0.5.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_0.5_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_00.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_00_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_1.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_1_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_2.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_2_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_4.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_4_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/init.lua
  data/tribes/buildings/productionsites/barbarians/barracks/menu.png
  data/tribes/buildings/productionsites/barbarians/barracks/working_00.png
  data/tribes/buildings/productionsites/barbarians/barracks/working_00_pc.png
Labels: barbarians, graphics

#4905 Fix workers gaining experience for idling
  data/tribes/buildings/productionsites/barbarians/ax_workshop/init.lua
  data/tribes/buildings/productionsites/barbarians/coalmine/init.lua
  data/tribes/buildings/productionsites/barbarians/coalmine_deep/init.lua
  data/tribes/buildings/productionsites/barbarians/coalmine_deeper/init.lua
  data/tribes/buildings/productionsites/barbarians/goldmine_deep/init.lua
  data/tribes/buildings/productionsites/barbarians/goldmine_deeper/init.lua
  data/tribes/buildings/productionsites/barbarians/granitemine/init.lua
  data/tribes/buildings/productionsites/barbarians/ironmine_deep/init.lua
  data/tribes/buildings/productionsites/barbarians/ironmine_deeper/init.lua
  data/tribes/buildings/productionsites/barbarians/metal_workshop/init.lua
  data/tribes/buildings/productionsites/barbarians/warmill/init.lua
  data/tribes/buildings/productionsites/empire/coalmine/init.lua
  data/tribes/buildings/productionsites/empire/coalmine_deep/init.lua
  data/tribes/buildings/productionsites/empire/goldmine/init.lua
  data/tribes/buildings/productionsites/empire/goldmine_deep/init.lua
  data/tribes/buildings/productionsites/empire/ironmine/init.lua
  data/tribes/buildings/productionsites/empire/ironmine_deep/init.lua
  data/tribes/buildings/productionsites/empire/marblemine/init.lua
  data/tribes/buildings/productionsites/empire/marblemine_deep/init.lua
  data/tribes/buildings/productionsites/frisians/armor_smithy_large/init.lua
  data/tribes/buildings/productionsites/frisians/armor_smithy_small/init.lua
  data/tribes/buildings/productionsites/frisians/blacksmithy/init.lua
  data/tribes/buildings/productionsites/frisians/coalmine/init.lua
  data/tribes/buildings/productionsites/frisians/coalmine_deep/init.lua
  data/tribes/buildings/productionsites/frisians/goldmine_deep/init.lua
  data/tribes/buildings/productionsites/frisians/honey_bread_bakery/init.lua
  data/tribes/buildings/productionsites/frisians/ironmine_deep/init.lua
  data/tribes/buildings/productionsites/frisians/mead_brewery/init.lua
  data/tribes/buildings/productionsites/frisians/rockmine/init.lua
  data/tribes/buildings/productionsites/frisians/rockmine_deep/init.lua
  data/tribes/buildings/productionsites/frisians/tailors_shop/init.lua
Labels: balancing & gameplay, bug, tribes
