Repository widelands/widelands, pull requests merged in 2021-12, with the labels that each got.

#5124 Replace Boost UUID, Boost SHA1, and `std::rand`
  cmake/codecheck/rules/deprecate_boost.py
  cmake/codecheck/rules/do_not_use_std_rand.py
  src/ai/ai_help_structs.cc
  src/ai/defaultai.cc
  src/ai/defaultai_seafaring.cc
  src/ai/defaultai_warfare.cc
  src/base/random.cc
  src/base/random.h
  src/editor/tools/noise_height_tool.cc
  src/editor/ui_menus/main_menu_random_map.cc
  src/logic/CMakeLists.txt
  src/logic/game.cc
  src/logic/player.cc
  src/logic/single_player_game_settings_provider.cc
  src/network/CMakeLists.txt
  src/network/crypto.cc
  src/network/gamehost.cc
  src/network/internet_gaming.cc
  src/network/network_player_settings_backend.cc
  src/third_party/CMakeLists.txt
  src/third_party/sha1/README
  src/third_party/sha1/sha1.cc
  src/third_party/sha1/sha1.h
  src/ui_basic/CMakeLists.txt
  src/ui_basic/progresswindow.cc
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/addons/login_box.cc
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/main.cc
  src/wlapplication.cc
  src/wui/CMakeLists.txt
  src/wui/game_tips.cc
Labels: cleanup & refactoring

#5143 Deploy build artifacts to automated pre-release
  .github/workflows/build.yaml
Labels: building & packaging, macos, windows

#5139 Hide Empty Input Queue Displays
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
Labels: bug, ui, multithreading

#5131 Fix more clang-tidy checks
  src/ai/ai_help_structs.cc
  src/ai/defaultai.cc
  src/ai/defaultai_seafaring.cc
  src/economy/expedition_bootstrap.cc
  src/economy/shipping_schedule.cc
  src/graphic/animation/animation.cc
  src/graphic/minimap_renderer.cc
  src/graphic/texture_atlas.cc
  src/logic/map_objects/tribes/market.cc
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/production_program.cc
  src/map_io/map_players_view_packet.cc
  src/scripting/lua_map.cc
  src/scripting/lua_ui.cc
  src/ui_basic/tabpanel.cc
  src/ui_fsmenu/keyboard_options.cc
  src/wlapplication_options.cc
  src/wui/building_statistics_menu.cc
  src/wui/encyclopedia_window.cc
  src/wui/mapview.cc
  src/wui/plot_area.cc
  utils/check_clang_tidy_results.py
Labels: cleanup & refactoring, building & packaging

#5147 Protect map object drawing with a mutex
  src/logic/map_objects/map_object.cc
  src/wui/interactive_player.cc
  src/wui/interactive_spectator.cc
Labels: bug, multithreading

#5158 Prevent defining sprintf to libintl_sprintf
  src/base/i18n.h
Labels: building & packaging, ftbfs, windows

#5153 Allow using `--script` with `--new_game_from_template`
  src/logic/game.cc
  src/network/gamehost.cc
  src/network/gamehost.h
  src/wlapplication.cc
Labels: enhancement, lua

#5170 Fix mingw path order
  .github/workflows/build.yaml
Labels: building & packaging

#5174 Fix a texture deletion from wrong thread
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
Labels: bug, crashes or hangs, multithreading

#5164 Replace Boost::Asio → Asio
  .github/workflows/build.yaml
  CMakeLists.txt
  CREDITS
  README.md
  appveyor.yml
  cmake/WlFunctions.cmake
  cmake/codecheck/rules/deprecate_boost.py
  cmake/codecheck/rules/do_not_use_BOOST_FOREACH.py
  cmake/codecheck/rules/do_not_use_BOOST_noncopyable.py
  cmake/codecheck/rules/do_not_use_legacy_symbols.py
  cmake/codecheck/rules/do_not_use_strcasecmp.py
  cmake/codecheck/rules/images_exist.py
  cmake/codecheck/rules/translations_printf.py
  debian/control
  install-dependencies.sh
  src/graphic/text/textstream.cc
  src/network/CMakeLists.txt
  src/network/bufferedconnection.cc
  src/network/bufferedconnection.h
  src/network/netclient.cc
  src/network/nethost.cc
  src/network/nethost.h
  src/network/network.cc
  src/network/network.h
  src/network/network_lan_promotion.cc
  src/network/network_lan_promotion.h
  src/wui/debugconsole.cc
  utils/build_deps.py
Labels: cleanup & refactoring

#5159 Use vcpkg version in cache key
  .github/workflows/build.yaml
Labels: building & packaging

#5178 Force `signed char` in `AbstractNode`
  src/base/format/abstract_node.h
Labels: ftbfs
