Repository widelands/widelands, pull requests merged in 2021-07, with the labels that each got.

#4992 Define second stage static dependencies on Windows per compiler
  CMakeLists.txt
  cmake/WlFunctions.cmake
Labels: building & packaging, windows

#4879 Fix richtext escape issues in message boxes
  src/graphic/text_layout.cc
  src/graphic/text_layout.h
  src/ui_basic/messagebox.cc
  src/ui_basic/messagebox.h
  src/ui_basic/multilinetextarea.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/keyboard_options.cc
Labels: bug, ui

#5002 Fix constructionsite enhancement race condition
  src/logic/map_objects/tribes/constructionsite.cc
Labels: bug, multithreading

#5009 Catch invalid location cast in `Carrier::transport_update`
  src/logic/map_objects/tribes/carrier.cc
Labels: bug, crashes or hangs

#5007 Fix race condition when changing military-constructionsite soldier capacity
  src/logic/playercommand.cc
Labels: bug, military
