Repository widelands/widelands, pull requests merged in 2021-04, with the labels that each got.

#4797 Fix detection of amount of starting gold in fri02
  data/campaigns/fri02.wmf/scripting/init.lua
  data/campaigns/fri02.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/starting_conditions.lua
Labels: bug, campaigns & scenarios, frisians

#4800 Add text size checks in multiline editbox
  src/ui_basic/multilineeditbox.cc
Labels: ui

#4799 Fix textdomain for keyboard shortcuts
  src/wlapplication_options.cc
Labels: bug, internationalization

#4802 Forward compatibility for remote add-ons
  src/network/net_addons.cc
Labels: addon

#4807 Document `LuaDescriptions::modify_unit`
  src/scripting/lua_root.cc
Labels: documentation

#4808 More Stringfixes
  data/tribes/initialization/frisians/units.lua
  data/txts/tips/editor.lua
Labels: internationalization

#4817 Add missing richtext escape for map descriptions
  src/ui_fsmenu/mapdetailsbox.cc
Labels: bug, ui

#4810 Fix initial info panel text visibility
  src/wui/info_panel.cc
Labels: bug, ui

#4811 Don't store Script add-ons in savegames
  src/game_io/game_preload_packet.cc
Labels: addon, saveloading & compatibility

#4818 Add ordered iteration for lua tables
  data/scripting/table.lua
  data/scripting/win_conditions/hq_hunter.lua
  data/scripting/win_conditions/win_condition_functions.lua
Labels: desync, lua
