Repository widelands/widelands, pull requests merged in 2021-02, with the labels that each got.

#4652 Add missing textdomain calls
  data/scripting/win_conditions/collectors.lua
  data/scripting/win_conditions/wood_gnome.lua
  src/map_io/map_player_names_and_tribes_packet.cc
Labels: bug, internationalization, wincondition

#4623 Fix distribution of idle ships to ports
  src/economy/shipping_schedule.cc
Labels: bug, crashes or hangs, seafaring, urgent

#4603 Add-Ons Packager
  src/logic/addons.cc
  src/logic/addons.h
  src/network/net_addons.cc
  src/ui_basic/CMakeLists.txt
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/multilineeditbox.h
  src/ui_basic/text_prompt.cc
  src/ui_basic/text_prompt.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/addons_packager.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/menu_target.h
  src/wlapplication.cc
  src/wlapplication.h
Labels: addon, enhancement, maps

#4656 Delay AI initalization after scenario init
  src/ai/defaultai.cc
Labels: ai, campaigns & scenarios

#4658 Fix LAN shortcut in main menu
  src/ui_fsmenu/main.cc
Labels: accessibility, bug

#4663 Disable player and tribe buttons in scenario setup
  src/ui_fsmenu/singleplayersetupbox.cc
Labels: bug, ui

#4671 Fix Build Action
  .github/workflows/build.yaml
  utils/check_clang_tidy_results.py
Labels: building & packaging

#4657 Update hero/rookie radiobuttons
  src/editor/ui_menus/tool_change_resources_options_menu.cc
  src/ui_basic/radiobutton.cc
  src/ui_basic/radiobutton.h
  src/wui/constructionsitewindow.cc
  src/wui/general_statistics_menu.cc
  src/wui/soldierlist.cc
Labels: military, ui

#4668 New empire barracks graphics by DragonAtma
  data/tribes/buildings/productionsites/empire/barracks/idle_0.5.png
  data/tribes/buildings/productionsites/empire/barracks/idle_00.png
  data/tribes/buildings/productionsites/empire/barracks/idle_1.png
  data/tribes/buildings/productionsites/empire/barracks/idle_2.png
  data/tribes/buildings/productionsites/empire/barracks/idle_4.png
  data/tribes/buildings/productionsites/empire/barracks/init.lua
  data/tribes/buildings/productionsites/empire/barracks/menu.png
Labels: empire, graphics

#4667 Generalize addon packager
  data/templates/campaigns.lua
  src/logic/CMakeLists.txt
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/addons_packager.h
  src/ui_fsmenu/addons_packager_box.cc
  src/ui_fsmenu/addons_packager_box.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/options.cc
Labels: addon, cleanup & refactoring

#4680 MP: Do not load empty map
  src/ui_fsmenu/launch_mpg.cc
Labels: multiplayer & networking

#4675 Expose win condition name to Lua
  src/scripting/lua_root.cc
  src/scripting/lua_root.h
Labels: enhancement, lua

#4678 Campaign editing
  data/templates/campaigns.lua
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/ui_basic/editbox.cc
  src/ui_basic/multilineeditbox.cc
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/addons_packager_box.cc
  src/ui_fsmenu/addons_packager_box.h
Labels: addon

#4682 Fix two crashes with tribe add-ons
  src/scripting/lua_root.cc
  src/wui/ware_statistics_menu.cc
  src/wui/ware_statistics_menu.h
Labels: bug, crashes or hangs, saveloading & compatibility, statistics, tribes

#4687 Track descriptions instances
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
Labels: bug

#4685 Add-Ons Sync Safety
  doc/sphinx/source/add-ons.rst
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/game_io/game_class_packet.cc
  src/logic/CMakeLists.txt
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/game.cc
  src/logic/game_settings.h
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/network/net_addons.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/campaigns.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/options.cc
Labels: addon, desync, enhancement

#4691 Multiplayer setup UI fixes
  src/logic/game_settings.cc
  src/logic/game_settings.h
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/wui/game_client_disconnected.cc
Labels: campaigns & scenarios, multiplayer & networking, ui

#4695 Building animation for empire barracks by DragonAtma
  data/tribes/buildings/productionsites/empire/barracks/build_0.5.png
  data/tribes/buildings/productionsites/empire/barracks/build_1.png
  data/tribes/buildings/productionsites/empire/barracks/build_2.png
  data/tribes/buildings/productionsites/empire/barracks/build_4.png
  data/tribes/buildings/productionsites/empire/barracks/init.lua
Labels: empire, graphics

#4692 Enforce host's choice of add-ons on clients
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/network_protocol.h
Labels: addon, multiplayer & networking

#4694 Add-ons performance tweaks
  src/graphic/CMakeLists.txt
  src/graphic/build_texture_atlas.cc
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/addons_packager.h
Labels: addon, graphics, ui

#4698 Fix clang compiler warnings
  src/logic/map_objects/immovable_program.h
  src/logic/mutable_addon.cc
  src/scripting/lua_ui.h
Labels: codecheck

#4666 Warn&Exit on too old OpenGL version
  src/graphic/gl/initialize.cc
Labels: graphics

#4700 Localize timestamps of remote add-ons
  src/ui_fsmenu/addons.cc
Labels: addon, internationalization

#4696 Fix Trident of Fire player slot detection
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/binary/heights
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/binary/mapobjects
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/binary/resource
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/binary/terrain
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/elemental
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/minimap.png
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/objective
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/player_names
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/player_position
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/port_spaces
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/scripting/initial_conditions.lua
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/scripting/map_editing.lua
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/scripting/multiplayer_init.lua
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/version
Labels: bug, campaigns & scenarios, multiplayer & networking

#4703 No message box on "CLIENT_LEFT_GAME"
  src/network/gameclient.cc
Labels: bug, multiplayer & networking, ui

#4462 Send localized cheating messages
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/network_gaming_messages.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
Labels: internationalization, urgent

#4546 Ensure utils directory works with Python3
  .github/workflows/build.yaml
  utils/check_clang_tidy_results.py
  utils/crop_animation.py
  utils/generate_glossary.py
  utils/glossary_checks.py
  utils/optimize_pngs.py
  utils/run-clang-tidy.py
  utils/update_copyright.py
Labels: python, urgent

#4706 Hotfix for savegame compatibility #4273
  src/logic/playercommand.cc
  src/scripting/lua_map.cc
Labels: saveloading & compatibility

#4702 Allow starting game from template
  data/templates/new_game_template
  src/graphic/color.cc
  src/graphic/color.h
  src/logic/addons.h
  src/network/gameclient.cc
  src/wlapplication.cc
  src/wlapplication.h
  src/wlapplication_messages.cc
Labels: enhancement

#4709 Make atlantean Discovery start easier
  data/tribes/initialization/atlanteans/starting_conditions/discovery.lua
Labels: atlanteans, balancing & gameplay

#4690 Immovable savegame compatibility
  src/logic/map_objects/immovable.cc
Labels: bug, saveloading & compatibility

#4708 Support custom tribes in add-ons
  data/scripting/win_conditions/collectors.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  data/tribes/scripting/help/tips.lua
  doc/sphinx/source/add-ons.rst
  src/graphic/build_texture_atlas.cc
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_basic_info.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/logic/single_player_game_settings_provider.cc
  src/network/gamehost.cc
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
  src/scripting/lua_path.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/singleplayerdropdown.cc
  src/wui/CMakeLists.txt
  src/wui/game_tips.cc
Labels: addon, tribes

#4710 Reduce crashes from missing add-on dependencies
  src/logic/addons.cc
  src/logic/addons.h
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/loadgame.cc
  src/wui/gamedetails.cc
  src/wui/gamedetails.h
  src/wui/mapdetails.cc
Labels: addon

#4714 Set minimal progress value in add-on packager
  src/ui_fsmenu/addons_packager.cc
Labels: addon, crashes or hangs
