Repository widelands/widelands, pull requests merged in 2021-09, with the labels that each got.

#5053 Wheel and key fixes
  src/ui_basic/listselect.cc
  src/ui_basic/tabpanel.cc
  src/wui/mapview.cc
Labels: ui

#5039 Update Add-Ons Manager for Protocol Version 5
  doc/sphinx/source/add-ons.rst
  src/base/math.cc
  src/base/math.h
  src/logic/CMakeLists.txt
  src/logic/addons.cc
  src/logic/addons.h
  src/network/CMakeLists.txt
  src/network/net_addons.cc
  src/network/net_addons.h
  src/ui_basic/checkbox.cc
  src/ui_basic/checkbox.h
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/manager.h
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
  src/ui_fsmenu/addons/rows_ui.cc
  src/ui_fsmenu/addons/rows_ui.h
  src/ui_fsmenu/addons/screenshot_upload.cc
Labels: enhancement, cleanup & refactoring, ui, addon

#5057 Fix clang compiler warnings
  src/ui_basic/dropdown.h
  src/ui_basic/panel.h
  src/wui/economy_options_window.cc
  src/wui/economy_options_window.h
Labels: cleanup & refactoring

#5066 Disable keys for fullscreen and screenshot when changing shortcuts
  src/ui_fsmenu/keyboard_options.cc
  src/wlapplication.cc
  src/wlapplication.h
Labels: bug, ui

#5060 Fix immovable savegame compatibility Long Long Way
  src/logic/map_objects/immovable.cc
Labels: bug, maps, world, saveloading & compatibility
