Repository widelands/widelands, pull requests merged in 2021-11, with the labels that each got.

#5084 Allow validating appdata.xml with appstream-util
  utils/update_appdata.py
Labels: python, building & packaging

#5102 Fix release ordering in appdata.xml
  xdg/org.widelands.Widelands.appdata.xml
  xdg/org.widelands.Widelands.appdata.xml.stub
Labels: building & packaging

#5070 Cleanup player end statuses on loading
  src/base/multithreading.cc
  src/logic/playersmanager.cc
Labels: bug, crashes or hangs, saveloading & compatibility, multithreading

#5099 Intelligent worker reordering
  src/ai/defaultai.cc
  src/economy/flag.cc
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/map_io/map_buildingdata_packet.cc
  src/wui/productionsitewindow.cc
Labels: enhancement, tribes, economy

#4866 Support more properties in modify_unit
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/militarysite.h
  src/logic/map_objects/tribes/trainingsite.cc
  src/logic/map_objects/tribes/trainingsite.h
  src/logic/map_objects/tribes/warehouse.h
  src/logic/map_objects/world/terrain_description.cc
  src/logic/map_objects/world/terrain_description.h
  src/scripting/lua_root.cc
  src/scripting/lua_root.h
Labels: enhancement, tribes, addon

#5094 Convert Attack Box to Window
  src/ui_basic/panel.h
  src/wui/CMakeLists.txt
  src/wui/attack_box.cc
  src/wui/attack_window.cc
  src/wui/attack_window.h
  src/wui/buildingwindow.cc
  src/wui/fieldaction.cc
  src/wui/interactive_base.cc
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
Labels: military, ui

#5110 Fastplace Groups
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/keyboard_options.h
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/interactive_player.cc
Labels: enhancement, tribes, accessibility

#4936 Add-ons: Disambiguations for dither layers and registries
  data/world/resources/coal/init.lua
  data/world/resources/coal/register.lua
  data/world/resources/fish/init.lua
  data/world/resources/fish/register.lua
  data/world/resources/gold/init.lua
  data/world/resources/gold/register.lua
  data/world/resources/iron/init.lua
  data/world/resources/iron/register.lua
  data/world/resources/register.lua
  data/world/resources/stones/init.lua
  data/world/resources/stones/register.lua
  data/world/resources/water/init.lua
  data/world/resources/water/register.lua
  data/world/terrains/desert/beach/init.lua
  doc/sphinx/extract_rst.py
  src/logic/map_objects/description_manager.cc
  src/logic/map_objects/description_manager.h
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/logic/map_objects/world/terrain_description.cc
  src/logic/map_objects/world/terrain_description.h
  test/maps/lua_testsuite.wmf/scripting/terrains_resources_descriptions.lua
Labels: bug, enhancement, world, addon

#5108 Clean some more clang-tidy checks
  .github/workflows/build.yaml
  src/ai/defaultai.cc
  src/ai/defaultai_warfare.cc
  src/base/multithreading.cc
  src/economy/test/test_road.cc
  src/economy/test/test_routing.cc
  src/economy/ware_instance.cc
  src/economy/waterway.cc
  src/economy/workers_queue.cc
  src/editor/editorinteractive.cc
  src/graphic/animation/nonpacked_animation.cc
  src/graphic/animation/spritesheet_animation.cc
  src/graphic/font_handler.cc
  src/graphic/text/rt_render.cc
  src/io/filesystem/zip_filesystem.cc
  src/logic/editor_game_base.cc
  src/logic/game.cc
  src/logic/map_objects/buildcost.cc
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/dismantlesite.cc
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/mutable_addon.cc
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/map_io/map_elemental_packet.cc
  src/map_io/map_players_messages_packet.cc
  src/map_io/s2map.cc
  src/network/bufferedconnection.cc
  src/network/internet_gaming.cc
  src/network/net_addons.cc
  src/network/nethost.cc
  src/ui_basic/messagebox.cc
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/screenshot_upload.cc
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mousewheel_options.cc
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/scenario_select.cc
  src/wlapplication.cc
  src/wui/constructionsitewindow.cc
  src/wui/fieldaction.cc
  src/wui/game_debug_ui.cc
  src/wui/game_main_menu_save_game.cc
  src/wui/game_message_menu.cc
  src/wui/gamedetails.cc
  src/wui/general_statistics_menu.cc
  src/wui/info_panel.cc
  src/wui/mapdetails.cc
  src/wui/mapview.cc
  src/wui/savegamedata.cc
  utils/check_clang_tidy_results.py
Labels: codecheck, cleanup & refactoring

#5114 Resolve thread sanitizer issues
  CMakeLists.txt
  cmake/WlFunctions.cmake
  compile.sh
  src/CMakeLists.txt
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/defaultai.h
  src/ai/defaultai_warfare.cc
  src/base/CMakeLists.txt
  src/base/multithreading.cc
  src/base/multithreading.h
  src/base/times.h
  src/economy/ferry_fleet.cc
  src/economy/ship_fleet.cc
  src/economy/ship_fleet.h
  src/economy/shipping_schedule.cc
  src/graphic/CMakeLists.txt
  src/graphic/gl/dither_program.cc
  src/graphic/gl/terrain_program.cc
  src/io/CMakeLists.txt
  src/io/profile.h
  src/logic/CMakeLists.txt
  src/logic/field.h
  src/logic/game.h
  src/logic/map.cc
  src/logic/map_objects/CMakeLists.txt
  src/logic/map_objects/bob.cc
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable.h
  src/logic/map_objects/map_object.h
  src/logic/map_objects/tribes/constructionsite.h
  src/logic/map_objects/tribes/dismantlesite.h
  src/logic/map_objects/tribes/ferry.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/worker.cc
  src/logic/player.cc
  src/logic/player.h
  src/logic/replay.cc
  src/logic/widelands_geometry.h
  src/map_io/CMakeLists.txt
  src/map_io/map_players_view_packet.cc
  src/ui_basic/CMakeLists.txt
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/wlapplication.cc
  src/wlapplication.h
  src/wui/attack_window.cc
  src/wui/building_statistics_menu.cc
  src/wui/economy_options_window.cc
  src/wui/watchwindow.cc
  utils/build_deps.py
Labels: memory & performance, multithreading

#5125 Fix worker reordering stack overflow
  src/logic/map_objects/tribes/productionsite.cc
Labels: bug, memory & performance

#5128 Keep GameController pointer alive for template game
  src/wlapplication.cc
Labels: multiplayer & networking

#5129 Fix Frequent Testsuite Timeouts
  CMakeLists.txt
  src/base/multithreading.cc
  src/base/multithreading.h
  src/logic/game.cc
  src/logic/game.h
  src/ui_basic/panel.cc
Labels: bug, testing, multithreading

#5127 Add debug output to help trace bug #5052
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
Labels: bug

#5092 Add-Ons Protocol Version 6
  src/network/net_addons.cc
  src/network/net_addons.h
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
Labels: enhancement, addon

#5137 Fix static initialisation order in unit tests
  src/base/test.cc
  src/base/test.h
Labels: bug, crashes or hangs, testing

#5133 Replace `boost::signals2`
  cmake/codecheck/rules/deprecate_boost.py
  src/logic/map_objects/map_object.h
  src/logic/map_objects/tribes/building.h
  src/network/CMakeLists.txt
  src/network/participantlist.cc
  src/network/participantlist.h
  src/notifications/CMakeLists.txt
  src/notifications/signal.h
  src/ui_basic/button.h
  src/ui_basic/checkbox.h
  src/ui_basic/dropdown.h
  src/ui_basic/editbox.h
  src/ui_basic/icongrid.h
  src/ui_basic/listselect.h
  src/ui_basic/messagebox.h
  src/ui_basic/multilineeditbox.h
  src/ui_basic/panel.h
  src/ui_basic/radiobutton.h
  src/ui_basic/scrollbar.h
  src/ui_basic/slider.h
  src/ui_basic/spinbox.h
  src/ui_basic/table.h
  src/ui_basic/tabpanel.h
  src/ui_basic/unique_window.h
  src/ui_fsmenu/addons/manager.cc
  src/wui/constructionsitewindow.h
  src/wui/fieldaction.cc
  src/wui/game_chat_panel.cc
  src/wui/game_chat_panel.h
  src/wui/mapview.h
  src/wui/minimap.h
  src/wui/plot_area.h
  src/wui/unique_window_handler.h
  src/wui/watchwindow.h
Labels: cleanup & refactoring

#5141 Allow loading addons with unit replacements first
  src/logic/map_objects/description_manager.cc
Labels: bug, world, tribes, addon

#5144 Fix segfault when signal lambda deletes itself
  src/notifications/signal.h
Labels: bug, crashes or hangs

#5132 Github MSVC CI action
  .github/workflows/build.yaml
  CMakeLists.txt
  cmake/WlFunctions.cmake
  src/base/log.cc
  src/logic/map_objects/tribes/productionsite.cc
  utils/win32/innosetup/Widelands.iss
Labels: building & packaging, windows

#5146 Allow productionsite programs to handle `callworker` failure
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/production_program.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/map_objects/tribes/worker_program.cc
Labels: enhancement, tribes, balancing & gameplay
