Repository widelands/widelands, pull requests merged in 2021-06, with the labels that each got.

#4902 Catch more editor exceptions gracefully
  src/editor/CMakeLists.txt
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/graphic/render_queue.cc
  src/graphic/render_queue.h
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable.h
  src/logic/map_objects/immovable_program.cc
  src/logic/map_objects/immovable_program.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/ui_fsmenu/main.cc
  src/wlapplication.cc
  src/wui/CMakeLists.txt
  src/wui/interactive_base.cc
Labels: bug, crashes or hangs, editor

#4921 Fix additional expedition items saveloading
  src/map_io/map_buildingdata_packet.cc
Labels: bug, saveloading & compatibility, seafaring, tribes, urgent

#4923 New atlantean & updated barbarian barracks graphics by DragonAtma
  data/tribes/buildings/productionsites/atlanteans/barracks/build_0.5.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_0.5_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_1.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_1_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_2.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_2_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_4.png
  data/tribes/buildings/productionsites/atlanteans/barracks/build_4_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_0.5.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_0.5_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_00.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_00_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_1.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_1_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_2.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_2_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_4.png
  data/tribes/buildings/productionsites/atlanteans/barracks/idle_4_pc.png
  data/tribes/buildings/productionsites/atlanteans/barracks/init.lua
  data/tribes/buildings/productionsites/atlanteans/barracks/menu.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_0.5.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_0.5_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_1.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_1_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_2.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_2_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_4.png
  data/tribes/buildings/productionsites/barbarians/barracks/build_4_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_0.5.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_0.5_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_1.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_1_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_2.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_2_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_4.png
  data/tribes/buildings/productionsites/barbarians/barracks/idle_4_pc.png
  data/tribes/buildings/productionsites/barbarians/barracks/init.lua
  data/tribes/buildings/productionsites/barbarians/barracks/menu.png
Labels: atlanteans, barbarians, graphics

#4883 Remove invisible scrollbar in dropdown
  src/ui_basic/listselect.cc
Labels: ui

#4913 Chasing the `SupplyList::remove_supply` crash
  src/economy/flag.cc
  src/economy/supply_list.cc
  src/economy/supply_list.h
  src/economy/ware_instance.cc
  src/economy/ware_instance.h
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/tribes/ship.cc
Labels: bug, crashes or hangs, economy, memory & performance

#4884 Multiplayer template game
  data/templates/new_game_template
  src/network/CMakeLists.txt
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.cc
  src/network/host_game_settings_provider.h
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/wlapplication.cc
Labels: enhancement, multiplayer & networking

#4806 Command line overhaul
  src/main.cc
  src/wlapplication.cc
  src/wlapplication.h
  src/wlapplication_messages.cc
  src/wlapplication_messages.h
  src/wlapplication_options.cc
Labels: enhancement, help

#4747 Use shared_ptr for AddOnInfo
  src/base/i18n.cc
  src/base/i18n.h
  src/editor/editorinteractive.cc
  src/editor/tools/info_tool.cc
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/game_io/game_loader.cc
  src/game_io/game_preload_packet.cc
  src/logic/CMakeLists.txt
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game_settings.h
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_basic_info.h
  src/map_io/map_elemental_packet.cc
  src/map_io/map_loader.h
  src/map_io/s2map.cc
  src/map_io/s2map.h
  src/map_io/widelands_map_loader.cc
  src/map_io/widelands_map_loader.h
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/net_addons.cc
  src/network/net_addons.h
  src/scripting/CMakeLists.txt
  src/scripting/lua_globals.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/addons.h
  src/ui_fsmenu/addons_packager.cc
  src/ui_fsmenu/campaigns.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/random_game.cc
  src/wlapplication.cc
  src/wui/mapdata.cc
Labels: addon, cleanup & refactoring, internationalization

#4784 Localize certain hotkeys
  src/wlapplication_options.cc
Labels: enhancement, internationalization

#4940 Write config after sound initialization
  src/sound/sound_handler.cc
  src/wlapplication.cc
Labels: sounds & music

#4843 In-game game/scenario loading
  data/campaigns/atl01.wmf/scripting/texts.lua
  data/campaigns/bar01.wmf/scripting/texts.lua
  data/campaigns/bar02.wmf/scripting/texts.lua
  data/campaigns/emp01.wmf/scripting/texts.lua
  data/campaigns/emp02.wmf/scripting/texts.lua
  data/campaigns/emp03.wmf/scripting/texts.lua
  data/campaigns/emp04.wmf/scripting/texts.lua
  data/campaigns/fri01.wmf/scripting/texts.lua
  data/campaigns/fri02.wmf/scripting/texts.lua
  data/campaigns/fri03.wmf/scripting/texts.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/campaigns/tutorial02_warfare.wmf/scripting/texts.lua
  data/campaigns/tutorial03_seafaring.wmf/scripting/texts.lua
  data/campaigns/tutorial04_economy.wmf/scripting/texts.lua
  data/images/wui/menus/load_game.png
  data/images/wui/menus/restart_scenario.png
  data/scripting/messages.lua
  src/game_io/game_class_packet.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/replay_game_controller.cc
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/scripting/lua_game.cc
  src/ui_basic/panel.cc
  src/ui_fsmenu/internet_lobby.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_mpg.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/loadgame.cc
  src/ui_fsmenu/netsetup_lan.h
  src/ui_fsmenu/scenario_select.cc
  src/ui_fsmenu/scenario_select.h
  src/wlapplication.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/game_client_disconnected.h
  src/wui/game_exit_confirm_box.cc
  src/wui/game_exit_confirm_box.h
  src/wui/game_main_menu_save_game.cc
  src/wui/game_main_menu_save_game.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/story_message_box.cc
  src/wui/story_message_box.h
  test/maps/plain.wmf/scripting/test_ui.lua
Labels: campaigns & scenarios, enhancement, saveloading & compatibility, tutorials, ui

#4945 Add theme image `ending.png` to themes documentation
  doc/sphinx/source/themes.rst
Labels: documentation

#4943 Resolve threading race conditions by assigning mutex locking priorities
  src/base/multithreading.cc
  src/ui_basic/panel.cc
  src/wui/interactive_base.cc
  test/maps/expedition.wmf/scripting/test_no_double_colonizing.lua
Labels: bug, memory & performance, multithreading

#4949 Screenshot notification
  src/io/filesystem/disk_filesystem.cc
  src/wlapplication.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
Labels: enhancement, ui

#4948 Break mutex deadlock in GameClient
  src/base/multithreading.cc
  src/base/multithreading.h
  src/network/gameclient.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  test/maps/expedition.wmf/scripting/init.lua
Labels: bug, multiplayer & networking, multithreading

#4955 replenish reed in Frisian trading outpost
  data/tribes/initialization/frisians/starting_conditions/trading_outpost.lua
Labels: frisians, tribes

#4901 Add soldiers overview tab to WarehouseWindow
  src/wui/soldier_statistics_menu.cc
  src/wui/soldier_statistics_menu.h
  src/wui/warehousewindow.cc
  test/maps/expedition.wmf/scripting/init.lua
Labels: enhancement, military, ui

#4954 Reset Lua interface when loading games in-game
  src/logic/editor_game_base.cc
Labels: bug, lua, saveloading & compatibility

#4760 Fix duplicate description registries by add-ons
  data/world/critters/badger/init.lua
  data/world/immovables/artifacts/artifact00/init.lua
  doc/sphinx/source/add-ons.rst
  doc/sphinx/source/lua_tribes_units.rst.org
  doc/sphinx/source/lua_world_units.rst.org
  src/logic/map_objects/description_manager.cc
  src/ui_fsmenu/addons.cc
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/scenario_select.cc
Labels: addon, bug, crashes or hangs, tribes, world

#4970 Fix game client deletion crash
  src/logic/game_controller.h
  src/network/gameclient.h
  src/network/gamehost.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
Labels: bug, crashes or hangs, multiplayer & networking

#4966 Fix more threading-related issues
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/progresswindow.cc
  src/wui/inputqueuedisplay.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
Labels: bug, crashes or hangs, multithreading, ui

#4968 Multiplayer setup UI improvements
  src/game_io/game_player_info_packet.cc
  src/logic/game.cc
  src/logic/player.cc
  src/logic/player.h
  src/map_io/map_player_names_and_tribes_packet.cc
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/multiplayersetupgroup.h
Labels: enhancement, multiplayer & networking, ui

#4971 Disambiguate productionsites' worker(s) missing/coming strings
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
Labels: amazons, enhancement, internationalization, tribes

#4853 Autogenerate and compare datadir version file
  .gitignore
  CMakeLists.txt
  cmake/datadirversion.cmake
  src/CMakeLists.txt
  src/wlapplication.cc
  utils/win32/innosetup/Widelands.iss
Labels: building & packaging, enhancement

#4973 Set Win logging dir in all main functions
  src/website/map_info.cc
  src/website/map_object_info.cc
Labels: windows

#4956 Some renamings and string fixes
  data/campaigns/emp04.wmf/scripting/texts.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/campaigns/tutorial02_warfare.wmf/scripting/texts.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/frisians/units.lua
  data/tribes/scripting/help/controls.lua
  data/world/init.lua
  data/world/map_generation.lua
  data/world/terrains/winter/snow/init.lua
  data/world/terrains/winter/taiga/idle.png
  data/world/terrains/winter/taiga/register.lua
  data/world/terrains/winter/taiga1/idle.png
  data/world/terrains/winter/taiga1/init.lua
  data/world/terrains/winter/taiga1/register.lua
  data/world/terrains/winter/taiga2/idle.png
  data/world/terrains/winter/taiga2/init.lua
  data/world/terrains/winter/taiga2/register.lua
  data/world/terrains/winter/taiga3/idle.png
  data/world/terrains/winter/taiga3/init.lua
  data/world/terrains/winter/taiga3/register.lua
  data/world/terrains/winter/tundra/idle.png
  data/world/terrains/winter/tundra/init.lua
  data/world/terrains/winter/tundra/register.lua
  data/world/terrains/winter/tundra2/register.lua
  data/world/terrains/winter/tundra3/register.lua
  data/world/terrains/winter/tundra_taiga/init.lua
  src/logic/map_objects/descriptions_compatibility_table.cc
  src/map_io/map_version_packet.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/options.cc
  src/wlapplication_options.cc
  src/wui/interactive_gamebase.cc
Labels: internationalization, tribes, world

#4896 Show message box when a replay desyncs
  src/logic/replay.cc
Labels: desync, enhancement, replay, ui

#4918 Fix invalid resource loading
  src/map_io/map_resources_packet.cc
Labels: bug, saveloading & compatibility, world

#4980 compile.sh improvements
  .gitignore
  compile.sh
Labels: building & packaging, enhancement
