Repository widelands/widelands, pull requests merged in 2022-05, with the labels that each got.

#5371 Fix workarea display bug
  src/wui/fieldaction.cc
Labels: ui

#5373 Enable include order codecheck on header files
  cmake/codecheck/rules/correct_include_order.py
  src/base/i18n.h
  src/graphic/text/rt_errors.h
  src/io/filesystem/zip_filesystem.h
  src/map_io/coords_profile.h
  src/notifications/notifications_impl.h
  src/ui_basic/CMakeLists.txt
  src/ui_basic/editbox.h
  src/ui_basic/window.h
  src/ui_fsmenu/singleplayersetupbox.h
  src/ui_fsmenu/training_wheel_options.h
  src/wui/watchwindow.h
  utils/find_unused_includes.py
Labels: codecheck

#5383 Move definition of WL_INSTALL_BINDIR
  CMakeLists.txt
  src/CMakeLists.txt
Labels: building & packaging

#5392 Use Debian Minizip Library for the PPA
  debian/control
Labels: building & packaging, linux

#5393 Restore global descriptions for savegame compatibility
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
Labels: tribes, saveloading & compatibility, lua

#5396 remove SYSTEM from target_compile_options
  cmake/WlFunctions.cmake
Labels: building & packaging, urgent

#5369 Update Elders and Chieftains
  data/txts/developers.json
Labels: urgent

#5399 Fix string bugs in lore texts reported on Transifex
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/empire/units.lua
Labels: bug, help, empire, atlanteans

#5358 CMakeLists.txt:add custom uninstall target
  .github/workflows/build.yaml
  CMakeLists.txt
  cmake/cmake_uninstall.cmake.in
  xdg/CMakeLists.txt
Labels: enhancement, building & packaging, urgent

#5401 Restore iterator after insertion in defaultai
  src/ai/defaultai.cc
Labels: bug, ai

#5406 Preallocate task stack before program update
  src/logic/map_objects/bob.cc
Labels: saveloading & compatibility

#5409 Fix use of vector fill constructor
  src/wui/general_statistics_menu.h
Labels: bug

#5417 Resolve relative parts before uninstalling empty dirs
  cmake/cmake_uninstall.cmake.in
Labels: building & packaging, testing

#5385 reformat version string (remove markdown format)
  .github/workflows/build.yaml
  cmake/BzrRevision.cmake
  cmake/InputRevision.cmake
  src/base/log.cc
  src/build_info.cc.cmake
  src/build_info.h
  src/editor/editorinteractive.cc
  src/graphic/graphic.cc
  src/io/profile.cc
  src/logic/replay.cc
  src/main.cc
  src/ui_fsmenu/about.cc
  src/ui_fsmenu/main.cc
  src/wlapplication.cc
  src/wlapplication_messages.cc
  src/wlapplication_messages.h
  utils/detect_revision.py
Labels: urgent

#5426 Fix collapsing permanently collapsed input queues
  src/wui/inputqueuedisplay.cc
Labels: bug, crashes or hangs, ui, urgent

#5415 Update testsuite compilers and OSs for Jammy
  .github/scripts/install_deps.sh
  .github/workflows/build.yaml
  .github/workflows/format.yaml
  .github/workflows/i18n.yaml
  CMakeLists.txt
  src/base/log.cc
  src/editor/editorinteractive.h
  src/io/filesystem/disk_filesystem.cc
Labels: testing

#5430 Remove NOCOM comments
  src/ai/ai_help_structs.h
  src/ai/defaultai.h
Labels: codecheck, ai

#5436 Thread safe destructor for Texture shared_ptr
  src/graphic/texture.cc
Labels: graphics, multithreading
