Repository widelands/widelands, pull requests merged in 2022-09, with the labels that each got.

#5538 Remove outdated info that add-on maps should not be zipped
  doc/sphinx/source/add-ons.rst
  src/map_io/map_players_view_packet.cc
  src/ui_fsmenu/addons/packager_box.cc
Labels: maps, addon

#5543 fix initialisation of inverted horizontal scrolling compensation
  src/wlapplication.cc
Labels: bug, linux, accessibility, ui

#5539 CI system updates
  CMakeLists.txt
  appveyor.yml
Labels: building & packaging

#5532 Update Asio to version 1.24.0 in download_asio.sh
  utils/download_asio.sh
Labels: building & packaging

#5545 Support Non-Indexed Terrain Textures
  src/logic/map_objects/world/terrain_description.cc
Labels: bug, crashes or hangs, linux, graphics

#5547 Use old style name for SDL pixelformat
  src/logic/map_objects/world/terrain_description.cc
Labels: bug, building & packaging, ftbfs, linux, graphics

#5554 Misc Replay Fixes
  src/game_io/game_interactive_player_packet.cc
  src/ui_fsmenu/loadgame.cc
Labels: replay, ui
