Repository widelands/widelands, pull requests merged in 2022-08, with the labels that each got.

#5452 Enable Enter/Escape Keys in Add-Ons Admin Dialog
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
Labels: accessibility, urgent, addon

#5484 Added static SDL2 targets for transitioning
  cmake/Modules/FindSDL2.cmake
  cmake/Modules/FindSDL2_image.cmake
  cmake/Modules/FindSDL2_mixer.cmake
  cmake/Modules/FindSDL2_ttf.cmake
Labels: building & packaging, windows

#5480 Fix too-early add-on descriptions registries
  src/editor/editorinteractive.cc
  src/game_io/game_class_packet.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable.h
  src/logic/replay.cc
  src/ui_fsmenu/keyboard_options.cc
Labels: bug, world, addon

#5490 Disable logging in notifications test
  src/notifications/test/notifications_test.cc
Labels: testing, windows

#5492 Optimized height calculation for map preview
  src/logic/map.cc
  src/logic/map.h
  src/map_io/widelands_map_loader.cc
Labels: memory & performance

#5491 Make Save/Load Game Dialog Truly Modal
  src/base/multithreading.cc
  src/ui_basic/panel.cc
  src/wui/game_main_menu_save_game.cc
  src/wui/game_main_menu_save_game.h
Labels: bug, ui, regression, multithreading

#5497 Warp mouse to target when launching attack
  src/wui/attack_window.cc
Labels: military, ui, regression

#5494 Use SDL Relative Mouse Mode
  src/ui_basic/panel.cc
  src/wlapplication.cc
  src/wlapplication.h
Labels: accessibility, urgent

#5499 Richtext-Escape Hotkey Strings
  src/editor/editorinteractive.cc
  src/scripting/lua_ui.cc
  src/ui_basic/dropdown.h
  src/ui_fsmenu/main.cc
  src/wlapplication_options.h
  src/wui/game_message_menu.cc
  src/wui/interactive_base.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_player.cc
  src/wui/seafaring_statistics_menu.cc
Labels: bug, graphics, ui

#5495 Consistent UI keyboard selection
  src/editor/ui_menus/main_menu_new_map.cc
  src/editor/ui_menus/main_menu_new_map.h
  src/ui_basic/button.cc
  src/ui_basic/checkbox.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/listselect.cc
  src/ui_basic/multilineeditbox.cc
Labels: accessibility, ui, urgent

#5510 Fix fri03 v1.0 Saveloading Compatibility
  src/logic/map_objects/description_manager.cc
  src/logic/map_objects/tribes/tribe_descr.cc
Labels: bug, saveloading & compatibility, frisians, urgent

#5513 Disable `-Werror` in Release Builds
  CMakeLists.txt
Labels: building & packaging

#5524 Use install-depencies.sh in workflow
  .github/scripts/install_deps.sh
  .github/workflows/build.yaml
  install-dependencies.sh
Labels: cleanup & refactoring, building & packaging

#5534 Prevent shipwright from building ferries where no ferry can live
  data/tribes/workers/amazons/shipwright/init.lua
  data/tribes/workers/atlanteans/shipwright/init.lua
  data/tribes/workers/barbarians/shipwright/init.lua
  data/tribes/workers/empire/shipwright/init.lua
  data/tribes/workers/frisians/shipwright/init.lua
  src/logic/map_objects/tribes/worker.cc
  src/logic/map_objects/tribes/worker_program.cc
Labels: bug, ferry & ww, urgent

#5536 Don't warp mouse to dropdown if it's already there
  src/ui_basic/dropdown.cc
Labels: bug, accessibility
