Repository widelands/widelands, pull requests merged in 2022-06, with the labels that each got.

#5439 training
  data/ai/ai_input_1.wai
  data/ai/ai_input_2.wai
  data/ai/ai_input_3.wai
  data/ai/ai_input_4.wai
Labels: ai

#5442 Unmark Amazons as Experimental
  data/tribes/initialization/amazons/init.lua
Labels: amazons

#5446 Improving building and dismantling mil. sites
  data/ai/ai_input_1.wai
  data/ai/ai_input_2.wai
  data/ai/ai_input_3.wai
  data/ai/ai_input_4.wai
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/defaultai.cc
  src/ai/defaultai_warfare.cc
Labels: ai

#5450 Saveload `destruction_blocked` property
  src/map_io/map_buildingdata_packet.cc
Labels: bug, saveloading & compatibility, urgent

#5394 Workaround for inverted horizontal scrolling bug in SDL
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/about.cc
  src/ui_fsmenu/mousewheel_options.cc
  src/ui_fsmenu/mousewheel_options.h
  src/ui_fsmenu/mousewheel_report.cc
  src/ui_fsmenu/mousewheel_report.h
  src/ui_fsmenu/tech_info.cc
  src/ui_fsmenu/tech_info.h
  src/wlapplication.cc
  src/wlapplication_mousewheel_options.cc
  src/wlapplication_mousewheel_options.h
Labels: bug, ui, urgent

#5377 Integrate AppImage building into CI
  .github/scripts/install_deps.sh
  .github/workflows/build.yaml
  CMakeLists.txt
Labels: enhancement, building & packaging, linux, urgent

#5091 Diplomacy
  data/campaigns/atl01.wmf/scripting/init.lua
  data/campaigns/atl02.wmf/scripting/init.lua
  data/campaigns/bar01.wmf/scripting/init.lua
  data/campaigns/bar02.wmf/scripting/init.lua
  data/campaigns/dummy.wmf/scripting/init.lua
  data/campaigns/emp01.wmf/scripting/init.lua
  data/campaigns/emp02.wmf/scripting/init.lua
  data/campaigns/emp03.wmf/scripting/init.lua
  data/campaigns/emp04.wmf/scripting/init.lua
  data/campaigns/fri01.wmf/scripting/init.lua
  data/campaigns/fri02.wmf/scripting/init.lua
  data/campaigns/fri03.wmf/scripting/init.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/init.lua
  data/campaigns/tutorial02_warfare.wmf/scripting/init.lua
  data/campaigns/tutorial03_seafaring.wmf/scripting/init.lua
  data/campaigns/tutorial04_economy.wmf/scripting/init.lua
  data/images/wui/menus/diplomacy.png
  data/maps/MP_Scenarios/Island_Hopping.wmf/scripting/multiplayer_init.lua
  data/maps/MP_Scenarios/Smugglers.wmf/scripting/multiplayer_init.lua
  data/maps/MP_Scenarios/Trident_of_Fire.wmf/scripting/multiplayer_init.lua
  data/maps/SP_Scenarios/Along_The_River.wmf/scripting/init.lua
  data/maps/SP_Scenarios/The_Green_Plateau.wmf/scripting/init.lua
  data/scripting/win_conditions/collectors.lua
  data/scripting/win_conditions/territorial_functions.lua
  data/scripting/win_conditions/win_condition_functions.lua
  src/ai/defaultai.cc
  src/base/multithreading.h
  src/game_io/game_class_packet.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/logic/widelands.h
  src/scripting/lua_game.cc
  src/scripting/lua_game.h
  src/scripting/lua_root.cc
  src/scripting/lua_root.h
  src/ui_basic/panel.h
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/CMakeLists.txt
  src/wui/game_diplomacy_menu.cc
  src/wui/game_diplomacy_menu.h
  src/wui/game_objectives_menu.cc
  src/wui/game_objectives_menu.h
  src/wui/interactive_base.cc
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
Labels: enhancement, balancing & gameplay, urgent

#5449 Rework of MS dismantlement (should_be_changed calculation)
  data/ai/ai_input_1.wai
  data/ai/ai_input_2.wai
  data/ai/ai_input_3.wai
  data/ai/ai_input_4.wai
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/defaultai.cc
  src/ai/defaultai_warfare.cc
Labels: ai

#5462 Fix Transifex String Issues
  data/campaigns/atl01.wmf/scripting/texts.lua
  data/campaigns/atl02.wmf/scripting/texts.lua
  data/tribes/buildings/productionsites/frisians/beekeepers_house/init.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/empire/units.lua
Labels: internationalization
