Repository widelands/widelands, pull requests merged in 2022-01, with the labels that each got.

#5161 Remove graphic_text_layout dependency from io_filesystem
  src/editor/CMakeLists.txt
  src/editor/ui_menus/main_menu_save_map.cc
  src/editor/ui_menus/main_menu_save_map_make_directory.cc
  src/io/filesystem/CMakeLists.txt
  src/io/filesystem/filesystem.cc
  src/io/filesystem/filesystem.h
  src/io/filesystem/illegal_filename_check.cc
  src/io/filesystem/illegal_filename_check.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/addons/packager_box.cc
  src/wui/CMakeLists.txt
  src/wui/game_main_menu_save_game.cc
Labels: cleanup & refactoring

#5157 Resolve msvc warnings
  CMakeLists.txt
  src/ai/defaultai.cc
  src/ai/defaultai_warfare.cc
  src/graphic/gl/road_program.cc
  src/graphic/gl/utils.cc
  src/graphic/gl/utils.h
  src/graphic/image_cache.cc
  src/io/filesystem/filesystem.cc
  src/ui_basic/box.cc
  src/ui_basic/scrollbar.cc
  src/ui_fsmenu/mapselect.cc
  src/wui/mapview.cc
  src/wui/mapviewpixelfunctions.cc
  src/wui/plot_area.cc
Labels: windows

#5179 Tx String and CLI Help Fixes
  data/tribes/ships/amazons/init.lua
  src/wlapplication_messages.cc
Labels: internationalization

#5176 Fix older g++ optimization segfaults
  CMakeLists.txt
Labels: crashes or hangs, building & packaging, testing

#5187 Fix -O3/-O2 typos
  CMakeLists.txt
Labels: cleanup & refactoring

#5182 Dependencies: Asio include handling & Solus support
  .gitignore
  CMakeLists.txt
  install-dependencies.sh
  utils/download_asio.sh
Labels: building & packaging, linux, bsd

#5190 More Stringfixes
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/options.cc
  src/wlapplication_messages.cc
  src/wlapplication_options.cc
Labels: internationalization

#5199 Auto-Cancel Redundant CI Workflows
  .github/workflows/build.yaml
  .github/workflows/format.yaml
  .github/workflows/i18n.yaml
  .github/workflows/launchpad_mirror.yaml
Labels: enhancement, building & packaging

#5171 Update_all_bfCheck bf redesign
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/defaultai.cc
Labels: ai

#5173 introducing limit for fields to be updated
  src/ai/defaultai.cc
  src/ai/defaultai.h
Labels: ai

#5188 Extend copyright script to update year in all files
  utils/update_copyright.py
Labels: python

#5183 Upscaled Splashscreen
  data/templates/default/loadscreens/splash.jpg
  src/graphic/align.cc
  src/graphic/align.h
  src/ui_basic/progresswindow.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
Labels: graphics

#5154 Fix Port Paths Reordering On Port Removal
  src/economy/ship_fleet.cc
  src/economy/ship_fleet.h
Labels: bug, seafaring

#5215 Add checks for unknown wares and workers when loading economy profiles
  src/wui/economy_options_window.cc
Labels: bug, crashes or hangs, economy, addon

#4787 Add script to check for optional lua parentheses
  .github/workflows/build.yaml
  utils/lua_style_checker.py
Labels: python, codecheck, lua

#5218 Update github action to windows-2022
  .github/workflows/build.yaml
Labels: building & packaging, windows
