Repository widelands/widelands, pull requests merged in 2022-07, with the labels that each got.

#5454 Fix fake-modal in-game load dialog releasing modal grab
  src/wui/game_main_menu_save_game.cc
  src/wui/game_main_menu_save_game.h
Labels: bug, crashes or hangs, ui, urgent

#5465 compile.sh fix and tweaks
  compile.sh
Labels: bug, enhancement, building & packaging

#5467 Run apt-get upgrade to prevent dependency mismatches
  .github/scripts/install_deps.sh
Labels: building & packaging

#5472 Added new SDL2-image dependencies to static linking
  CMakeLists.txt
Labels: building & packaging, windows

#5475 Fix Lua Scripting Multithreading
  src/base/multithreading.h
  src/logic/editor_game_base.cc
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/scripting/CMakeLists.txt
  src/scripting/lua_coroutine.cc
  src/scripting/lua_table.cc
  src/scripting/lua_table.h
  src/scripting/run_script.cc
Labels: bug, crashes or hangs, tribes, lua, urgent, multithreading

#5476 Military capacity string refactor
  data/tribes/initialization/amazons/military_capacity.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/military_capacity.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/military_capacity.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/military_capacity.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/military_capacity.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_basic_info.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/scripting/lua_table.cc
Labels: bug, internationalization, tribes, lua, military
