Repository widelands/widelands, pull requests merged in 2022-04, with the labels that each got.

#5350 Fix legacy scenario units load order
  src/logic/game.cc
Labels: bug, saveloading & compatibility

#5353 v1.0 Backwards Compatibility for World/Tribe Add-Ons
  src/logic/map_objects/description_manager.cc
Labels: world, tribes, addon

#5310 Clear readability-implicit-bool-conversion in logic
  src/logic/addons.cc
  src/logic/cmd_luacoroutine.cc
  src/logic/cmd_queue.cc
  src/logic/editor_game_base.cc
  src/logic/game.cc
  src/logic/generic_save_handler.cc
  src/logic/map.cc
  src/logic/map_objects/backtrace.cc
  src/logic/map_objects/bob.cc
  src/logic/map_objects/checkstep.cc
  src/logic/map_objects/description_manager.cc
  src/logic/map_objects/findbob.cc
  src/logic/map_objects/findimmovable.cc
  src/logic/map_objects/findnode.cc
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable_program.cc
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/map_object_program.cc
  src/logic/map_objects/tribes/battle.cc
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building_settings.cc
  src/logic/map_objects/tribes/carrier.cc
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/dismantlesite.cc
  src/logic/map_objects/tribes/ferry.cc
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/partially_finished_building.cc
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/trainingsite.cc
  src/logic/map_objects/tribes/tribe_basic_info.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/warelist.cc
  src/logic/map_objects/tribes/worker.cc
  src/logic/map_objects/tribes/worker_descr.cc
  src/logic/map_objects/tribes/worker_program.cc
  src/logic/map_objects/world/critter.cc
  src/logic/map_objects/world/terrain_description.cc
  src/logic/mapdifferenceregion.cc
  src/logic/mapfringeregion.cc
  src/logic/maphollowregion.cc
  src/logic/maptriangleregion.cc
  src/logic/mutable_addon.cc
  src/logic/path.cc
  src/logic/pathfield.cc
  src/logic/player.cc
  src/logic/playercommand.cc
  src/logic/playersmanager.cc
  src/logic/replay.cc
  src/logic/save_handler.cc
  src/logic/single_player_game_controller.cc
  src/logic/widelands_geometry.cc
Labels: cleanup & refactoring

#5315 Clear readability-implicit-bool-conversion in economy
  src/economy/cmd_call_economy_balance.cc
  src/economy/economy.cc
  src/economy/economy_data_packet.cc
  src/economy/expedition_bootstrap.cc
  src/economy/ferry_fleet.cc
  src/economy/flag.cc
  src/economy/idleworkersupply.cc
  src/economy/input_queue.cc
  src/economy/portdock.cc
  src/economy/request.cc
  src/economy/road.cc
  src/economy/routeastar.cc
  src/economy/router.cc
  src/economy/ship_fleet.cc
  src/economy/shipping_schedule.cc
  src/economy/shippingitem.cc
  src/economy/supply_list.cc
  src/economy/test/test_routing.cc
  src/economy/transfer.cc
  src/economy/ware_instance.cc
  src/economy/wares_queue.cc
  src/economy/waterway.cc
Labels: cleanup & refactoring, urgent

#5305 Clear readability-implicit-bool-conversion in ui_fsmenu
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/rows_ui.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/mousewheel_options.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/scenario_select.cc
  src/ui_fsmenu/singleplayerdropdown.cc
  src/ui_fsmenu/singleplayersetupbox.cc
Labels: cleanup & refactoring, urgent

#5319 Clear readability-implicit-bool-conversion
  src/economy/expedition_bootstrap.cc
  src/sound/songset.cc
  src/sound/sound_handler.cc
  src/wlapplication.cc
  src/wlapplication_mousewheel_options.cc
  src/wlapplication_options.cc
  utils/check_clang_tidy_results.py
Labels: cleanup & refactoring, urgent

#5372 Fix Sound Options Panel Styling
  src/wui/sound_options.cc
Labels: bug, ui

#5285 Add Empire lore texts
  data/tribes/initialization/empire/units.lua
Labels: enhancement, help, tribes, empire, urgent

#5370 Update ChangeLog to 0621ce2
  ChangeLog
Labels: urgent

#5360 third_party/CMakeLists.txt:only use embedded minizip if not installed
  .github/workflows/build.yaml
  CMakeLists.txt
  README.md
  cmake/WlFunctions.cmake
  src/CMakeLists.txt
  src/base/macros.h
  src/io/filesystem/CMakeLists.txt
  src/io/filesystem/zip_filesystem.h
  src/third_party/CMakeLists.txt
  utils/build_deps.py
Labels: building & packaging, linux, filesystem, urgent

#5359 CMakeLists.txt:put binaries in correct locations when installing
  CMakeLists.txt
  README.md
  cmake/WlFunctions.cmake
  debian/rules
  xdg/CMakeLists.txt
Labels: building & packaging, urgent

#5381 Calculate max battle animation height
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/soldier.h
Labels: graphics

#5382 Fix syncreport requesting during game startup
  src/network/gamehost.cc
Labels: bug, multiplayer & networking, desync, urgent
