Repository widelands/widelands, pull requests merged in 2022-10, with the labels that each got.

#5598 Update screenshots in appdata.xml
  xdg/org.widelands.Widelands.appdata.xml.stub
Labels: building & packaging, graphics, media

#5597 Relax Invalid Assumption in AttackWindow Saveloading
  src/wui/attack_window.cc
Labels: bug, crashes or hangs, saveloading & compatibility, military, ui, urgent

#5590 Do not delete units during random game loading
  src/logic/game.cc
Labels: urgent, addon, random map

#5601 Fixes in dump- and load economy scripts
  utils/dump_economy.lua
  utils/load_economy.lua
Labels: bug, lua, economy

#5568 Fix for #5501 - add set_soldiers cap
  src/scripting/lua_map.cc
Labels: bug, crashes or hangs, lua, military

#5560 Log output and formatting usage cleanups
  src/base/format/tree.h
  src/base/string.h
  src/io/filesystem/layered_filesystem.cc
  src/network/bufferedconnection.cc
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/internet_gaming.cc
  src/network/internet_gaming_messages.cc
  src/network/internet_gaming_messages.h
  src/network/network_gaming_messages.cc
  src/network/network_gaming_messages.h
  src/network/network_protocol.h
Labels: cleanup & refactoring, multiplayer & networking

#5615 Fix undefined `PATH_MAX`
  src/io/filesystem/filesystem.cc
Labels: ftbfs, filesystem, urgent

#5541 Drop support for g++-5 and g++-6
  .github/workflows/build.yaml
  CMakeLists.txt
Labels: building & packaging

#5432 Show name and experience type of missing workers
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/wui/productionsitewindow.cc
Labels: enhancement, tribes, statistics

#5611 Allow loading another replay in replay mode
  src/logic/game.cc
  src/logic/game.h
  src/logic/replay_game_controller.cc
  src/logic/replay_game_controller.h
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/loadgame.cc
  src/wlapplication.cc
  src/wui/CMakeLists.txt
  src/wui/game_main_menu_save_game.cc
  src/wui/game_main_menu_save_game.h
  src/wui/gamedetails.cc
  src/wui/gamedetails.h
  src/wui/interactive_gamebase.cc
  src/wui/load_or_save_game.cc
  src/wui/load_or_save_game.h
Labels: enhancement, replay

#5625 Require libpng >= 1.6
  CMakeLists.txt
  install-dependencies.sh
Labels: help wanted, building & packaging, macos, graphics

#5380 Configurable Win Condition Duration
  data/scripting/win_conditions/collectors.lua
  data/scripting/win_conditions/territorial_time.lua
  data/scripting/win_conditions/win_condition_functions.lua
  data/scripting/win_conditions/wood_gnome.lua
  src/game_io/game_preload_packet.cc
  src/game_io/game_preload_packet.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/game_settings.h
  src/logic/single_player_game_settings_provider.cc
  src/logic/single_player_game_settings_provider.h
  src/logic/widelands.h
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.cc
  src/network/host_game_settings_provider.h
  src/network/network_protocol.h
  src/scripting/lua_root.cc
  src/scripting/lua_root.h
  src/ui_basic/spinbox.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/wlapplication.cc
Labels: enhancement, balancing & gameplay, wincondition

#5496 Caret-escape control characters in strings
  src/base/format/string_node.h
  src/base/test/test_string.cc
Labels: enhancement

#5437 Show coming and absent soldiers in building soldier list
  src/economy/request.h
  src/economy/transfer.h
  src/logic/map_objects/tribes/building.cc
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/militarysite.h
  src/logic/map_objects/tribes/soldiercontrol.h
  src/logic/map_objects/tribes/trainingsite.cc
  src/logic/map_objects/tribes/trainingsite.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/warehouse.h
  src/wui/soldierlist.cc
Labels: enhancement, military, ui

#5621 Draw Actual Game Speed
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
Labels: enhancement, ui

#5608 Seed random number generator before starting new game
  src/game_io/game_class_packet.cc
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/network_protocol.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/random_game.cc
Labels: bug, balancing & gameplay
