Repository widelands/widelands, pull requests merged in 2022-02, with the labels that each got.

#5207 Refactor FloatNode and NumberNode
  src/base/CMakeLists.txt
  src/base/format/abstract_node.h
  src/base/format/float_node.h
  src/base/format/number_node.h
  src/base/format/tree.cc
  src/base/format/tree.h
  src/base/format/write_number.h
  src/base/test/test_string.cc
  utils/find_unused_includes.py
Labels: cleanup & refactoring

#5191 Keep progress window open until game is ready
  src/logic/game.cc
  test/maps/all_tribes.wmf/scripting/test_place_foreign_buildings.lua
  test/maps/lua_testsuite.wmf/scripting/init.lua
  test/maps/port_space.wmf/scripting/test_attack_forbidden.lua
  test/scripting/stable_save.lua
Labels: enhancement, ui

#5235 Fix Race Condition in Attack Window
  src/wui/attack_window.cc
  src/wui/attack_window.h
Labels: bug, crashes or hangs, multithreading

#5184 Ensure Notifications only reach the topmost DescriptionManager
  src/logic/map_objects/description_manager.cc
  src/logic/map_objects/description_manager.h
Labels: bug, world, tribes, addon

#5234 Show server name and check add-on version before upload
  src/network/net_addons.cc
  src/network/net_addons.h
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/manager.h
Labels: enhancement, addon

#5245 Disable Add-Ons Manager Auto-Connect & Auto-Login
  src/ui_fsmenu/addons/manager.cc
Labels: privacy, addon

#5260 Fix misc clang-tidy checks in `base`
  src/base/exceptions.cc
  src/base/format/tree.cc
  src/base/i18n.cc
  src/base/i18n.h
  src/base/log.cc
  src/base/multithreading.cc
  src/base/random.cc
  src/base/random.h
  src/base/scoped_timer.cc
  src/base/test/test_string.cc
Labels: cleanup & refactoring

#5270 fix pause and jump in empire mill working animation
  data/tribes/buildings/productionsites/empire/mill/init.lua
Labels: empire, graphics

#5259 Fix misc clang-tidy checks in `ai`
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/ai_hints.cc
  src/ai/defaultai.cc
  src/ai/defaultai_seafaring.cc
  src/ai/defaultai_warfare.cc
Labels: cleanup & refactoring

#5278 results of AI training
  data/ai/ai_input_1.wai
  data/ai/ai_input_2.wai
  data/ai/ai_input_3.wai
  data/ai/ai_input_4.wai
  src/ai/ai_help_structs.cc
Labels: ai

#5258 Fix misc clang-tidy checks in `game_io`
  src/game_io/game_class_packet.cc
  src/game_io/game_loader.cc
  src/game_io/game_map_packet.cc
  src/game_io/game_player_ai_persistent_packet.cc
  src/game_io/game_player_info_packet.cc
  src/game_io/game_preload_packet.cc
  src/game_io/game_saver.cc
Labels: cleanup & refactoring

#5252 Fix misc clang-tidy checks in `map_io`
  src/map_io/map_allowed_building_types_packet.cc
  src/map_io/map_allowed_worker_types_packet.cc
  src/map_io/map_bob_packet.cc
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_elemental_packet.cc
  src/map_io/map_heights_packet.cc
  src/map_io/map_images.h
  src/map_io/map_node_ownership_packet.cc
  src/map_io/map_player_names_and_tribes_packet.cc
  src/map_io/map_player_position_packet.cc
  src/map_io/map_players_messages_packet.cc
  src/map_io/map_port_spaces_packet.cc
  src/map_io/map_scripting_packet.cc
  src/map_io/s2map.cc
Labels: cleanup & refactoring

#5248 Fix misc clang-tidy checks in `ui_fsmenu`
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/addons/screenshot_upload.cc
  src/ui_fsmenu/campaign_select.cc
  src/ui_fsmenu/campaigns.cc
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/loadgame.cc
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/menu.cc
  src/ui_fsmenu/mousewheel_options.cc
  src/ui_fsmenu/mousewheel_options.h
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/netsetup_lan.h
  src/ui_fsmenu/scenario_select.cc
  src/ui_fsmenu/singleplayersetupbox.cc
Labels: cleanup & refactoring

#5250 Fix misc clang-tidy checks in `scripting`
  src/scripting/logic.cc
  src/scripting/lua_bases.cc
  src/scripting/lua_bases.h
  src/scripting/lua_coroutine.cc
  src/scripting/lua_coroutine.h
  src/scripting/lua_game.cc
  src/scripting/lua_game.h
  src/scripting/lua_interface.h
  src/scripting/lua_map.cc
  src/scripting/lua_root.cc
  src/scripting/lua_table.cc
  src/scripting/luna_impl.cc
  src/scripting/run_script.cc
Labels: cleanup & refactoring

#5257 Fix misc clang-tidy checks in `editor`
  src/editor/editorinteractive.cc
  src/editor/map_generator.cc
  src/editor/tools/decrease_height_tool.h
  src/editor/tools/decrease_resources_tool.h
  src/editor/tools/delete_critter_tool.h
  src/editor/tools/delete_immovable_tool.cc
  src/editor/tools/delete_immovable_tool.h
  src/editor/tools/increase_height_tool.h
  src/editor/tools/increase_resources_tool.h
  src/editor/tools/noise_height_tool.h
  src/editor/tools/place_critter_tool.cc
  src/editor/tools/place_critter_tool.h
  src/editor/tools/place_immovable_tool.h
  src/editor/tools/resize_tool.cc
  src/editor/tools/resize_tool.h
  src/editor/tools/set_height_tool.h
  src/editor/tools/set_origin_tool.h
  src/editor/tools/set_port_space_tool.h
  src/editor/tools/set_resources_tool.h
  src/editor/tools/set_starting_pos_tool.cc
  src/editor/tools/set_terrain_tool.cc
  src/editor/tools/set_terrain_tool.h
  src/editor/ui_menus/field_info_window.cc
  src/editor/ui_menus/main_menu_load_map.cc
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_map_options.h
  src/editor/ui_menus/main_menu_save_map.cc
  src/editor/ui_menus/tool_set_terrain_options_menu.cc
Labels: cleanup & refactoring

#5247 Fix misc clang-tidy checks in `ui_basic`
  src/ui_basic/box.cc
  src/ui_basic/button.cc
  src/ui_basic/checkbox.cc
  src/ui_basic/color_chooser.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/editbox.cc
  src/ui_basic/fileview_panel.cc
  src/ui_basic/icongrid.cc
  src/ui_basic/icongrid.h
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
  src/ui_basic/messagebox.cc
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/scrollbar.cc
  src/ui_basic/slider.cc
  src/ui_basic/slider.h
  src/ui_basic/spinbox.cc
  src/ui_basic/table.cc
  src/ui_basic/table.h
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
  src/ui_basic/textarea.cc
  src/ui_basic/unique_window.cc
  src/ui_basic/unique_window.h
  src/ui_basic/window.cc
Labels: cleanup & refactoring

#5256 Fix misc clang-tidy checks in `economy`
  src/economy/economy.cc
  src/economy/expedition_bootstrap.cc
  src/economy/flag.cc
  src/economy/flag.h
  src/economy/idleworkersupply.cc
  src/economy/input_queue.h
  src/economy/portdock.cc
  src/economy/portdock.h
  src/economy/request.cc
  src/economy/road.cc
  src/economy/road.h
  src/economy/roadbase.cc
  src/economy/route.cc
  src/economy/ship_fleet.cc
  src/economy/shipping_schedule.cc
  src/economy/shippingitem.cc
  src/economy/shippingitem.h
  src/economy/test/test_road.cc
  src/economy/test/test_routing.cc
  src/economy/ware_instance.cc
  src/economy/wares_queue.cc
  src/economy/waterway.cc
  src/economy/workers_queue.cc
Labels: cleanup & refactoring

#5253 Fix misc clang-tidy checks in `graphic`
  src/graphic/build_texture_atlas.cc
  src/graphic/gl/blit_program.h
  src/graphic/gl/initialize.cc
  src/graphic/gl/terrain_program.h
  src/graphic/gl/utils.cc
  src/graphic/graphic.cc
  src/graphic/graphic.h
  src/graphic/minimap_renderer.cc
  src/graphic/minimap_renderer.h
  src/graphic/rendertarget.cc
  src/graphic/rendertarget.h
  src/graphic/styles/font_style.h
  src/graphic/surface.h
  src/graphic/text/font_io.h
  src/graphic/text/rt_parse.cc
  src/graphic/text/rt_parse.h
  src/graphic/text/rt_render.cc
  src/graphic/text/rt_render.h
  src/graphic/text/sdl_ttf_font.cc
  src/graphic/text/sdl_ttf_font.h
  src/graphic/text/textstream.cc
  src/graphic/text_layout.cc
  src/graphic/texture.cc
  src/graphic/texture.h
  src/graphic/texture_atlas.cc
  src/graphic/texture_atlas.h
  src/graphic/wordwrap.cc
Labels: cleanup & refactoring

#5251 Fix misc clang-tidy checks in `network`
  src/network/bufferedconnection.h
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.cc
  src/network/host_game_settings_provider.h
  src/network/internet_gaming.cc
  src/network/net_addons.cc
  src/network/net_addons.h
  src/network/netclient.cc
  src/network/nethost.cc
  src/network/network.cc
  src/network/network_lan_promotion.cc
  src/network/network_player_settings_backend.cc
  src/network/network_player_settings_backend.h
  src/network/participantlist.cc
Labels: cleanup & refactoring

#5231 Update Add-On Upload to Command Version 2
  src/network/net_addons.cc
Labels: enhancement, addon

#5249 Fix misc clang-tidy checks in `wui`
  src/wui/actionconfirm.h
  src/wui/attack_window.cc
  src/wui/building_statistics_menu.cc
  src/wui/buildingwindow.cc
  src/wui/chat_overlay.cc
  src/wui/debugconsole.cc
  src/wui/economy_options_window.cc
  src/wui/economy_options_window.h
  src/wui/encyclopedia_window.cc
  src/wui/fieldaction.cc
  src/wui/fieldaction.h
  src/wui/game_chat_panel.cc
  src/wui/game_exit_confirm_box.h
  src/wui/game_main_menu_save_game.cc
  src/wui/game_message_menu.cc
  src/wui/game_objectives_menu.cc
  src/wui/game_summary.h
  src/wui/gamedetails.cc
  src/wui/general_statistics_menu.cc
  src/wui/general_statistics_menu.h
  src/wui/info_panel.cc
  src/wui/inputqueuedisplay.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
  src/wui/interactive_spectator.cc
  src/wui/interactive_spectator.h
  src/wui/mapdata.cc
  src/wui/mapdata.h
  src/wui/mapview.cc
  src/wui/mapview.h
  src/wui/mapviewpixelfunctions.cc
  src/wui/minimap.cc
  src/wui/minimap.h
  src/wui/plot_area.cc
  src/wui/productionsitewindow.cc
  src/wui/savegamedata.h
  src/wui/savegameloader.cc
  src/wui/savegametable.cc
  src/wui/seafaring_statistics_menu.cc
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
  src/wui/soldier_statistics_menu.cc
  src/wui/soldierlist.cc
  src/wui/stock_menu.cc
  src/wui/toolbar.cc
  src/wui/ware_statistics_menu.cc
  src/wui/warehousewindow.cc
  src/wui/waresdisplay.cc
  src/wui/watchwindow.cc
  src/wui/watchwindow.h
Labels: cleanup & refactoring

#5288 Fix Description Index Misordering from UI Code
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/mapselect.h
Labels: bug, world, multiplayer & networking, ui, desync

#5289 Fix misc clang-tidy checks in remaining files
  src/scripting/lua_map.cc
  src/sound/sound_handler.cc
  src/website/json/json.cc
  src/wlapplication.cc
  src/wlapplication_mousewheel_options.cc
  src/wlapplication_options.cc
  utils/check_clang_tidy_results.py
Labels: cleanup & refactoring
