Repository widelands/widelands, pull requests merged in 2022-11, with the labels that each got.

#5634 Upscaled editor splash image
  data/templates/default/loadscreens/editor.jpg
  src/editor/editorinteractive.cc
  src/editor/ui_menus/main_menu_load_map.cc
  src/editor/ui_menus/main_menu_new_map.cc
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_save_map.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/ui_basic/progresswindow.cc
  src/ui_basic/progresswindow.h
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/random_game.cc
  src/wlapplication.cc
  src/wui/game_main_menu_save_game.cc
Labels: editor, graphics

#5629 Fix Clang15 Compiler Warnings
  src/ai/defaultai.cc
  src/ai/defaultai_warfare.cc
  src/editor/ui_menus/tool_toolhistory_options_menu.cc
  src/logic/map_objects/tribes/ship.cc
Labels: bug, codecheck, cleanup & refactoring, ai

#5640 Fix trainingsites' definition of when a soldier is present
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/trainingsite.cc
  src/logic/map_objects/tribes/trainingsite.h
Labels: bug, military

#5639 fix saving game with new name
  src/wui/game_main_menu_save_game.cc
Labels: bug, saveloading & compatibility, ui

#5642 Move empty sign on Atlantean mines to make it visible when status labels are shown
  data/tribes/buildings/productionsites/atlanteans/coalmine/empty_0.5.png
  data/tribes/buildings/productionsites/atlanteans/coalmine/empty_1.png
  data/tribes/buildings/productionsites/atlanteans/coalmine/empty_2.png
  data/tribes/buildings/productionsites/atlanteans/coalmine/empty_4.png
  data/tribes/buildings/productionsites/atlanteans/crystalmine/empty_0.5.png
  data/tribes/buildings/productionsites/atlanteans/crystalmine/empty_1.png
  data/tribes/buildings/productionsites/atlanteans/crystalmine/empty_2.png
  data/tribes/buildings/productionsites/atlanteans/crystalmine/empty_4.png
  data/tribes/buildings/productionsites/atlanteans/goldmine/empty_0.5.png
  data/tribes/buildings/productionsites/atlanteans/goldmine/empty_1.png
  data/tribes/buildings/productionsites/atlanteans/goldmine/empty_2.png
  data/tribes/buildings/productionsites/atlanteans/goldmine/empty_4.png
  data/tribes/buildings/productionsites/atlanteans/ironmine/empty_0.5.png
  data/tribes/buildings/productionsites/atlanteans/ironmine/empty_1.png
  data/tribes/buildings/productionsites/atlanteans/ironmine/empty_2.png
  data/tribes/buildings/productionsites/atlanteans/ironmine/empty_4.png
Labels: tribes, accessibility, graphics, atlanteans, media

#5604 Prevent spectating host from changing game speed
  src/game_io/game_player_info_packet.cc
  src/logic/playercommand.cc
  src/logic/playersmanager.cc
  src/logic/playersmanager.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/scripting/lua_game.cc
  src/wui/game_diplomacy_menu.cc
  src/wui/game_summary.cc
Labels: multiplayer & networking

#5607 Worker and Soldier Statistics Tweaks
  data/images/wui/stats/genstats_civil_blds_defeated.png
  data/templates/default/init.lua
  src/logic/game.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/map_objects/tribes/soldier.h
  src/logic/player.cc
  src/logic/player.h
  src/wui/general_statistics_menu.cc
  src/wui/soldier_statistics_menu.cc
Labels: bug, enhancement, statistics

#5665 Cancel battles when players negotiate truce
  src/logic/map_objects/tribes/soldier.cc
Labels: bug, military

#5670 Redesign Diplomacy Accept/Reject/Retract UI
  src/logic/game.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/widelands.h
  src/wui/actionconfirm.cc
  src/wui/actionconfirm.h
  src/wui/game_diplomacy_menu.cc
  src/wui/game_diplomacy_menu.h
  src/wui/interactive_player.cc
Labels: enhancement, balancing & gameplay, ui
