Repository widelands/widelands, pull requests merged in 2022-12, with the labels that each got.

#5672 Switch to C++17
  .github/workflows/build.yaml
  CMakeLists.txt
  README.md
  utils/check_clang_tidy_results.py
Labels: building & packaging

#5599 Show enabled game-relevant add-ons before hosting
  src/logic/CMakeLists.txt
  src/logic/addons.cc
  src/logic/addons.h
  src/network/gamehost.cc
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/netsetup_lan.cc
Labels: multiplayer & networking, ui, addon

#5487 Quick Navigation GUI
  data/images/wui/menus/quicknav.png
  data/images/wui/menus/quicknav_set.png
  src/game_io/game_interactive_player_packet.cc
  src/notifications/note_ids.h
  src/ui_basic/panel.h
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/CMakeLists.txt
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/quicknavigation.cc
  src/wui/quicknavigation.h
Labels: enhancement, ui

#5671 Show chat with customized player colours
  src/chat/chat.h
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/launch_mpg.cc
  src/wui/chat_msg_layout.cc
  src/wui/chat_msg_layout.h
  src/wui/chat_overlay.cc
  src/wui/chat_overlay.h
  src/wui/game_chat_menu.cc
  src/wui/game_chat_menu.h
  src/wui/game_chat_panel.cc
  src/wui/game_chat_panel.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
Labels: bug, graphics, chat

#5682 Update clang-tidy CI version
  .github/scripts/install_deps.sh
  utils/check_clang_tidy_results.py
Labels: building & packaging

#5689 Clear clang-tidy in game_io headers
  src/game_io/game_data_packet.h
  src/game_io/game_map_packet.h
Labels: cleanup & refactoring

#5696 Clear clang-tidy in sound headers
  src/sound/songset.cc
  src/sound/songset.h
  src/sound/sound_handler.cc
  src/sound/sound_handler.h
Labels: cleanup & refactoring

#5684 Clear clang-tidy in ai headers
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/ai_hints.h
  src/ai/computer_player.h
  src/ai/defaultai.cc
  src/ai/defaultai.h
Labels: cleanup & refactoring

#5695 Clear clang-tidy in scripting headers
  src/scripting/factory.h
  src/scripting/lua_bases.h
  src/scripting/lua_coroutine.cc
  src/scripting/lua_coroutine.h
  src/scripting/lua_editor.h
  src/scripting/lua_game.h
  src/scripting/lua_map.h
  src/scripting/lua_path.cc
  src/scripting/lua_root.h
  src/scripting/lua_table.cc
  src/scripting/lua_table.h
  src/scripting/lua_ui.h
  src/scripting/luna.h
  src/scripting/luna_impl.h
Labels: cleanup & refactoring

#5693 Clear clang-tidy in map_io headers
  src/map_io/map_elemental_packet.h
  src/map_io/map_loader.h
  src/map_io/map_object_loader.h
  src/map_io/map_object_saver.cc
  src/map_io/map_object_saver.h
  src/map_io/map_saver.cc
  src/map_io/map_saver.h
  src/map_io/s2map.cc
  src/map_io/s2map.h
Labels: cleanup & refactoring

#5690 Clear clang-tidy in io headers
  src/io/fileread.cc
  src/io/fileread.h
  src/io/filesystem/filesystem.cc
  src/io/filesystem/filesystem.h
  src/io/filesystem/zip_filesystem.cc
  src/io/filesystem/zip_filesystem.h
  src/io/filewrite.cc
  src/io/filewrite.h
  src/io/profile.h
  src/io/streamread.h
  src/io/streamwrite.h
Labels: cleanup & refactoring

#5694 Clear clang-tidy in notifications headers
  src/notifications/notifications.cc
  src/notifications/notifications_impl.h
Labels: cleanup & refactoring

#5692 Clear clang-tidy in network headers
  src/network/bufferedconnection.cc
  src/network/bufferedconnection.h
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.h
  src/network/internet_gaming.cc
  src/network/internet_gaming.h
  src/network/net_addons.cc
  src/network/net_addons.h
  src/network/netclient_interface.h
  src/network/nethost.cc
  src/network/nethost.h
  src/network/nethost_interface.h
  src/network/nethostproxy.h
  src/network/network.h
  src/network/network_lan_promotion.cc
  src/network/network_lan_promotion.h
Labels: cleanup & refactoring

#5685 Clear clang-tidy in base headers
  src/base/format/abstract_node.h
  src/base/format/common_nodes.h
  src/base/format/float_node.h
  src/base/format/string_node.h
  src/base/format/tree.cc
  src/base/format/tree.h
  src/base/format/write_number.h
  src/base/math.cc
  src/base/math.h
  src/base/md5.h
  src/base/multithreading.h
  src/base/random.cc
  src/base/random.h
  src/base/string.h
  src/base/test.h
  src/base/times.h
  src/base/utf8.h
  src/base/vector.h
  src/base/warning.h
  src/base/wexception.h
Labels: cleanup & refactoring

#5688 Clear clang-tidy in graphic headers
  src/graphic/animation/animation.cc
  src/graphic/animation/animation.h
  src/graphic/animation/diranimations.h
  src/graphic/animation/spritesheet_animation.cc
  src/graphic/animation/spritesheet_animation.h
  src/graphic/build_texture_atlas.h
  src/graphic/color.h
  src/graphic/font_handler.h
  src/graphic/game_renderer.h
  src/graphic/gl/blit_program.h
  src/graphic/gl/fields_to_draw.h
  src/graphic/gl/road_program.h
  src/graphic/gl/utils.cc
  src/graphic/gl/utils.h
  src/graphic/image.h
  src/graphic/minimap_renderer.h
  src/graphic/render_queue.cc
  src/graphic/render_queue.h
  src/graphic/rendertarget.h
  src/graphic/screen.h
  src/graphic/styles/building_statistics_style.h
  src/graphic/styles/button_style.h
  src/graphic/styles/font_style.h
  src/graphic/styles/progress_bar_style.h
  src/graphic/styles/statistics_plot_style.h
  src/graphic/styles/table_style.h
  src/graphic/styles/text_panel_style.h
  src/graphic/styles/ware_info_style.h
  src/graphic/surface.h
  src/graphic/text/rendered_text.cc
  src/graphic/text/rendered_text.h
  src/graphic/text/rt_errors.h
  src/graphic/text/rt_parse.h
  src/graphic/text/rt_render.cc
  src/graphic/text/sdl_ttf_font.cc
  src/graphic/text/sdl_ttf_font.h
  src/graphic/text/textstream.h
  src/graphic/text/transient_cache.h
  src/graphic/texture.h
  src/graphic/texture_atlas.cc
  src/graphic/texture_atlas.h
  src/graphic/wordwrap.cc
  src/graphic/wordwrap.h
Labels: cleanup & refactoring

#5698 Clear clang-tidy in ui_fsmenu headers
  src/ui_fsmenu/about.h
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager.h
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/addons/packager_box.h
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
  src/ui_fsmenu/addons/rows_ui.h
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/internet_lobby.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.h
  src/ui_fsmenu/launch_spg.h
  src/ui_fsmenu/loadgame.cc
  src/ui_fsmenu/loadgame.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/mapselect.h
  src/ui_fsmenu/menu.cc
  src/ui_fsmenu/menu.h
  src/ui_fsmenu/mousewheel_options.h
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/random_game.h
  src/ui_fsmenu/singleplayerdropdown.h
  src/ui_fsmenu/singleplayersetupbox.h
Labels: cleanup & refactoring

#5697 Clear clang-tidy in ui_basic headers
  src/ui_basic/box.cc
  src/ui_basic/box.h
  src/ui_basic/button.h
  src/ui_basic/checkbox.h
  src/ui_basic/color_chooser.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/dropdown.h
  src/ui_basic/editbox.cc
  src/ui_basic/editbox.h
  src/ui_basic/fileview_panel.cc
  src/ui_basic/fileview_panel.h
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/multilinetextarea.cc
  src/ui_basic/multilinetextarea.h
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/progressbar.cc
  src/ui_basic/progressbar.h
  src/ui_basic/progresswindow.h
  src/ui_basic/scrollbar.cc
  src/ui_basic/scrollbar.h
  src/ui_basic/slider.cc
  src/ui_basic/slider.h
  src/ui_basic/table.cc
  src/ui_basic/table.h
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
  src/ui_basic/text_prompt.h
  src/ui_basic/textarea.h
  src/ui_basic/unique_window.h
  src/ui_basic/window.cc
  src/ui_basic/window.h
Labels: cleanup & refactoring

#5686 Clear clang-tidy in editor headers
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/editor/map_generator.cc
  src/editor/map_generator.h
  src/editor/tools/action_args.h
  src/editor/tools/decrease_height_tool.h
  src/editor/tools/decrease_resources_tool.h
  src/editor/tools/delete_critter_tool.h
  src/editor/tools/delete_immovable_tool.h
  src/editor/tools/draw_tool.h
  src/editor/tools/history.cc
  src/editor/tools/increase_height_tool.h
  src/editor/tools/increase_resources_tool.h
  src/editor/tools/info_tool.h
  src/editor/tools/multi_select.h
  src/editor/tools/resize_tool.h
  src/editor/tools/set_height_tool.h
  src/editor/tools/set_origin_tool.h
  src/editor/tools/set_resources_tool.h
  src/editor/tools/set_terrain_tool.h
  src/editor/tools/tool.h
  src/editor/tools/tool_action.h
  src/editor/tools/tool_conf.cc
  src/editor/tools/tool_conf.h
  src/editor/tools/toolhistory_tool.h
  src/editor/ui_menus/categorized_item_selection_menu.h
  src/editor/ui_menus/help.h
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/editor/ui_menus/main_menu_load_or_save_map.h
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_map_options.h
  src/editor/ui_menus/main_menu_new_map.cc
  src/editor/ui_menus/main_menu_new_map.h
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_random_map.h
  src/editor/ui_menus/main_menu_save_map_make_directory.cc
  src/editor/ui_menus/main_menu_save_map_make_directory.h
  src/editor/ui_menus/tool_options_menu.h
  src/editor/ui_menus/tool_place_critter_options_menu.h
  src/editor/ui_menus/tool_toolhistory_options_menu.cc
  src/editor/ui_menus/tool_toolhistory_options_menu.h
  src/editor/ui_menus/toolsize_menu.cc
  src/editor/ui_menus/toolsize_menu.h
Labels: cleanup & refactoring

#5537 Map Generator Add-Ons & Map Generating Dialog Accessibility Tweaks
  data/images/wui/editor/menus/map_options.png
  data/images/wui/editor/menus/new_random_map.png
  doc/sphinx/source/add-ons.rst
  src/editor/map_generator.cc
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_random_map.h
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
  src/ui_fsmenu/random_game.cc
Labels: enhancement, accessibility, addon, random map

#5704 Editor: Show Starting Positions on Minimap
  src/graphic/minimap_renderer.cc
  src/wui/interactive_base.cc
  src/wui/minimap.cc
  src/wui/minimap.h
Labels: enhancement, editor, ui

#4961 Allow letting individual productionsites produce indefinitely
  data/campaigns/tutorial04_economy.wmf/scripting/mission_thread.lua
  data/campaigns/tutorial04_economy.wmf/scripting/texts.lua
  data/images/wui/menus/end_infinity.png
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/production_program.h
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/map_io/map_buildingdata_packet.cc
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
Labels: enhancement, tribes, balancing & gameplay, economy

#5681 Create .clang-tidy config file and sanitize headers
  .clang-tidy
  .github/workflows/build.yaml
  .gitignore
  src/base/test.h
  src/editor/ui_menus/main_menu_random_map.h
  src/game_io/game_player_ai_persistent_packet.cc
  src/logic/map_objects/bob.h
  src/logic/map_objects/map_object.h
  src/logic/map_objects/tribes/soldiercontrol.h
  src/logic/player.cc
  src/logic/player.h
  src/network/network.h
  src/ui_basic/dropdown.h
  src/wlapplication.cc
  src/wlapplication.h
  src/wlapplication_options.h
  utils/check_clang_tidy_results.py
Labels: codecheck, cleanup & refactoring

#5708 Fix segfault in multiselect editor tools
  src/editor/tools/multi_select.h
Labels: bug, crashes or hangs, editor, regression

#5705 Add shortcut keys for all menu items
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/editor/ui_menus/main_menu_new_map.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_spectator.cc
  src/wui/seafaring_statistics_menu.cc
Labels: enhancement, accessibility, ui

#5710 Misc String Fixes
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/campaigns/tutorial03_seafaring.wmf/scripting/texts.lua
  data/maps/SP_Scenarios/Along_The_River.wmf/scripting/texts.lua
  data/scripting/training_wheels/objectives.lua
  data/scripting/win_conditions/collectors.lua
  data/txts/tips/general_game.lua
  src/ui_fsmenu/addons/manager.cc
Labels: internationalization

#5557 Show flags preview in road building mode when Ctrl is held
  src/wui/fieldaction.cc
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_player.cc
Labels: enhancement, tribes, accessibility

#5645 Replays: Single-File, Optional Writing, Autodeleting
  src/logic/filesystem_constants.h
  src/logic/game_controller.h
  src/logic/replay.cc
  src/logic/replay.h
  src/logic/replay_game_controller.h
  src/logic/single_player_game_controller.h
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/ui_basic/spinbox.cc
  src/ui_basic/spinbox.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_mpg.h
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication.cc
  src/wlapplication_messages.cc
  src/wui/gamedetails.cc
  src/wui/savegameloader.cc
  src/wui/savegameloader.h
Labels: enhancement, saveloading & compatibility, replay

#5703 Naming Warehouses and Ships
  data/campaigns/emp01.wmf/scripting/mission_thread.lua
  data/campaigns/emp01.wmf/scripting/starting_conditions.lua
  data/campaigns/emp03.wmf/scripting/mission_thread.lua
  data/campaigns/emp03.wmf/scripting/starting_conditions.lua
  data/campaigns/emp04.wmf/scripting/starting_conditions.lua
  data/campaigns/fri01.wmf/scripting/starting_conditions.lua
  data/tribes/initialization/amazons/units.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  data/tribes/ships/amazons/init.lua
  data/tribes/ships/atlanteans/init.lua
  data/tribes/ships/barbarians/init.lua
  data/tribes/ships/empire/init.lua
  src/economy/expedition_bootstrap.cc
  src/economy/portdock.cc
  src/economy/shipping_schedule.cc
  src/game_io/game_player_info_packet.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/warehouse.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_packet_versions.h
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
  src/wui/warehousewindow.cc
  src/wui/warehousewindow.h
Labels: enhancement, seafaring

#5714 Redesigned Amazon frontiers and flags with more visible playercolour
  data/tribes/initialization/amazons/images/flag_0.5.png
  data/tribes/initialization/amazons/images/flag_0.5_pc.png
  data/tribes/initialization/amazons/images/flag_1.png
  data/tribes/initialization/amazons/images/flag_1_pc.png
  data/tribes/initialization/amazons/images/flag_2.png
  data/tribes/initialization/amazons/images/flag_2_pc.png
  data/tribes/initialization/amazons/images/flag_4.png
  data/tribes/initialization/amazons/images/flag_4_pc.png
  data/tribes/initialization/amazons/images/frontier_0.5.png
  data/tribes/initialization/amazons/images/frontier_0.5_pc.png
  data/tribes/initialization/amazons/images/frontier_1.png
  data/tribes/initialization/amazons/images/frontier_1_pc.png
  data/tribes/initialization/amazons/images/frontier_2.png
  data/tribes/initialization/amazons/images/frontier_2_pc.png
  data/tribes/initialization/amazons/images/frontier_4.png
  data/tribes/initialization/amazons/images/frontier_4_pc.png
  data/tribes/initialization/amazons/units.lua
Labels: graphics, amazons

#5726 Fix SoldierList off-by-one buffer overflow
  src/wui/soldierlist.cc
Labels: bug, crashes or hangs, military, ui

#5731 Trigger `closed` signal when closing unique window
  src/ui_basic/unique_window.cc
Labels: bug, ui
