Repository widelands/widelands, pull requests merged in 2022-03, with the labels that each got.

#5282 Refactoring of construct_building
  src/ai/defaultai.cc
  src/ai/defaultai.h
Labels: ai

#5266 Fix Add-Ons Admin Menu Visibility
  src/ui_fsmenu/addons/remote_interaction.cc
Labels: bug, ui, addon

#5286 Refactor Add-Ons Postloading
  src/game_io/game_class_packet.cc
  src/game_io/game_loader.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/description_manager.cc
  src/logic/map_objects/description_manager.h
  src/logic/map_objects/descriptions.cc
  src/logic/map_objects/descriptions.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/launch_spg.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/mapselect.h
  src/ui_fsmenu/random_game.cc
  src/ui_fsmenu/random_game.h
Labels: crashes or hangs, saveloading & compatibility, addon

#5317 Clear readability-implicit-bool-conversion in base
  src/base/format/tree.cc
  src/base/i18n.cc
  src/base/multithreading.cc
  src/base/string.cc
Labels: cleanup & refactoring

#5318 Clear readability-implicit-bool-conversion in website
  src/website/create_spritesheet.cc
  src/website/lua/lua_tree.cc
  src/website/map_object_info.cc
  src/website/website_common.cc
Labels: cleanup & refactoring

#5314 Clear readability-implicit-bool-conversion in editor
  src/editor/editorinteractive.cc
  src/editor/map_generator.cc
  src/editor/tools/increase_resources_tool.cc
  src/editor/tools/place_critter_tool.cc
  src/editor/tools/place_immovable_tool.cc
  src/editor/tools/set_port_space_tool.cc
  src/editor/tools/set_starting_pos_tool.cc
  src/editor/tools/set_terrain_tool.cc
  src/editor/ui_menus/field_info_window.cc
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_save_map.cc
Labels: cleanup & refactoring

#5323 Fix tribes postloading again and add regression test
  src/editor/editorinteractive.cc
  src/game_io/game_class_packet.cc
  src/logic/editor_game_base.cc
  src/logic/editor_game_base.h
  src/logic/game.cc
  src/logic/replay.cc
  src/ui_fsmenu/keyboard_options.cc
  test/maps/plain.wmf/scripting/test_tribes_postloading_works.lua
Labels: bug, tribes, testing

#5307 Clear readability-implicit-bool-conversion in scripting
  src/scripting/factory.cc
  src/scripting/globals.cc
  src/scripting/logic.cc
  src/scripting/lua.cc
  src/scripting/lua_bases.cc
  src/scripting/lua_coroutine.cc
  src/scripting/lua_game.cc
  src/scripting/lua_globals.cc
  src/scripting/lua_map.cc
  src/scripting/lua_path.cc
  src/scripting/lua_root.cc
  src/scripting/lua_table.cc
  src/scripting/lua_ui.cc
  src/scripting/persistence.cc
  src/scripting/run_script.cc
Labels: cleanup & refactoring

#5311 Clear readability-implicit-bool-conversion in io
  src/io/fileread.cc
  src/io/filesystem/disk_filesystem.cc
  src/io/filesystem/filesystem.cc
  src/io/filesystem/zip_filesystem.cc
  src/io/profile.cc
Labels: cleanup & refactoring

#5313 Clear readability-implicit-bool-conversion in game_io
  src/game_io/game_class_packet.cc
  src/game_io/game_cmd_queue_packet.cc
  src/game_io/game_interactive_player_packet.cc
  src/game_io/game_player_ai_persistent_packet.cc
  src/game_io/game_player_economies_packet.cc
  src/game_io/game_player_info_packet.cc
  src/game_io/game_preload_packet.cc
Labels: cleanup & refactoring

#5316 Clear readability-implicit-bool-conversion in ai
  src/ai/ai_help_structs.cc
  src/ai/ai_help_structs.h
  src/ai/defaultai.cc
  src/ai/defaultai_seafaring.cc
  src/ai/defaultai_warfare.cc
Labels: cleanup & refactoring

#5304 Clear readability-implicit-bool-conversion in wui
  src/wui/actionconfirm.cc
  src/wui/attack_window.cc
  src/wui/building_statistics_menu.cc
  src/wui/building_statistics_menu.h
  src/wui/buildingwindow.cc
  src/wui/chat_msg_layout.cc
  src/wui/constructionsitewindow.cc
  src/wui/economy_options_window.cc
  src/wui/encyclopedia_window.cc
  src/wui/fieldaction.cc
  src/wui/game_chat_panel.cc
  src/wui/game_client_disconnected.cc
  src/wui/game_debug_ui.cc
  src/wui/game_message_menu.cc
  src/wui/game_summary.cc
  src/wui/gamedetails.cc
  src/wui/general_statistics_menu.cc
  src/wui/info_panel.cc
  src/wui/inputqueuedisplay.cc
  src/wui/interactive_base.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_player.cc
  src/wui/interactive_spectator.cc
  src/wui/itemwaresdisplay.cc
  src/wui/load_or_save_game.cc
  src/wui/mapdata.cc
  src/wui/mapdetails.cc
  src/wui/mapview.cc
  src/wui/mapviewpixelfunctions.cc
  src/wui/minimap.cc
  src/wui/plot_area.cc
  src/wui/portdockwaresdisplay.cc
  src/wui/productionsitewindow.cc
  src/wui/savegamedeleter.cc
  src/wui/savegameloader.cc
  src/wui/seafaring_statistics_menu.cc
  src/wui/shipwindow.cc
  src/wui/soldier_statistics_menu.cc
  src/wui/soldiercapacitycontrol.cc
  src/wui/soldierlist.cc
  src/wui/stock_menu.cc
  src/wui/ware_statistics_menu.cc
  src/wui/waresdisplay.cc
  src/wui/watchwindow.cc
Labels: cleanup & refactoring

#5306 Clear readability-implicit-bool-conversion in ui_basic
  src/ui_basic/box.cc
  src/ui_basic/button.cc
  src/ui_basic/checkbox.cc
  src/ui_basic/color_chooser.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/editbox.cc
  src/ui_basic/icon.cc
  src/ui_basic/listselect.cc
  src/ui_basic/messagebox.cc
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/panel.cc
  src/ui_basic/progresswindow.cc
  src/ui_basic/radiobutton.cc
  src/ui_basic/scrollbar.cc
  src/ui_basic/spinbox.cc
  src/ui_basic/table.cc
  src/ui_basic/tabpanel.cc
  src/ui_basic/textarea.cc
  src/ui_basic/unique_window.cc
  src/ui_basic/window.cc
Labels: cleanup & refactoring

#5312 Clear readability-implicit-bool-conversion in graphic
  src/graphic/animation/animation_manager.cc
  src/graphic/animation/nonpacked_animation.cc
  src/graphic/animation/spritesheet_animation.cc
  src/graphic/build_texture_atlas.cc
  src/graphic/gl/dither_program.cc
  src/graphic/gl/terrain_program.cc
  src/graphic/gl/utils.cc
  src/graphic/gl/workarea_program.cc
  src/graphic/graphic.cc
  src/graphic/graphic_functions.cc
  src/graphic/image_cache.cc
  src/graphic/image_io.cc
  src/graphic/minimap_renderer.cc
  src/graphic/rendertarget.cc
  src/graphic/surface.cc
  src/graphic/text/bidi.cc
  src/graphic/text/font_io.cc
  src/graphic/text/font_set.cc
  src/graphic/text/rt_parse.cc
  src/graphic/text/rt_render.cc
  src/graphic/text/sdl_ttf_font.cc
  src/graphic/text/textstream.cc
  src/graphic/texture.cc
  src/graphic/texture_atlas.cc
Labels: cleanup & refactoring

#5309 Clear readability-implicit-bool-conversion in map_io
  src/map_io/coords_profile.cc
  src/map_io/map_allowed_building_types_packet.cc
  src/map_io/map_building_packet.cc
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_flag_packet.cc
  src/map_io/map_flagdata_packet.cc
  src/map_io/map_images.cc
  src/map_io/map_object_saver.cc
  src/map_io/map_objective_packet.cc
  src/map_io/map_player_names_and_tribes_packet.cc
  src/map_io/map_players_messages_packet.cc
  src/map_io/map_players_view_packet.cc
  src/map_io/map_port_spaces_packet.cc
  src/map_io/map_roaddata_packet.cc
  src/map_io/map_saver.cc
  src/map_io/map_scripting_packet.cc
  src/map_io/map_waterwaydata_packet.cc
  src/map_io/s2map.cc
  src/map_io/widelands_map_loader.cc
Labels: cleanup & refactoring
