Repository widelands/widelands, pull requests merged in 2023-07, with the labels that each got.

#5864 Editor Tool Random Gap
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/editor/tools/action_args.h
  src/editor/tools/decrease_height_tool.cc
  src/editor/tools/decrease_resources_tool.cc
  src/editor/tools/delete_critter_tool.cc
  src/editor/tools/delete_immovable_tool.cc
  src/editor/tools/history.cc
  src/editor/tools/increase_height_tool.cc
  src/editor/tools/increase_resources_tool.cc
  src/editor/tools/noise_height_tool.cc
  src/editor/tools/place_critter_tool.cc
  src/editor/tools/place_immovable_tool.cc
  src/editor/tools/set_height_tool.cc
  src/editor/tools/set_port_space_tool.cc
  src/editor/tools/set_resources_tool.cc
  src/editor/tools/set_terrain_tool.cc
  src/editor/ui_menus/toolsize_menu.cc
  src/editor/ui_menus/toolsize_menu.h
  src/logic/map.cc
  src/logic/map.h
  src/logic/widelands_geometry.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mousewheel_options.cc
  src/ui_fsmenu/mousewheel_options.h
  src/wlapplication_mousewheel_options.cc
  src/wlapplication_mousewheel_options.h
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/interactive_base.h
Labels: enhancement, editor

#5968 Do not try to refresh inexistent soldier capacity box in warehouse construction site
  src/wui/constructionsitewindow.cc
Labels: bug, crashes or hangs, military, urgent

#5966 Fix wild pointer dereference during ship removal
  src/economy/ship_fleet.cc
Labels: bug, crashes or hangs, seafaring, regression

#5976 Make Game::random_location() safer
  src/logic/game.h
Labels: bug, crashes or hangs

#5974 Don't detect portspace under own port
  src/logic/map_objects/tribes/ship.cc
Labels: bug, seafaring

#5972 Fail safely when ship destination dock is unreachable
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: bug, crashes or hangs, seafaring

#5977 Push vcpkg ref only to main repo
  .github/workflows/check_vcpkg.yaml
Labels: building & packaging

#5982 Fix Segfault in `FieldActionWindow`
  src/wui/fieldaction.cc
Labels: bug, crashes or hangs, ui

#5983 Save and load garrison settings
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_packet_versions.h
Labels: bug, saveloading & compatibility, military

#5989 Fix soldier request deletion when ship is destroyed
  src/logic/map_objects/tribes/ship.cc
  src/map_io/map_buildingdata_packet.cc
Labels: bug, saveloading & compatibility, seafaring, urgent

#5952 win condition wood_gnome can have several winners
  data/scripting/win_conditions/wood_gnome.lua
  data/txts/developers.json
Labels: wincondition

#5964 count trees for start conditions like poor_hamlet
  data/scripting/infrastructure.lua
Labels: wincondition

#5999 Fix Transifex String Issues
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
  data/tribes/initialization/empire/units.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/map_objects/tribes/productionsite.cc
Labels: internationalization

#6000 Clean up legacy resource handling code
  src/editor/editorinteractive.cc
  src/logic/field.h
  src/logic/map_objects/world/resource_description.cc
  src/logic/map_objects/world/resource_description.h
  src/logic/player.h
  src/map_io/map_players_view_packet.cc
  src/wui/game_debug_ui.cc
Labels: world, cleanup & refactoring, editor, memory & performance

#6002 Select info tool after opening history window
  src/editor/editorinteractive.cc
Labels: editor, ui

#6004 Cleanup failed game object before entering menu
  src/wlapplication.cc
Labels: saveloading & compatibility

#6007 Set fixed msvc toolset version
  .github/workflows/build.yaml
Labels: building & packaging, windows

#6003 Follow links in building help window
  src/ui_basic/panel.cc
  src/wui/encyclopedia_window.cc
  src/wui/helpwindow.cc
  src/wui/helpwindow.h
Labels: help, ui

#6010 Forbid spectators setting ship destination
  src/wui/shipwindow.cc
Labels: bug, seafaring, regression, desync

#5975 Misc API Enhancements
  src/logic/map_objects/tribes/worker_descr.h
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
  src/scripting/lua_root.cc
  src/website/map_info.cc
  test/maps/plain.wmf/scripting/test_casern.lua
Labels: enhancement, maps, lua

#6021 Resolve compiler warnings
  .github/workflows/build.yaml
  CMakeLists.txt
  src/scripting/lua_map.cc
  src/wlapplication.cc
Labels: codecheck

#5933 Lua UI API Extensions
  src/scripting/lua_ui.cc
  src/scripting/lua_ui.h
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/progressbar.h
  src/ui_basic/radiobutton.cc
  src/ui_basic/radiobutton.h
Labels: enhancement, lua, ui, addon

#6029 5880 less ci noise
  src/scripting/lua_root.cc
Labels: building & packaging

#6006 Forbid soldiers boarding ships on high sea
  src/logic/map_objects/tribes/ship.cc
Labels: bug, seafaring, urgent

#6012 Show error message immediately when host leaves metaserver game
  src/network/gameclient.cc
Labels: bug, multiplayer & networking, urgent

#6016 Remove hardcoded panel sizes in launch game window
  src/ui_basic/box.cc
  src/ui_basic/box.h
  src/ui_basic/multilinetextarea.cc
  src/ui_basic/multilinetextarea.h
  src/ui_basic/spinbox.cc
  src/ui_basic/spinbox.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/mapdetailsbox.cc
  src/ui_fsmenu/mapdetailsbox.h
  src/ui_fsmenu/menu.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/multiplayersetupgroup.h
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
  src/wui/mapdetails.cc
Labels: ui

#6032 Do not hide Add-On comment text during layout
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
Labels: ui, addon

#6011 Free Unsent PlayerCommands on Cleanup
  src/logic/game.cc
  src/logic/game.h
Labels: bug, memory & performance

#6033 Fix false positives in add-ons packager change detection
  src/ui_fsmenu/addons/packager.cc
Labels: bug, ui, regression, addon

#6018 Update expedition swimmable directions on every field
  src/logic/map_objects/bob.cc
  src/logic/map_objects/bob.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/ui_basic/dropdown.cc
Labels: bug, seafaring, urgent

#6039 Fix cornercase hang in ship healthbar drawing calculation
  src/logic/map_objects/tribes/ship.cc
Labels: bug, crashes or hangs, seafaring, graphics

#6044 Warship soldier capacity setting enhancements
  src/logic/map_objects/tribes/ship.cc
  src/wui/shipwindow.cc
  src/wui/soldierlist.cc
Labels: enhancement, military, seafaring, ui

#6045 Reroute ships on the way to port-under-construction upon port completion
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/player.cc
  src/logic/player.h
Labels: bug, crashes or hangs, seafaring

#6035 Do not layout invisible box items
  src/ui_basic/box.cc
  src/ui_basic/box.h
  src/ui_basic/spinbox.cc
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/multiplayersetupgroup.h
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
Labels: ui
