Repository widelands/widelands, pull requests merged in 2023-09, with the labels that each got.

#6135 Fix some segfaults related to `Map::calc_distance`
  src/logic/map.cc
  src/logic/map.h
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/soldier.cc
Labels: bug, crashes or hangs, cleanup & refactoring

#6088 Warships don't detect own ports as portspaces
  src/ai/defaultai_seafaring.cc
  src/game_io/game_interactive_player_packet.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/scripting/lua_map.cc
  src/wui/attack_window.cc
  src/wui/attack_window.h
  src/wui/fieldaction.cc
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
  src/wui/shipwindow.cc
Labels: bug, seafaring, graphics

#6124 Allow saving favourite colours in colour chooser
  src/ui_basic/CMakeLists.txt
  src/ui_basic/color_chooser.cc
  src/ui_basic/color_chooser.h
  src/wlapplication.cc
Labels: enhancement, accessibility

#6136 More consistent worker eviction
  src/economy/request.cc
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/worker.cc
Labels: bug, tribes, balancing & gameplay, regression

#6127 Game Chat Accessibility Tweaks
  src/wui/chat_overlay.cc
  src/wui/game_chat_menu.cc
Labels: accessibility, chat

#6128 Remember more settings in stock/unique window
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_map_options.h
  src/ui_basic/unique_window.cc
  src/ui_basic/unique_window.h
  src/wui/interactive_gamebase.h
  src/wui/stock_menu.cc
  src/wui/stock_menu.h
Labels: accessibility

#6129 Further enhancements for ship construction
  src/logic/map_objects/findimmovable.cc
  src/logic/map_objects/findimmovable.h
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/immovable.h
  src/logic/map_objects/immovable_program.cc
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/worker.cc
  src/wui/interactive_gamebase.cc
Labels: bug, enhancement, tribes, seafaring, ui

#6140 Guard against invalid ship battle situations
  src/logic/map_objects/tribes/ship.cc
Labels: bug, seafaring, urgent

#6122 Track warship soldier requests
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: bug, military, seafaring, economy, urgent

#6082 Fix selection cursor setting after picking custom starting position
  src/ai/defaultai.cc
  src/game_io/game_player_info_packet.cc
  src/logic/player.cc
  src/logic/player.h
  src/wui/interactive_player.cc
Labels: bug, cleanup & refactoring, accessibility, graphics, urgent

#6132 Sanitize network game player names more thoroughly
  src/network/gamehost.cc
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/netsetup_lan.h
Labels: bug, multiplayer & networking

#6142 Misc sea-fighting-related UI tweaks
  src/graphic/gl/utils.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/ui_basic/dropdown.h
  src/wui/attack_window.cc
  src/wui/attack_window.h
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
  src/wui/soldiercapacitycontrol.cc
  src/wui/soldierlist.cc
Labels: bug, seafaring, ui, urgent

#6139 Deadlock-related improvements
  src/base/multithreading.cc
  src/base/mutex.h
  src/ui_basic/panel.cc
  src/wui/game_main_menu_save_game.cc
Labels: bug, crashes or hangs, cleanup & refactoring, urgent, multithreading

#6143 Bigger menu.png for Amazon ship
  data/tribes/ships/amazons/menu.png
Labels: seafaring, graphics, amazons

#6147 Update msvc toolset version
  .github/workflows/build.yaml
Labels: building & packaging, ftbfs, windows

#6148 Different overlay image for valid start positions
  src/wui/interactive_player.cc
Labels: enhancement, accessibility, graphics, ui, urgent

#6144 Refactor WaresDisplay ware list handling
  src/wui/constructionsitewindow.cc
  src/wui/constructionsitewindow.h
  src/wui/stock_menu.cc
  src/wui/stock_menu.h
  src/wui/warehousewindow.cc
  src/wui/waresdisplay.cc
  src/wui/waresdisplay.h
Labels: bug, crashes or hangs, cleanup & refactoring, ui, urgent, multithreading

#6152 Revert and replace #6082, only use intermediate state for local player
  src/ai/defaultai.cc
  src/game_io/game_player_info_packet.cc
  src/logic/player.cc
  src/logic/player.h
  src/wui/interactive_player.cc
Labels: bug, regression, desync
