Repository widelands/widelands, pull requests merged in 2023-05, with the labels that each got.

#5884 Map Required WL Version Check
  src/editor/editorinteractive.cc
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/map_revision.h
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager.h
  src/wui/mapdata.cc
  src/wui/mapdata.h
  src/wui/mapdetails.cc
Labels: bug, maps, saveloading & compatibility, addon

#5887 Naval Warfare: Better Invasion End Detection
  src/logic/map_objects/findimmovable.cc
  src/logic/map_objects/findimmovable.h
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/worker.cc
Labels: enhancement, military, seafaring

#5897 Fix modality and threading issues around `StoryMessageBox`
  src/base/multithreading.cc
  src/scripting/lua_game.cc
  src/ui_basic/panel.cc
  src/wui/story_message_box.cc
  src/wui/story_message_box.h
Labels: bug, crashes or hangs, ui, multithreading

#5873 More Editbox Accessibility
  src/ui_basic/editbox.cc
  src/ui_basic/editbox.h
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/multilineeditbox.h
Labels: enhancement, accessibility

#5903 Fix Compilation With GCC 13.1 And AppleClang
  CMakeLists.txt
  src/base/math.h
  src/game_io/game_loader.h
Labels: bug, ftbfs

#5885 Naval Warfare: Attack UI Refactoring
  src/economy/shippingitem.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/map_objects/tribes/worker.h
  src/logic/player.cc
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/wui/attack_window.cc
  src/wui/attack_window.h
  src/wui/interactive_player.cc
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
  src/wui/soldierlist.cc
  src/wui/soldierlist.h
Labels: enhancement, military, seafaring, ui

#5906 [refactor] Make `WLApplication::get()` return reference
  src/main.cc
  src/ui_basic/panel.cc
  src/ui_basic/progresswindow.cc
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/tech_info.cc
  src/wlapplication.cc
  src/wlapplication.h
  src/wui/mapview.cc
Labels: cleanup & refactoring

#5902 Make Main Menu Dropdown Entries a Bigger Click Target
  data/templates/default/init.lua
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/ui_basic/dropdown.h
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
  src/ui_fsmenu/main.cc
Labels: enhancement, accessibility

#5910 Capitalisation of tribe names - Barbarians
  data/campaigns/atl02.wmf/scripting/texts.lua
  data/campaigns/emp01.wmf/elemental
  data/campaigns/emp02.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/mission_thread.lua
  data/campaigns/fri02.wmf/scripting/texts.lua
  data/maps/SP_Scenarios/The_Green_Plateau.wmf/scripting/texts.lua
  data/tribes/buildings/productionsites/atlanteans/sawmill/init.lua
  data/tribes/buildings/productionsites/empire/sawmill/init.lua
  data/tribes/buildings/warehouses/barbarians/headquarters/init.lua
  data/tribes/buildings/warehouses/barbarians/headquarters_interim/init.lua
  data/tribes/initialization/atlanteans/units.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/frisians/units.lua
  src/logic/map_objects/tribes/market.cc
  src/scripting/lua_map.cc
  test/maps/all_tribes.wmf/scripting/test_barbarians.lua
  test/maps/market_trading.wmf/scripting/tribes/init.lua
  test/maps/plain.wmf/scripting/tribes/init.lua
Labels: bug, internationalization, barbarians

#5909 Tutorial 01 fixes
  data/campaigns/tutorial01_basic_control.wmf/scripting/helper_functions_demonstration.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/mission_thread.lua
  data/campaigns/tutorial01_basic_control.wmf/scripting/texts.lua
Labels: bug, enhancement, tutorials, regression

#5914 Resolve static libraries during configuration
  CMakeLists.txt
  cmake/WlFunctions.cmake
Labels: building & packaging

#5918 Increase sleep time in test/maps/expedition.wmf/scripting/test_starting_and_immediately_canceling.lua
  test/maps/expedition.wmf/scripting/test_starting_and_immediately_canceling.lua
Labels: building & packaging, testing

#5917 Disable ignored clang-tidy checks in the config file
  .clang-tidy
  src/base/i18n.h
  src/graphic/style_manager.cc
  src/scripting/lua_bases.h
  src/scripting/lua_game.h
  src/scripting/lua_globals.cc
  src/scripting/lua_map.h
  src/scripting/luna.h
  src/wlapplication_options.cc
  utils/check_clang_tidy_results.py
  utils/run-clang-tidy.py
Labels: bug, cleanup & refactoring

#5904 Build vcpkg packages weekly
  .github/scripts/vcpkg_ref
  .github/workflows/build.yaml
  .github/workflows/check_vcpkg.yaml
  .github/workflows/i18n.yaml
Labels: building & packaging

#5905 Add-Ons Packager: Compute Minimum WL Version For Maps
  src/logic/CMakeLists.txt
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/main.cc
Labels: enhancement, maps, addon

#5921 Remove hard-coded library paths for MinGW builds
  CMakeLists.txt
Labels: building & packaging, windows

#5908 Naval Warfare: Attack Anything in Range
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/player.cc
  src/wui/attack_window.cc
  src/wui/interactive_player.cc
Labels: enhancement, military, seafaring

#5922 Cache clang-tidy
  .github/workflows/build.yaml
  utils/run-clang-tidy.py
Labels: enhancement, python, codecheck, cleanup & refactoring, building & packaging

#5912 Link ship/ferry yards to fleets and produce ships/ferries as needed
  data/images/wui/fieldaction/menu_tab_ferry_targets.png
  data/images/wui/fieldaction/menu_tab_ship_targets.png
  data/images/wui/overlays/special.png
  data/tribes/buildings/productionsites/amazons/ferry_yard/init.lua
  data/tribes/buildings/productionsites/atlanteans/ferry_yard/init.lua
  data/tribes/buildings/productionsites/barbarians/ferry_yard/init.lua
  data/tribes/buildings/productionsites/empire/ferry_yard/init.lua
  data/tribes/buildings/productionsites/frisians/ferry_yard/init.lua
  data/tribes/workers/amazons/shipwright/init.lua
  data/tribes/workers/atlanteans/shipwright/init.lua
  data/tribes/workers/barbarians/shipwright/init.lua
  data/tribes/workers/empire/shipwright/init.lua
  data/tribes/workers/frisians/shipwright/init.lua
  src/economy/economy.h
  src/economy/ferry_fleet.cc
  src/economy/ferry_fleet.h
  src/economy/ship_fleet.cc
  src/economy/ship_fleet.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/map.cc
  src/logic/map.h
  src/logic/map_objects/findnode.cc
  src/logic/map_objects/findnode.h
  src/logic/map_objects/immovable.cc
  src/logic/map_objects/map_object.h
  src/logic/map_objects/map_object_type.cc
  src/logic/map_objects/map_object_type.h
  src/logic/map_objects/tribes/production_program.cc
  src/logic/map_objects/tribes/production_program.h
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/logic/widelands.h
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_object_packet.cc
  src/scripting/lua_map.cc
  src/ui_basic/panel.h
  src/wui/CMakeLists.txt
  src/wui/buildingwindow.cc
  src/wui/fieldaction.cc
  src/wui/fleet_options_window.cc
  src/wui/fleet_options_window.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
  src/wui/interactive_spectator.cc
Labels: enhancement, tribes, seafaring, economy, ferry & ww

#5926 Naval Warfare: Show fleet strength in general statistics
  data/images/wui/stats/genstats_naval_losses.png
  data/images/wui/stats/genstats_naval_victories.png
  data/images/wui/stats/genstats_ships.png
  src/game_io/game_player_info_packet.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/player.h
  src/wui/general_statistics_menu.cc
Labels: enhancement, statistics, seafaring

#5928 Fix Shipyard/PortDock/FleetInterface Load Order Regression
  src/economy/ship_fleet.cc
  src/logic/map_objects/map_object.h
  src/logic/map_objects/tribes/productionsite.cc
  src/logic/map_objects/tribes/productionsite.h
  src/map_io/map_buildingdata_packet.cc
  src/map_io/widelands_map_loader.cc
Labels: bug, saveloading & compatibility, seafaring, regression

#5900 Unify `EditBox` and `MultilineEditbox`
  src/editor/ui_menus/main_menu_map_options.cc
  src/editor/ui_menus/main_menu_map_options.h
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_random_map.h
  src/editor/ui_menus/main_menu_save_map.cc
  src/editor/ui_menus/main_menu_save_map.h
  src/editor/ui_menus/main_menu_save_map_make_directory.cc
  src/editor/ui_menus/main_menu_save_map_make_directory.h
  src/editor/ui_menus/player_menu.cc
  src/editor/ui_menus/player_menu.h
  src/graphic/wordwrap.cc
  src/graphic/wordwrap.h
  src/ui_basic/CMakeLists.txt
  src/ui_basic/editbox.cc
  src/ui_basic/editbox.h
  src/ui_basic/multilineeditbox.h
  src/ui_basic/text_prompt.h
  src/ui_basic/textinput.cc
  src/ui_basic/textinput.h
  src/ui_fsmenu/addons/contact.h
  src/ui_fsmenu/addons/login_box.cc
  src/ui_fsmenu/addons/login_box.h
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/manager.h
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager.h
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/addons/packager_box.h
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
  src/ui_fsmenu/addons/screenshot_upload.cc
  src/ui_fsmenu/addons/screenshot_upload.h
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/internet_lobby.h
  src/ui_fsmenu/login_box.cc
  src/ui_fsmenu/login_box.h
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/netsetup_lan.h
  src/wui/economy_options_window.cc
  src/wui/economy_options_window.h
  src/wui/game_chat_panel.cc
  src/wui/game_chat_panel.h
  src/wui/game_main_menu_save_game.cc
  src/wui/game_main_menu_save_game.h
  src/wui/pinned_note.cc
  src/wui/pinned_note.h
  src/wui/quicknavigation.cc
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
  src/wui/warehousewindow.cc
Labels: cleanup & refactoring, accessibility, ui
