Repository widelands/widelands, pull requests merged in 2023-06, with the labels that each got.

#5872 UI Plugins
  doc/sphinx/source/add-ons.rst
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/editor_game_base.cc
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/scripting/CMakeLists.txt
  src/scripting/lua.cc
  src/scripting/lua.h
  src/scripting/lua_ui.cc
  src/scripting/lua_ui.h
  src/wui/interactive_base.h
Labels: enhancement, ui, addon

#5934 Enforce use of global vcpkg in CI
  .github/workflows/build.yaml
Labels: building & packaging, windows

#5937 Skip timestamp-only POT changes during translations update
  utils/merge_and_push_translations.sh
Labels: internationalization, cleanup & refactoring, regression

#5929 Naval Warfare: Make detected portspaces addressable for expeditions
  src/game_io/game_player_info_packet.cc
  src/logic/CMakeLists.txt
  src/logic/detected_port_space.cc
  src/logic/detected_port_space.h
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_compassdir.cc
  src/logic/map_compassdir.h
  src/logic/map_objects/checkstep.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/ui_basic/listselect.cc
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
Labels: enhancement, seafaring

#5942 Layout ship window before setting fastclick target
  src/wui/shipwindow.cc
Labels: bug, seafaring, accessibility, ui

#5943 CMakeLists.txt cleanups
  CMakeLists.txt
Labels: cleanup & refactoring, building & packaging

#5945 Remove superfluous SDL_GetModState() calls
  src/ui_basic/button.cc
  src/ui_basic/checkbox.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/listselect.cc
  src/ui_basic/panel.cc
  src/ui_basic/textinput.cc
  src/wui/game_chat_panel.cc
Labels: cleanup & refactoring

#5946 Fix regression in `EditBox::scroll_cursor_into_view`
  src/ui_basic/textinput.cc
Labels: bug, ui, regression

#5935 Allow lookup of richtext inline images without specifying scale suffix
  src/graphic/text/rt_parse.cc
  src/graphic/text/rt_render.cc
Labels: bug, help, tutorials, regression

#5930 Garrisons for Warehouses and Warships
  data/images/wui/buildings/prefer_any.png
  data/tribes/buildings/warehouses/amazons/headquarters/init.lua
  data/tribes/buildings/warehouses/amazons/port/init.lua
  data/tribes/buildings/warehouses/atlanteans/headquarters/init.lua
  data/tribes/buildings/warehouses/atlanteans/port/init.lua
  data/tribes/buildings/warehouses/barbarians/headquarters/init.lua
  data/tribes/buildings/warehouses/barbarians/headquarters_interim/init.lua
  data/tribes/buildings/warehouses/barbarians/port/init.lua
  data/tribes/buildings/warehouses/empire/headquarters/init.lua
  data/tribes/buildings/warehouses/empire/headquarters_shipwreck/init.lua
  data/tribes/buildings/warehouses/empire/port/init.lua
  data/tribes/buildings/warehouses/frisians/headquarters/init.lua
  data/tribes/buildings/warehouses/frisians/port/init.lua
  src/ai/defaultai_warfare.cc
  src/economy/CMakeLists.txt
  src/economy/portdock.cc
  src/economy/portdock.h
  src/economy/soldier_request.cc
  src/economy/soldier_request.h
  src/logic/CMakeLists.txt
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/tribes/building.h
  src/logic/map_objects/tribes/building_settings.cc
  src/logic/map_objects/tribes/building_settings.h
  src/logic/map_objects/tribes/constructionsite.cc
  src/logic/map_objects/tribes/militarysite.cc
  src/logic/map_objects/tribes/militarysite.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/warehouse.h
  src/logic/map_objects/tribes/worker.cc
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/logic/widelands.cc
  src/logic/widelands.h
  src/map_io/map_buildingdata_packet.cc
  src/map_io/map_packet_versions.h
  src/scripting/lua_map.cc
  src/scripting/lua_root.cc
  src/wui/constructionsitewindow.cc
  src/wui/soldiercapacitycontrol.cc
  src/wui/soldierlist.cc
  src/wui/warehousewindow.cc
Labels: enhancement, military, seafaring, economy

#5947 Position attacking warships 2 nodes west of the defender
  src/logic/map_objects/tribes/ship.cc
Labels: military, seafaring, urgent

#5954 Continuous Bob Animations
  src/logic/map_objects/bob.cc
Labels: bug, graphics

#5938 Naval Warfare: Open all nearby ships' windows on click
  src/ui_basic/listselect.cc
  src/ui_basic/listselect.h
  src/wui/attack_window.cc
  src/wui/fieldaction.cc
  src/wui/fieldaction.h
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
  src/wui/interactive_player.h
  src/wui/interactive_spectator.cc
Labels: seafaring, accessibility

#5953 Fix Kicking Out Superfluous Warship Soldiers
  src/economy/soldier_request.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: bug, seafaring

#5959 Translation update: Exit cleanly when nothing needs to be committed
  utils/merge_and_push_translations.sh
Labels: internationalization, building & packaging

#5956 Z-Order Map Options Window Above Save Map Window
  src/editor/ui_menus/main_menu_save_map.cc
Labels: bug, editor, ui, regression

#5962 Fix stacking order of new ship battles
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: bug, seafaring
