Repository widelands/widelands, pull requests merged in 2023-03, with the labels that each got.

#5794 Disable apt upgrade in workflow
  .github/scripts/install_deps.sh
Labels: building & packaging, linux

#5786 Allow sending expeditions and warships to specific ports, ships, and notes
  data/images/wui/ship/ship_retreat.png
  src/economy/shipping_schedule.cc
  src/economy/ware_instance.cc
  src/logic/game.cc
  src/logic/game.h
  src/logic/map_objects/bob.cc
  src/logic/map_objects/bob.h
  src/logic/map_objects/pinned_note.cc
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/shipstates.h
  src/logic/player.cc
  src/logic/player.h
  src/logic/playercommand.cc
  src/logic/playercommand.h
  src/logic/queue_cmd_factory.cc
  src/logic/queue_cmd_ids.h
  src/scripting/lua_map.cc
  src/ui_basic/dropdown.h
  src/wui/seafaring_statistics_menu.cc
  src/wui/shipwindow.cc
  src/wui/shipwindow.h
Labels: enhancement, seafaring

#5781 Carry over ship names in Atlantean campaign
  data/campaigns/atl01.wmf/scripting/mission_thread.lua
  data/campaigns/atl02.wmf/scripting/init.lua
  data/campaigns/atl02.wmf/scripting/starting_conditions.lua
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/map_objects/tribes/warehouse.h
  src/logic/player.cc
  src/logic/player.h
Labels: bug, tribes, campaigns & scenarios, seafaring, atlanteans

#5804 Fix undefined `GLEW_ERROR_NO_GLX_DISPLAY`
  src/graphic/gl/initialize.cc
Labels: bug, ftbfs, graphics

#5799 Workflow improvements
  .github/scripts/install_deps.sh
  .github/workflows/build.yaml
  .github/workflows/i18n.yaml
  install-dependencies.sh
Labels: building & packaging

#5806 Add timeout support to regression_test.py and improve output
  .github/workflows/build.yaml
  regression_test.py
Labels: bug, enhancement, building & packaging, testing

#5785 Fix collapsing input queues and other window handling fixes and enhancements
  src/ui_basic/unique_window.cc
  src/ui_basic/unique_window.h
  src/ui_basic/window.cc
  src/wui/buildingwindow.cc
  src/wui/buildingwindow.h
  src/wui/constructionsitewindow.cc
  src/wui/constructionsitewindow.h
  src/wui/dismantlesitewindow.cc
  src/wui/dismantlesitewindow.h
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
  src/wui/interactive_base.cc
  src/wui/militarysitewindow.cc
  src/wui/militarysitewindow.h
  src/wui/portdockwaresdisplay.cc
  src/wui/portdockwaresdisplay.h
  src/wui/productionsitewindow.cc
  src/wui/productionsitewindow.h
  src/wui/trainingsitewindow.cc
  src/wui/trainingsitewindow.h
  src/wui/unique_window_handler.cc
  src/wui/unique_window_handler.h
  src/wui/warehousewindow.cc
  src/wui/warehousewindow.h
Labels: enhancement, accessibility, ui

#5812 Fix window Z ordering priorities
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/ui_basic/dropdown.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/window.h
  src/wui/actionconfirm.cc
  src/wui/game_exit_confirm_box.cc
  src/wui/game_main_menu_save_game.cc
  src/wui/info_panel.cc
Labels: bug, ui, regression

#5803 Save only used terrains in terrain packet
  src/map_io/map_terrain_packet.cc
  src/map_io/map_version_packet.cc
Labels: bug, world, saveloading & compatibility, addon

#5821 Make Amazon treetop sentry placeable by scripts
  src/logic/player.cc
  test/maps/all_tribes.wmf/scripting/init.lua
  test/maps/all_tribes.wmf/scripting/test_amazons.lua
  test/maps/place_buildings.wmf/binary/heights
  test/maps/place_buildings.wmf/binary/mapobjects
  test/maps/place_buildings.wmf/binary/resource
  test/maps/place_buildings.wmf/binary/terrain
  test/maps/place_buildings.wmf/elemental
  test/maps/place_buildings.wmf/minimap.png
  test/maps/place_buildings.wmf/objective
  test/maps/place_buildings.wmf/player_names
  test/maps/place_buildings.wmf/player_position
  test/maps/place_buildings.wmf/port_spaces
  test/maps/place_buildings.wmf/scripting/init.lua
  test/maps/place_buildings.wmf/scripting/test_place_buildings.lua
  test/maps/place_buildings.wmf/version
  utils/dump_economy.lua
Labels: bug, lua, amazons

#5826 Fix player end status handling
  src/game_io/game_player_info_packet.cc
  src/logic/playersmanager.cc
  src/logic/playersmanager.h
  src/wui/game_summary.cc
  src/wui/game_summary.h
Labels: bug, crashes or hangs, regression

#5824 Fix segfault in Panel::move_to_top()
  src/ui_basic/panel.cc
Labels: bug, crashes or hangs, ui

#5829 Turn unguaranteed add-on dependency check assert into a conditional
  src/ui_fsmenu/addons/manager.cc
Labels: bug, crashes or hangs, regression, addon

#5795 Naval Warfare: Healing
  data/tribes/ships/amazons/init.lua
  data/tribes/ships/atlanteans/init.lua
  data/tribes/ships/barbarians/init.lua
  data/tribes/ships/empire/init.lua
  data/tribes/ships/frisians/init.lua
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: enhancement, seafaring

#5831 Remove libvorbis feature from vcpkg package list
  install-dependencies.sh
Labels: building & packaging, windows

#5832 Send message when ship arrives at player-specified destination
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: enhancement, seafaring
