Repository widelands/widelands, pull requests merged in 2023-08, with the labels that each got.

#6050 Building Stats Menu checks if saveloaded selection is still available
  src/wui/building_statistics_menu.cc
Labels: bug, crashes or hangs, saveloading & compatibility, statistics

#6055 Fix `Window::move_inside_parent` bottom docking
  src/ui_basic/window.cc
Labels: bug, ui, regression

#6059 Options window cleanup
  data/templates/default/init.lua
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/ui_basic/checkbox.cc
  src/ui_basic/checkbox.h
  src/ui_basic/panel.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication.cc
  src/wlapplication.h
  src/wlapplication_messages.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/CMakeLists.txt
  src/wui/sound_options.cc
Labels: enhancement, ui

#6054 Settlers2/RTTR Map Loading Fixes
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/map_io/s2map.cc
Labels: maps, saveloading & compatibility

#6053 Forbid changing soldier capacity in replays
  src/base/exceptions.cc
  src/base/wexception.h
  src/ui_basic/panel.cc
  src/wui/soldiercapacitycontrol.cc
Labels: bug, crashes or hangs, replay, multithreading

#6062 Fix documentation CI workflow
  .github/workflows/build.yaml
Labels: python, building & packaging

#6048 User Inactivity Detection
  src/logic/save_handler.cc
  src/logic/save_handler.h
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication_messages.cc
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
Labels: enhancement, saveloading & compatibility, accessibility

#6065 Fix racecondition segfault when opening building window
  src/wui/interactive_base.cc
Labels: crashes or hangs, tribes, ui, multithreading

#6066 Misc Naval Warfare Segfault/Assert Fixes
  src/logic/map_objects/tribes/ship.cc
Labels: bug, crashes or hangs, seafaring, urgent

#6070 Well-defined shipyards collaboration
  src/logic/map_objects/tribes/production_program.cc
Labels: balancing & gameplay, seafaring

#6073 Game client win condition duration bugfix
  src/ui_basic/spinbox.cc
  src/ui_basic/spinbox.h
  src/ui_fsmenu/launch_mpg.cc
Labels: bug, multiplayer & networking, wincondition

#6069 Fix chat player color indices if some players are not in the game
  src/wui/interactive_base.cc
Labels: bug, chat

#6057 Don't require World add-ons to be globally enabled for dependent Maps add-ons
  src/logic/addons.cc
  src/logic/addons.h
  src/ui_fsmenu/addons/manager.cc
Labels: enhancement, addon

#6071 Fix naval battle stacking in complex situations
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/wui/attack_window.cc
  src/wui/interactive_player.cc
Labels: bug, crashes or hangs, seafaring

#6079 Fix LaunchMPG Layouting Segfault
  src/ui_fsmenu/launch_mpg.cc
Labels: bug, crashes or hangs, multiplayer & networking, accessibility, regression

#6056 Custom Ship & Warehouse Naming Lists
  src/logic/filesystem_constants.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/warehouse.cc
  src/logic/player.cc
  src/logic/player.h
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/network_protocol.h
  src/ui_basic/table.cc
  src/ui_fsmenu/launch_spg.cc
  src/wlapplication.cc
  src/wui/interactive_player.cc
Labels: enhancement, tribes

#6076 Fail gracefully in LAN setup when network access restricted
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/netsetup_lan.cc
  src/ui_fsmenu/netsetup_lan.h
Labels: bug, crashes or hangs, multiplayer & networking

#6089 Fix documentation CI dependencies, again
  .github/workflows/build.yaml
  doc/sphinx/requirements.txt
Labels: bug, python, building & packaging, urgent

#6101 Fix more box regressions
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/multiplayersetupgroup.h
  src/wui/inputqueuedisplay.cc
  src/wui/inputqueuedisplay.h
Labels: ui

#6097 Fix `PlayerMessageCommand` Saveloading
  src/logic/playercommand.cc
Labels: bug, saveloading & compatibility

#6098 Fix double cleanup for direct loading of invalid replay
  src/logic/game.cc
  src/logic/replay_game_controller.cc
Labels: bug, crashes or hangs, replay, memory & performance

#6091 Add mutex locks for economy creation/deletion
  src/logic/player.cc
  src/wui/stock_menu.cc
Labels: bug, crashes or hangs, ui, economy, multithreading

#6105 Reinitialize forester cache when reloading
  src/logic/game.cc
Labels: bug, replay, desync

#6087 Make `SoldierList` robust against map object removal
  src/wui/soldierlist.cc
Labels: bug, crashes or hangs, tribes, ui

#6104 Safeguard pathfinding with a mutex
  src/base/mutex.h
  src/logic/map.cc
Labels: bug, pathfinding, multithreading

#6099 Stop ship battles when ship is destroyed
  src/logic/map_objects/tribes/ship.cc
Labels: bug, seafaring, urgent

#6086 Garrisoned soldiers shouldn't count towards economy target
  src/economy/economy.cc
Labels: bug, military, economy, urgent

#6084 Add a building plot to unusable port island on Calvisson
  data/maps/Calvisson.wmf/binary/terrain
Labels: maps

#6108 Emergency saving enhancements
  data/txts/tips/crash.lua
  src/network/gameclient.cc
  src/network/gamehost.cc
  src/wlapplication.cc
Labels: enhancement, saveloading & compatibility, urgent

#6103 Draw system clock also in main menu
  src/base/time_string.cc
  src/base/time_string.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/wui/info_panel.cc
Labels: enhancement, accessibility

#6064 commit pure translations separately
  utils/merge_and_push_translations.sh
Labels: enhancement, internationalization, cleanup & refactoring

#6115 Invasion soldiers conquer portspace for the duration of the invasion
  src/logic/map_objects/map_object.h
  src/logic/map_objects/map_object_type.cc
  src/logic/map_objects/map_object_type.h
  src/logic/map_objects/tribes/soldier.cc
  src/logic/map_objects/tribes/soldier.h
  src/map_io/map_object_packet.cc
  src/scripting/lua_map.cc
Labels: bug, military, seafaring, urgent

#5944 Debugconsole and input history improvements
  src/CMakeLists.txt
  src/game_io/game_interactive_player_packet.cc
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/network_gaming_messages.cc
  src/ui_basic/CMakeLists.txt
  src/ui_basic/textinput.cc
  src/ui_basic/textinput.h
  src/ui_fsmenu/internet_lobby.cc
  src/ui_fsmenu/keyboard_options.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication.cc
  src/wlapplication_messages.cc
  src/wlapplication_options.cc
  src/wlapplication_options.h
  src/wui/attack_window.cc
  src/wui/buildingwindow.cc
  src/wui/fieldaction.cc
  src/wui/game_chat_menu.cc
  src/wui/game_chat_menu.h
  src/wui/game_chat_panel.cc
  src/wui/game_chat_panel.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_gamebase.cc
  src/wui/interactive_gamebase.h
  src/wui/interactive_player.cc
  src/wui/shipwindow.cc
Labels: enhancement, cleanup & refactoring, lua, chat

#6125 Add Lua APIs for Missing Bob Types
  src/logic/map_objects/tribes/soldier.h
  src/scripting/lua_bases.cc
  src/scripting/lua_bases.h
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
  src/ui_fsmenu/main.cc
  test/maps/plain.wmf/scripting/test_pinned_notes.lua
Labels: bug, enhancement, tribes, lua
