Repository widelands/widelands, pull requests merged in 2023-02, with the labels that each got.

#5768 Fix performance text in encyclopedia and sleep times in production buildings where the workers need some experience
  data/tribes/buildings/productionsites/barbarians/ax_workshop/init.lua
  data/tribes/buildings/productionsites/barbarians/bakery/init.lua
  data/tribes/buildings/productionsites/barbarians/barracks/init.lua
  data/tribes/buildings/productionsites/barbarians/big_inn/init.lua
  data/tribes/buildings/productionsites/barbarians/brewery/init.lua
  data/tribes/buildings/productionsites/barbarians/coalmine/init.lua
  data/tribes/buildings/productionsites/barbarians/coalmine_deep/init.lua
  data/tribes/buildings/productionsites/barbarians/coalmine_deeper/init.lua
  data/tribes/buildings/productionsites/barbarians/gamekeepers_hut/init.lua
  data/tribes/buildings/productionsites/barbarians/goldmine/init.lua
  data/tribes/buildings/productionsites/barbarians/goldmine_deep/init.lua
  data/tribes/buildings/productionsites/barbarians/goldmine_deeper/init.lua
  data/tribes/buildings/productionsites/barbarians/granitemine/init.lua
  data/tribes/buildings/productionsites/barbarians/inn/init.lua
  data/tribes/buildings/productionsites/barbarians/ironmine/init.lua
  data/tribes/buildings/productionsites/barbarians/ironmine_deep/init.lua
  data/tribes/buildings/productionsites/barbarians/ironmine_deeper/init.lua
  data/tribes/buildings/productionsites/barbarians/metal_workshop/init.lua
  data/tribes/buildings/productionsites/barbarians/micro_brewery/init.lua
  data/tribes/buildings/productionsites/barbarians/tavern/init.lua
  data/tribes/buildings/productionsites/barbarians/warmill/init.lua
  data/tribes/initialization/barbarians/units.lua
  data/tribes/initialization/frisians/units.lua
Labels: help

#5772 Update webp link target for MSVC builds
  CMakeLists.txt
  cmake/WlFunctions.cmake
Labels: building & packaging, windows

#5764 Support compilation with musl libc
  install-dependencies.sh
  src/base/i18n.cc
  src/base/macros.h
Labels: building & packaging

#5782 Transifex String Fixes
  data/campaigns/fri05.wmf/scripting/texts.lua
  data/maps/SP_Scenarios/Along_The_River.wmf/scripting/objectives.lua
  data/tribes/initialization/barbarians/units.lua
Labels: bug, internationalization

#5783 Fix Editor Add-Ons Postloading
  src/editor/editorinteractive.cc
  src/editor/ui_menus/main_menu_new_map.cc
  src/wui/interactive_base.cc
Labels: bug, world, editor, addon

#5780 Disable fastclick during game loading
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/progresswindow.cc
  src/ui_basic/window.cc
Labels: bug, saveloading & compatibility, accessibility
