Repository widelands/widelands, pull requests merged in 2023-01, with the labels that each got.

#5729 Add tooltips to ItemWaresDisplay and fix icons alignment
  src/wui/CMakeLists.txt
  src/wui/itemwaresdisplay.cc
  src/wui/itemwaresdisplay.h
  src/wui/shipwindow.cc
Labels: bug, enhancement, seafaring, ui

#5720 Fix heap-use-after-free in `BuildingWindow::init`
  src/wui/buildingwindow.cc
Labels: bug, crashes or hangs, ui, regression

#5719 Keep player colours if unchanged when changing slot
  src/logic/single_player_game_settings_provider.cc
  src/ui_fsmenu/multiplayersetupgroup.cc
  src/ui_fsmenu/singleplayersetupbox.cc
  src/ui_fsmenu/singleplayersetupbox.h
Labels: enhancement, ui

#5724 Fix Filesystem Errors from ReplayWriter
  src/logic/CMakeLists.txt
  src/logic/mutable_addon.cc
  src/logic/replay.cc
  src/logic/save_handler.cc
  src/logic/save_handler.h
  src/network/CMakeLists.txt
  src/network/net_addons.cc
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/addons/manager.cc
  src/wlapplication.cc
Labels: bug, saveloading & compatibility, replay, regression, filesystem

#5730 Indicate soldier preference in milsite stats string
  data/campaigns/tutorial02_warfare.wmf/scripting/texts.lua
  src/logic/map_objects/tribes/militarysite.cc
Labels: enhancement, military, statistics

#5737 Updated Frisian Campaign Portraits
  data/campaigns/fri01.wmf/pics/hauke.png
  data/campaigns/fri01.wmf/pics/maukor.png
  data/campaigns/fri01.wmf/pics/reebaud.png
  data/campaigns/fri02.wmf/pics/hauke.png
  data/campaigns/fri02.wmf/pics/murilius.png
  data/campaigns/fri02.wmf/pics/reebaud.png
  data/campaigns/fri03.wmf/pics/angadthur.png
  data/campaigns/fri03.wmf/pics/claus.png
  data/campaigns/fri03.wmf/pics/henneke.png
  data/campaigns/fri03.wmf/pics/iniucundus.png
  data/campaigns/fri04.wmf/pics/amazon.png
  data/campaigns/fri04.wmf/pics/claus.png
  data/campaigns/fri04.wmf/pics/henneke.png
  data/campaigns/fri04.wmf/pics/iniucundus.png
  data/campaigns/fri04.wmf/pics/reebaud.png
  data/campaigns/fri05.wmf/pics/claus.png
  data/campaigns/fri05.wmf/pics/henneke.png
  data/campaigns/fri05.wmf/pics/ketelsen.png
  data/campaigns/fri05.wmf/pics/reebaud.png
Labels: campaigns & scenarios, graphics, frisians

#5728 Forbid soldiers leaving buildings through the wall
  src/logic/map_objects/tribes/soldier.cc
Labels: bug, military

#5739 Add function `LuaMap::wrap_field` with wraparound
  src/scripting/lua_map.cc
  src/scripting/lua_map.h
Labels: enhancement, maps, lua

#5740 Fix map pixel to triangle computation regression
  src/wui/mapviewpixelfunctions.cc
Labels: bug, maps, regression

#5715 Add mutexes for Notifications backend
  src/base/CMakeLists.txt
  src/base/i18n.h
  src/base/multithreading.cc
  src/base/multithreading.h
  src/base/mutex.h
  src/game_io/game_cmd_queue_packet.cc
  src/logic/map_objects/map_object.cc
  src/logic/map_objects/tribes/building.cc
  src/logic/message_queue.h
  src/notifications/notifications_impl.h
  src/scripting/lua_coroutine.cc
  src/scripting/lua_table.h
  src/wui/attack_window.cc
  src/wui/interactive_player.cc
Labels: bug, multithreading

#5734 Allow themes to replace arbitrary UI images
  cmake/codecheck/rules/images_exist.py
  data/templates/default/init.lua
  doc/sphinx/source/themes.rst
  src/editor/CMakeLists.txt
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/editor/ui_menus/main_menu_load_map.cc
  src/editor/ui_menus/main_menu_new_map.cc
  src/editor/ui_menus/main_menu_random_map.cc
  src/editor/ui_menus/main_menu_save_map.cc
  src/graphic/CMakeLists.txt
  src/graphic/animation/CMakeLists.txt
  src/graphic/graphic_functions.cc
  src/graphic/image_cache.cc
  src/graphic/image_cache.h
  src/graphic/playercolor.cc
  src/graphic/style_manager.cc
  src/graphic/style_manager.h
  src/graphic/text/CMakeLists.txt
  src/graphic/text/test/CMakeLists.txt
  src/logic/CMakeLists.txt
  src/logic/map_objects/CMakeLists.txt
  src/map_io/CMakeLists.txt
  src/network/CMakeLists.txt
  src/ui_basic/CMakeLists.txt
  src/ui_basic/panel.cc
  src/ui_basic/progresswindow.cc
  src/ui_basic/progresswindow.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/main.cc
  src/wui/CMakeLists.txt
  src/wui/info_panel.cc
Labels: enhancement, graphics, ui, filesystem, addon

#5747 Fix hang on building window warp
  src/wui/buildingwindow.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/productionsitewindow.cc
  src/wui/productionsitewindow.h
Labels: bug, crashes or hangs, ui, regression, multithreading

#5732 Add Go To Road button to fieldaction roadbuild window
  src/wui/fieldaction.cc
Labels: enhancement, ui

#5750 Update python formatting for docformatter 1.5
  utils/confgettext.py
  utils/fix_formatting.py
  utils/pywi/animation.py
  utils/pywi/config.py
  utils/pywi/packing.py
  utils/pywi/tests.py
  utils/test/test_lua-xgettext.py
  utils/test/test_make_spritemap.py
Labels: python, building & packaging

#5718 Allow starting new game with additional world add-ons
  src/map_io/s2map.cc
  src/map_io/widelands_map_loader.cc
Labels: enhancement, world, addon

#5735 Refine game error handling
  src/base/format/string_node.h
  src/logic/game_data_error.cc
  src/logic/game_data_error.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/main.h
  src/wlapplication.cc
Labels: bug, saveloading & compatibility, ui

#5733 Make "Fogless" a Game Setting
  data/scripting/win_conditions/endless_game_fogless.lua
  data/scripting/win_conditions/init.lua
  data/templates/new_game_template
  src/editor/ui_menus/main_menu_random_map.cc
  src/logic/game.cc
  src/logic/game_settings.h
  src/logic/single_player_game_settings_provider.cc
  src/logic/single_player_game_settings_provider.h
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.cc
  src/network/host_game_settings_provider.h
  src/network/network_protocol.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/wlapplication.cc
Labels: enhancement, wincondition

#5753 Enable World Add-Ons in Random Matches & Maps
  src/editor/ui_menus/main_menu_random_map.cc
  src/ui_fsmenu/random_game.cc
Labels: enhancement, world, addon, random map

#5635 3-Click Map Publishing as Add-On Inside the Editor
  data/images/wui/editor/menus/upload.png
  src/editor/CMakeLists.txt
  src/editor/editorinteractive.cc
  src/editor/editorinteractive.h
  src/logic/addons.cc
  src/logic/addons.h
  src/logic/filesystem_constants.h
  src/logic/mutable_addon.cc
  src/logic/mutable_addon.h
  src/network/net_addons.cc
  src/network/net_addons.h
  src/ui_fsmenu/CMakeLists.txt
  src/ui_fsmenu/addons/CMakeLists.txt
  src/ui_fsmenu/addons/contact.cc
  src/ui_fsmenu/addons/contact.h
  src/ui_fsmenu/addons/login_box.cc
  src/ui_fsmenu/addons/login_box.h
  src/ui_fsmenu/addons/manager.cc
  src/ui_fsmenu/addons/manager.h
  src/ui_fsmenu/addons/packager.cc
  src/ui_fsmenu/addons/packager.h
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/addons/packager_box.h
  src/ui_fsmenu/addons/progress.cc
  src/ui_fsmenu/addons/progress.h
  src/ui_fsmenu/addons/remote_interaction.cc
  src/ui_fsmenu/addons/remote_interaction.h
  src/ui_fsmenu/addons/rows_ui.cc
  src/ui_fsmenu/addons/rows_ui.h
  src/ui_fsmenu/addons/screenshot_upload.cc
  src/ui_fsmenu/addons/screenshot_upload.h
  src/wlapplication.cc
  src/wui/mapdata.cc
Labels: enhancement, editor, addon

#5759 CI workflow update
  .github/workflows/build.yaml
  .github/workflows/format.yaml
Labels: building & packaging

#5761 Only create pre-release from master in main repo
  .github/workflows/build.yaml
Labels: building & packaging

#5763 Fix add-ons admin dialog Enter key handling
  src/ui_fsmenu/addons/remote_interaction.cc
Labels: bug, ui, addon

#5566 Make Info Panel a Snap Target & Remove "Snap Only When Overlapping" Option
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/logic/generic_save_handler.cc
  src/ui_basic/box.cc
  src/ui_basic/box.h
  src/ui_basic/button.cc
  src/ui_basic/button.h
  src/ui_basic/dropdown.cc
  src/ui_basic/panel.cc
  src/ui_basic/panel.h
  src/ui_basic/slider.cc
  src/ui_basic/slider.h
  src/ui_basic/window.cc
  src/ui_basic/window.h
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/options.cc
  src/ui_fsmenu/options.h
  src/wlapplication_messages.cc
  src/wui/game_main_menu_save_game.cc
  src/wui/info_panel.cc
  src/wui/info_panel.h
  src/wui/interactive_base.cc
  test/maps/plain.wmf/scripting/test_ui.lua
Labels: enhancement, accessibility

#5766 Merge Add-On Dirnames in Map Select UIs
  src/editor/ui_menus/main_menu_load_map.cc
  src/editor/ui_menus/main_menu_load_map.h
  src/editor/ui_menus/main_menu_load_or_save_map.cc
  src/editor/ui_menus/main_menu_load_or_save_map.h
  src/editor/ui_menus/main_menu_save_map.cc
  src/editor/ui_menus/main_menu_save_map.h
  src/ui_fsmenu/addons/packager_box.cc
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/ui_fsmenu/main.cc
  src/ui_fsmenu/mapselect.cc
  src/ui_fsmenu/mapselect.h
  src/wui/mapdata.cc
  src/wui/mapdata.h
  src/wui/mapdetails.cc
  src/wui/maptable.cc
Labels: enhancement, maps, ui, addon
