Repository widelands/widelands, pull requests merged in 2023-04, with the labels that each got.

#5837 Add possibility to set vcpkg ref
  .github/scripts/vcpkg_ref
  .github/workflows/build.yaml
Labels: building & packaging

#5796 Naval Warfare: Onboard Soldiers Attack Bonus
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
Labels: enhancement, military, seafaring

#5845 Pin docformatter version in formatting workflow
  .github/workflows/format.yaml
  utils/fix_formatting.py
Labels: bug, python, building & packaging

#5849 added size to tooltip
  src/editor/ui_menus/tool_place_immovable_options_menu.cc
Labels: enhancement, world, editor, ui

#5848 Editor Automatic Tree Placement Tool
  data/scripting/editor/toolhistory_tooltip.lua
  src/editor/tools/place_immovable_tool.cc
  src/editor/tools/tool.h
  src/editor/ui_menus/categorized_item_selection_menu.h
  src/editor/ui_menus/tool_options_menu.h
  src/editor/ui_menus/tool_place_immovable_options_menu.cc
  src/editor/ui_menus/tool_place_immovable_options_menu.h
  src/editor/ui_menus/tool_toolhistory_options_menu.cc
  src/ui_basic/tabpanel.cc
  src/ui_basic/tabpanel.h
Labels: enhancement, world, editor

#5835 Integrate EditBox and MultilineEditbox with the primary selection buffer
  src/graphic/text_layout.h
  src/ui_basic/editbox.cc
  src/ui_basic/editbox.h
  src/ui_basic/multilineeditbox.cc
  src/ui_basic/multilineeditbox.h
Labels: enhancement, accessibility, ui

#5820 Watch window fixes and tweaks
  src/wui/mapview.cc
  src/wui/watchwindow.cc
  src/wui/watchwindow.h
Labels: bug, enhancement, accessibility, ui

#5856 Fix editor painting mode regression
  src/wui/mapview.cc
  src/wui/watchwindow.cc
Labels: bug, editor, regression

#5862 Validate that all tribes possess all special animations
  src/logic/map_objects/tribes/tribe_descr.cc
  src/logic/map_objects/tribes/tribe_descr.h
Labels: bug, tribes, graphics

#5825 Improve landmark behaviour when game main window is resized
  src/game_io/CMakeLists.txt
  src/game_io/game_interactive_player_packet.cc
  src/wui/mapview.cc
  src/wui/mapview.h
  src/wui/mapviewpixelfunctions.h
  src/wui/quicknavigation.cc
Labels: enhancement, accessibility

#5859 Naval Warfare: Coastal Invasion
  src/logic/map.cc
  src/logic/map.h
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/ship.h
  src/wui/shipwindow.cc
Labels: enhancement, balancing & gameplay, military, seafaring

#5867 Darken background behind modal windows
  src/ui_basic/panel.cc
Labels: enhancement, accessibility, graphics, ui

#5863 Refactor Game Configuration Flags
  src/editor/ui_menus/main_menu_random_map.cc
  src/logic/game.cc
  src/logic/game_settings.h
  src/logic/single_player_game_settings_provider.cc
  src/logic/single_player_game_settings_provider.h
  src/network/gameclient.cc
  src/network/gameclient.h
  src/network/gamehost.cc
  src/network/gamehost.h
  src/network/host_game_settings_provider.cc
  src/network/host_game_settings_provider.h
  src/network/network_protocol.h
  src/ui_fsmenu/launch_game.cc
  src/ui_fsmenu/launch_game.h
  src/ui_fsmenu/launch_mpg.cc
  src/ui_fsmenu/launch_spg.cc
  src/wlapplication.cc
Labels: enhancement, cleanup & refactoring, ui

#5871 Make `modify_unit` index lookup load-order-safe
  src/scripting/lua_root.cc
Labels: bug, tribes, addon

#5875 Disambiguate temporary savegame for multiple LAN games
  src/io/filesystem/CMakeLists.txt
  src/io/filesystem/filesystem.cc
  src/io/filesystem/filesystem.h
  src/logic/editor_game_base.cc
  src/logic/replay.cc
Labels: bug, multiplayer & networking, filesystem

#5868 Scalable Buildhelp Overlays
  data/images/wui/overlays/big.png
  data/images/wui/overlays/big_0.5.png
  data/images/wui/overlays/big_1.png
  data/images/wui/overlays/big_2.png
  data/images/wui/overlays/big_4.png
  data/images/wui/overlays/medium.png
  data/images/wui/overlays/medium_0.5.png
  data/images/wui/overlays/medium_1.png
  data/images/wui/overlays/medium_2.png
  data/images/wui/overlays/medium_4.png
  data/images/wui/overlays/mine.png
  data/images/wui/overlays/mine_0.5.png
  data/images/wui/overlays/mine_1.png
  data/images/wui/overlays/mine_2.png
  data/images/wui/overlays/mine_4.png
  data/images/wui/overlays/port.png
  data/images/wui/overlays/port_0.5.png
  data/images/wui/overlays/port_1.png
  data/images/wui/overlays/port_2.png
  data/images/wui/overlays/port_4.png
  data/images/wui/overlays/set_flag.png
  data/images/wui/overlays/set_flag_0.5.png
  data/images/wui/overlays/set_flag_1.png
  data/images/wui/overlays/set_flag_2.png
  data/images/wui/overlays/set_flag_4.png
  data/images/wui/overlays/small.png
  data/images/wui/overlays/small_0.5.png
  data/images/wui/overlays/small_1.png
  data/images/wui/overlays/small_2.png
  data/images/wui/overlays/small_4.png
  src/editor/editorinteractive.cc
  src/graphic/image_cache.cc
  src/graphic/image_cache.h
  src/wui/interactive_base.cc
  src/wui/interactive_base.h
  src/wui/interactive_player.cc
  src/wui/interactive_spectator.cc
Labels: enhancement, accessibility, graphics

#5883 Implement padding numbers with digit width space UTF-8 characters
  src/base/format/abstract_node.h
  src/base/format/float_node.h
  src/base/format/number_node.h
  src/base/format/write_number.h
  src/wui/info_panel.cc
Labels: enhancement, cleanup & refactoring, accessibility

#5879 Disallow add-ons which are incompatible with the current Widelands version
  src/logic/addons.cc
  src/logic/addons.h
  src/ui_fsmenu/addons/rows_ui.cc
Labels: bug, crashes or hangs, addon

#5869 Naval Warfare: Invasion Enhancements
  src/logic/map_objects/tribes/ship.cc
  src/logic/map_objects/tribes/soldier.cc
  src/wui/interactive_player.cc
Labels: enhancement, military, seafaring
